module.exports = (prams) => {
  return {
    "code":0,
    "msg":"success",
    "data":{
      "beginDate": "2020-07-20T00:00:00",
      "createdBy": 0,
      "createdTime": null,
      "endDate": "2020-07-20T00:00:00",
      "feederPolCityCode": "SZ",
      "feederPolCityName": "",
      "feederPolCname": "",
      "feederPolCode": "SK",
      "feederPolEname": "佛山",
      "feederPolType": "",
      "feederSchedule": "6/1",
      "feederVoyage": 7,
      "oceanFreightList": [
          {
              "chargeCode": "OCF",
              "chargeId": 2,
              "chargeMode": "coastPrice",
              "chargeType": "",
              "createdBy": 0,
              "createdTime": null,
              "currency": "",
              "payMode": "",
              "price": 0,
              "priceGp20": 0,
              "priceGp40": 0,
              "priceHq40": 0,
              "priceHq45": 0,
              "rateUnit": "",
              "state": "",
              "structure": ""
          }
      ],
      "podCityCode": "SIDELI",
      "podCityName": "",
      "podCname": "",
      "podCode": "SK",
      "podEname": "INDIA",
      "polCityCode": "SZ",
      "polCityName": "",
      "polCname": "",
      "polCode": "SK",
      "polCodeType": "",
      "polEname": "蛇口",
      "publishStatus": "invalid",
      "receiptArea": "珠三角",
      "remark": "测试数据",
      "routeCode": "SK-SK-AXX-0000000000000020",
      "routeId": 19,
      "shipCarrierCode": "MSC",
      "state": "valid",
      "surchargeList": [
          {
              "chargeCode": "附加费",
              "chargeId": 10,
              "chargeMode": "coastPrice",
              "chargeType": "起运港LOCAL",
              "createdBy": 0,
              "createdTime": null,
              "currency": "USD",
              "payMode": "",
              "price": 10,
              "priceGp20": 20,
              "priceGp40": 40,
              "priceHq40": 80,
              "priceHq45": 100,
              "rateUnit": "箱",
              "state": "valid",
              "structure": ""
          }
      ],
      "sysLineCode": "AXX",
      "updatedBy": 0,
      "updatedTime": null,
      "versionStatus": "new"
    }
}
};
