module.exports = (prams) => {
  return {
    "code":0,
    "msg":"success",
    "data":{
        "pageNum":1,
        "totalPage":100,
        "pageSize":100,
        "allColumns": [
            "polEname",
            "endDate",
            "transitPort3Ename",
            "feederMatchMode",
            "publishDate",
            "allin",
            "sailingDate",
            "bkgAgent",
            "effectiveType",
            "transitPort2Ename",
            "freeTimeDesc",
            "shipCarrierCode",
            "priceGp20",
            "podCode",
            "state",
            "podCountryName",
            "publishStatus",
            "externalDesc",
            "carrierService",
            "surchargeList",
            "blankSailing",
            "polCname",
            "recommendLevel",
            "voyage",
            "pricerName",
            "guidanceDesc",
            "feederRouteId",
            "sysLineCode",
            "weightDesc",
            "transitPort3Cname",
            "publisher",
            "transitPort1Ename",
            "shipTerms",
            "transitPort1Cname",
            "sameFlagCode",
            "feederPolCname",
            "podCityName",
            "priceGp40",
            "cargoLimited",
            "podEname",
            "routeId",
            "pricerDeptCode",
            "surchargeDesc",
            "internalDesc",
            "pricer",
            // "transitVoyage",
            "polCityName",
            "feederPolEname",
            "feederPolCode",
            "priceHq40",
            "cutoffDate",
            "polCode",
            "blType",
            "beginDate",
            "schedule",
            "issueWay",
            "transitPort2Cname",
            "priceHq45",
            "podCname",
            "attention",
            "subRouteList",
            "carrierLineName",
            "feederPolCode",
            "feederPolCname",
            "feederPolEname",
        ],
        "configColumns": [
            "priceGp20",
            "priceGp40",
            "priceHq40",
            "priceHq45",
            "remark",
            "beginDate",
            "feederPolCode",
            "polCode",
            "podCode",
            "surchargeList",
            "serviceCname",
            "shipCarrierCode",
            "receiptArea"
        ],
        "list":[
            {
                "beginDate": null,
                "createdBy": 0,
                "createdTime": null,
                "endDate": null,
                "feederPolCityCode": "FS",
                "feederPolCityName": "佛山",
                "feederPolCname": "佛山",
                "feederPolCode": "CNXSZ",
                "feederPolEname": "FOSHAN",
                "feederSchedule": "",
                "feederVoyage": 0,
                "oceanFreightList": [],
                "podCityCode": "",
                "podCityName": "",
                "podCname": "",
                "podCode": "INVD",
                "podEname": "",
                "polCityCode": "",
                "polCityName": "深圳",
                "polCname": "蛇口",
                "polCode": "SK",
                "polEname": "SHEKOU",
                "publishStatus": "",
                "receiptArea": "珠三角",
                "remark": "注意注意注意注意注意注意注意注意注意注意注意注意注意注意",
                "routeCode": "",
                "routeId": 2,
                "shipCarrierCode": "MSC",
                "state": "unpublished",
                "surchargeList": [
                    {
                        "chargeCode": "DOC",
                        "chargeName": "文件费",
                        "chargeMode": "basePrice",
                        "chargeType": "起运港LOCAL",
                        "createdBy": 0,
                        "createdTime": null,
                        "currency": "USD",
                        "oid": 3,
                        "payMode": "预付",
                        "price": 52.3,
                        "priceGp20": '',
                        "priceGp40": '',
                        "priceHq40": '',
                        "priceHq45": '',
                        "rateUnit": "箱",
                        "state": "valid",
                        "templateId": 2,
                        "updatedBy": 0,
                        "updatedTime": null
                    },
                    {
                        "chargeCode": "SEAL",
                        "chargeName": "封条费",
                        "chargeMode": "basePrice",
                        "chargeType": "目的港LOCAL",
                        "createdBy": 0,
                        "createdTime": null,
                        "currency": "USD",
                        "oid": 3,
                        "payMode": "到付",
                        "price": 52.3,
                        "priceGp20": 45,
                        "priceGp40": 45,
                        "priceHq40": 45,
                        "priceHq45": 45,
                        "rateUnit": "箱型",
                        "state": "valid",
                        "templateId": 2,
                        "updatedBy": 0,
                        "updatedTime": null
                    },
                    {
                        "chargeCode": "GKABF",
                        "chargeName": "港口安保费",
                        "chargeMode": "basePrice",
                        "chargeType": "运费附加费",
                        "createdBy": 0,
                        "createdTime": null,
                        "currency": "ASP",
                        "oid": 4,
                        "payMode": "无限制",
                        "price": 521.3,
                        "priceGp20": 121.2,
                        "priceGp40": 43,
                        "priceHq40": 23,
                        "priceHq45": 43,
                        "rateUnit": "票",
                        "state": "valid",
                        "templateId": 2,
                        "updatedBy": 0,
                        "updatedTime": null
                    }
                ],
                "sysLineCode": "",
                "updatedBy": 0,
                "updatedTime": null,
                "versionStatus": "",
                "serviceCnname": "321321",
                "priceGp20": 1,
                "priceGp40": 2,
                "priceHq40": 3,
                "priceHq45": 4,
                "currency": "USD",
                "beginDate":"2020-08-18",
                "endDate":"2020-09-18",
            },
            {
                "beginDate": null,
                "createdBy": 0,
                "createdTime": null,
                "endDate": null,
                "feederPolCityCode": "FS",
                "feederPolCityName": "佛山",
                "feederPolCname": "佛山",
                "feederPolCode": "CNXSZ",
                "feederPolEname": "FOSHAN",
                "feederSchedule": "",
                "feederVoyage": 0,
                "oceanFreightList": [],
                "podCityCode": "",
                "podCityName": "",
                "podCname": "",
                "podCode": "INVD",
                "podEname": "",
                "polCityCode": "",
                "polCityName": "深圳",
                "polCname": "蛇口",
                "polCode": "SK",
                "polEname": "SHEKOU",
                "publishStatus": "",
                "receiptArea": "珠三角",
                "remark": "测试数据",
                "routeCode": "",
                "routeId": 3,
                "shipCarrierCode": "MSC",
                "state": "published",
                "surchargeList": [],
                "sysLineCode": "",
                "updatedBy": 0,
                "updatedTime": null,
                "versionStatus": "",
                "priceGp20": '12',
                "priceGp40": '13',
                "priceHq40": '23',
                "priceHq45": '54',
                "weightPriceGp20": '1',
                "weightPriceGp40": '11',
                "weightPriceHq40": '111',
                "weightPriceHq45": '11',
                "beginDate":"2020-08-18",
                "endDate":"2020-09-18",
            }
        ]
    }
}
};
