module.exports = (params) => {
  return {
    "code": 0,
    "data": [
        {
            "createdBy": 0,
            "createdName": "",
            "createdTime": null,
            "currency": "USD",
            "feeCode": "AAC",
            "feeEnName": "AAC",
            "feeItemId": 0,
            "feeName": "加拿大海关申报费",
            "feeUnit": "",
            "foreignTaxRate": 0,
            "freeTaxType": "",
            "invoiceSumName": "",
            "mergeFeeCode": "",
            "mergeFeeName": "",
            "profitType": "",
            "receipayGroup": "",
            "revision": 0,
            "state": "",
            "taxClass": "",
            "taxClassNo": "",
            "updatedBy": 0,
            "updatedName": "",
            "updatedTime": null,
            "znTaxRate": 0
        },
        {
            "createdBy": 0,
            "createdName": "",
            "createdTime": null,
            "currency": "USD",
            "feeCode": "OCF",
            "feeEnName": "OCEAN FREIGHT",
            "feeItemId": 0,
            "feeName": "海运费",
            "feeUnit": "",
            "foreignTaxRate": 0,
            "freeTaxType": "",
            "invoiceSumName": "",
            "mergeFeeCode": "",
            "mergeFeeName": "",
            "profitType": "",
            "receipayGroup": "",
            "revision": 0,
            "state": "",
            "taxClass": "",
            "taxClassNo": "",
            "updatedBy": 0,
            "updatedName": "",
            "updatedTime": null,
            "znTaxRate": 0
        }
    ],
    "msg": "success"
  }
}