module.exports = (prams) => {
  return {
    "code": 0,
    "data": [
        {
            "bocRate": 0.2157,
            "createdBy": 0,
            "createdName": "",
            "createdTime": "2020-10-12T15:00:01",
            "effectDate": "2020-10-13",
            "exchangeRateId": 135,
            "exchangeRateTaskId": 665,
            "expireDate": "2020-10-13",
            "lowerRate": 0.2673,
            "presetStatus": "",
            "rate": 0.2157,
            "revision": 0,
            "srcCurrency": "THB",
            "state": "valid",
            "toCurrency": "CNY",
            "type": "settle",
            "updatedBy": 0,
            "updatedName": "",
            "updatedTime": null,
            "upperRate": 0.2657,
            "yearMon": "2020-10-13"
        },
        {
          "bocRate": 0.2157,
          "createdBy": 0,
          "createdName": "",
          "createdTime": "2020-10-12T15:00:01",
          "effectDate": "2020-10-13",
          "exchangeRateId": 136,
          "exchangeRateTaskId": 666,
          "expireDate": "2020-10-13",
          "lowerRate": 5.9,
          "presetStatus": "",
          "rate": 6.6821,
          "revision": 0,
          "srcCurrency": "USD",
          "state": "valid",
          "toCurrency": "CNY",
          "type": "settle",
          "updatedBy": 0,
          "updatedName": "",
          "updatedTime": null,
          "upperRate": 7.9,
          "yearMon": "2020-10-13"
        },
        {
          "bocRate": 0.2157,
          "createdBy": 0,
          "createdName": "",
          "createdTime": "2020-10-12T15:00:01",
          "effectDate": "2020-10-13",
          "exchangeRateId": 137,
          "exchangeRateTaskId": 667,
          "expireDate": "2020-10-13",
          "lowerRate": 0.12,
          "presetStatus": "",
          "rate": 0.1497,
          "revision": 0,
          "srcCurrency": "CNY",
          "state": "valid",
          "toCurrency": "USD",
          "type": "settle",
          "updatedBy": 0,
          "updatedName": "",
          "updatedTime": null,
          "upperRate": 0.4,
          "yearMon": "2020-10-13"
        },
        {
          "bocRate": 0.2157,
          "createdBy": 0,
          "createdName": "",
          "createdTime": "2020-10-12T15:00:01",
          "effectDate": "2020-10-13",
          "exchangeRateId": 136,
          "exchangeRateTaskId": 666,
          "expireDate": "2020-10-13",
          "lowerRate": 0.2673,
          "presetStatus": "",
          "rate": 0.8622,
          "revision": 0,
          "srcCurrency": "HKD",
          "state": "valid",
          "toCurrency": "CNY",
          "type": "settle",
          "updatedBy": 0,
          "updatedName": "",
          "updatedTime": null,
          "upperRate": 0.2657,
          "yearMon": "2020-10-13"
        },
        {
          "bocRate": 0.2157,
          "createdBy": 0,
          "createdName": "",
          "createdTime": "2020-10-12T15:00:01",
          "effectDate": "2020-10-13",
          "exchangeRateId": 137,
          "exchangeRateTaskId": 667,
          "expireDate": "2020-10-13",
          "lowerRate": 0.2673,
          "presetStatus": "",
          "rate": 1.1598,
          "revision": 0,
          "srcCurrency": "CNY",
          "state": "valid",
          "toCurrency": "HKD",
          "type": "settle",
          "updatedBy": 0,
          "updatedName": "",
          "updatedTime": null,
          "upperRate": 0.2657,
          "yearMon": "2020-10-13"
        },
        {
          "bocRate": 0.2157,
          "createdBy": 0,
          "createdName": "",
          "createdTime": "2020-10-12T15:00:01",
          "effectDate": "2020-10-13",
          "exchangeRateId": 136,
          "exchangeRateTaskId": 666,
          "expireDate": "2020-10-13",
          "lowerRate": 0.2673,
          "presetStatus": "",
          "rate": 7.75,
          "revision": 0,
          "srcCurrency": "USD",
          "state": "valid",
          "toCurrency": "HKD",
          "type": "settle",
          "updatedBy": 0,
          "updatedName": "",
          "updatedTime": null,
          "upperRate": 0.2657,
          "yearMon": "2020-10-13"
        },
        {
          "bocRate": 0.2157,
          "createdBy": 0,
          "createdName": "",
          "createdTime": "2020-10-12T15:00:01",
          "effectDate": "2020-10-13",
          "exchangeRateId": 137,
          "exchangeRateTaskId": 667,
          "expireDate": "2020-10-13",
          "lowerRate": 0.2673,
          "presetStatus": "",
          "rate": 0.129,
          "revision": 0,
          "srcCurrency": "HKD",
          "state": "valid",
          "toCurrency": "USD",
          "type": "settle",
          "updatedBy": 0,
          "updatedName": "",
          "updatedTime": null,
          "upperRate": 0.2657,
          "yearMon": "2020-10-13"
      }
    ],
    "msg": "success"
  }
};
