module.exports = (prams) => {
    return {
        "code": 0,
        "data": [
            {
                "cnName":"USD",
                "code":"USD",
                "createdBy":0,
                "createdName":"",
                "createdTime":null,
                "currencyId":1,
                "finCode":"USD",
                "revision":0,
                "standardStatus":"",
                "state":"",
                "updatedBy":0,
                "updatedName":"",
                "updatedTime":null
            },
            {
                "cnName":"CNY",
                "code":"CNY",
                "createdBy":0,
                "createdName":"",
                "createdTime":null,
                "currencyId":2,
                "finCode":"CNY",
                "revision":0,
                "standardStatus":"",
                "state":"",
                "updatedBy":0,
                "updatedName":"",
                "updatedTime":null
            },
            {
                "cnName":"HKD",
                "code":"HKD",
                "createdBy":0,
                "createdName":"",
                "createdTime":null,
                "currencyId":2,
                "finCode":"HKD",
                "revision":0,
                "standardStatus":"",
                "state":"",
                "updatedBy":0,
                "updatedName":"",
                "updatedTime":null
            },
            {
                "cnName":"EUR",
                "code":"EUR",
                "createdBy":0,
                "createdName":"",
                "createdTime":null,
                "currencyId":2,
                "finCode":"EUR",
                "revision":0,
                "standardStatus":"",
                "state":"",
                "updatedBy":0,
                "updatedName":"",
                "updatedTime":null
            },
            {
                "cnName":"GBP",
                "code":"GBP",
                "createdBy":0,
                "createdName":"",
                "createdTime":null,
                "currencyId":2,
                "finCode":"GBP",
                "revision":0,
                "standardStatus":"",
                "state":"",
                "updatedBy":0,
                "updatedName":"",
                "updatedTime":null
            }
        ],
        "msg": "success"
    }
};
