module.exports = (params) => {
    return {
        "code": 0,
        "data": {
            "allColumns": [],
            "configColumns": [],
            "currPage": 1,
            "list": [
                {
                    "acctVoucherNo": "",
                    "voucherNo": "Y0000032",
                    "balanceAmtAf": 380.00,
                    "balanceAmtBf": 380.00,
                    "bizWirteoffAmt": 380.00,
                    "currency": "CNY",
                    "invoiceNo": "",
                    "realAmt": 0,
                    "receivableRegId": 17,
                    "receivableRegNo": "REC2020102600017",
                    "recheckBy": 0,
                    "recheckName": "",
                    "recheckStatus": "",
                    "recheckTime": null,
                    "remark": "",
                    "reverseBy": "",
                    "reverseName": "",
                    "reverseTime": null,
                    "settleCompCode": "000001",
                    "settleCompName": "深圳分公司",
                    "settleCorpCode": "code111",
                    "settleCorpName": "测试客户1",
                    "totalWirteoffAmt": 380.00,
                    "writeoffBy": 13,
                    "writeoffExRate": 1.0000000000,
                    "writeoffName": "许坤才",
                    "writeoffReceipayId": 1,
                    "writeoffReceipayNo": "2020102600000004",
                    "writeoffReverseNo": "",
                    "writeoffTime": "2020-10-26 08:27:07"
                },
                {
                    "acctVoucherNo": "",
                    "voucherNo": "Y0000032",
                    "balanceAmtAf": 380.00,
                    "balanceAmtBf": 380.00,
                    "bizWirteoffAmt": 380.00,
                    "currency": "CNY",
                    "invoiceNo": "",
                    "realAmt": 0,
                    "receivableRegId": 17,
                    "receivableRegNo": "REC2020102600017",
                    "recheckBy": 0,
                    "recheckName": "",
                    "recheckStatus": "",
                    "recheckTime": null,
                    "remark": "",
                    "reverseBy": "",
                    "reverseName": "",
                    "reverseTime": null,
                    "settleCompCode": "000001",
                    "settleCompName": "深圳分公司",
                    "settleCorpCode": "code111",
                    "settleCorpName": "测试客户1",
                    "totalWirteoffAmt": 380.00,
                    "writeoffBy": 13,
                    "writeoffExRate": 1.0000000000,
                    "bankseqFilePath": '/test1.xls',
                    "writeoffName": "许坤才",
                    "writeoffReceipayId": 2,
                    "writeoffReceipayNo": "2020102600000005",
                    "writeoffReverseNo": "",
                    "writeoffTime": "2020-10-26 09:39:16"
                }
            ],
            "pageSize": 5,
            "totalCount": 2,
            "totalPage": 1
        },
        "msg": "success"
    }
}