module.exports = (params) => {
    return {
        "code": 0,
        "data": {
            "accountNo": "744557928354",
            "acctVoucherNo": "",
            "bankSeqNo": "123456",
            "bankseqFileCode": "",
            "batchNo": "2020102100000008",
            "confirmBy": 0,
            "confirmName": "",
            "confirmTime": null,
            "corpPrerevAccountId": 1,
            "createdBy": 13,
            "createdName": "许坤才",
            "createdTime": "2020-10-21 02:05:56",
            "currency": "CNY",
            "firstWriteoffReceipayNo": "",
            "interTransferFee": 0.00,
            "invoiceNo": "",
            "invoicesFeeList": [
                {
                    "currency": "USD",
                    "exSettleAmt": 10.00,
                    "feeAmt": 110.00,
                    "feeCode": "truck001",
                    "feeEnName": "truck001",
                    "feeId": 41,
                    "feeName": "拖车费",
                    "feeUnit": "UNIT",
                    "noWriteoffAmt": 10.00,
                    "orderNo": "",
                    "receipayType": "",
                    "serviceCode": "",
                    "serviceName": "",
                    "settleAmt": 10.00,
                    "settleCompCode": "000001",
                    "settleCompName": "深圳分公司",
                    "settleCorpCode": "code111",
                    "settleCorpName": "",
                    "settleCurrency": "USD",
                    "settleExRate": 1.0000000000,
                    "settleOrderFeeId": 42,
                    "settleOrderId": 14,
                    "settleOrderNo": "",
                    "taxRate": 6.0000000000,
                    "unitCount": 1,
                    "unitPrice": 110.00,
                    "writeoffAmt": 0.00
                }
            ],
            "lessPayAmt": 0.00,
            "payAccountNo": "123456",
            "payBankName": "中国银行",
            "payCorpCode": "cus000001",
            "payCorpName": "长帆开票测试",
            "proxyFileCode": "",
            "realAmt": 1000.00,
            "receivableRegId": 15,
            "receivableRegNo": "2020102100000015",
            "recvCompCode": "000001",
            "recvCompName": "深圳分公司",
            "recvDate": "2020-10-10",
            "remark": "备注",
            "settleCorpCode": "cus000001",
            "settleCorpName": "长帆开票测试",
            "state": "valid",
            "toReceivableRegId": 0,
            "totalAmt": 1000.00,
            "transferFeeAmt": 100.00,
            "transferFeeList": [
                {
                    "amt": 100.00,
                    "bankSeqNo": "123456",
                    "batchNo": "2020102100000008",
                    "createdBy": 13,
                    "createdName": "许坤才",
                    "createdTime": "2020-10-21 02:05:56",
                    "currency": "CNY",
                    "cutType": "exter_cut",
                    "feeId": 79,
                    "hasAllotAmt": 0.00,
                    "payOrderId": 0,
                    "receipayType": "receive",
                    "receivableRegId": 15,
                    "revision": 0,
                    "settleCompCode": "000001",
                    "settleCompName": "深圳分公司",
                    "state": "valid",
                    "transferFeeId": 1,
                    "updatedBy": 0,
                    "updatedName": "",
                    "updatedTime": null,
                    "writeoffReceipayNo": ""
                }
            ],
            "type": "customer_pay",
            "updatedBy": 0,
            "updatedName": "",
            "updatedTime": null,
            "voucherTime": null,
            "writeoffAmt": 0.00,
            "writeoffBalance": 0,
            "writeoffStatus": "nofinish"
        },
        "msg": "success"
    }
}