module.exports = (params) => {
    return {
        "code": 0,
        "data": {
            "allColumns": [
                "transitPortCode",
                "bkgReqNo",
                "bargePortCode",
                "cancelType",
                "remark",
                "oid",
                "parseStatus",
                "cutOffDate",
                "vessel",
                "isThrowOff",
                "createdTime",
                "state",
                "so",
                "cancelReason",
                "bargeCutOff",
                "updatedTime",
                "isCancel",
                "updatedBy",
                "bargeTdTime",
                "bindOrderTime",
                "isBindOrder",
                "isHeavy",
                "podPortCode",
                "voyage",
                "revision",
                "soFileNo",
                "etdTime",
                "createdBy",
                "containerInfo",
                "polPortCode"
            ],
            "configColumns": [],
            "currPage": 1,
            "list": [
                {
                    "bargeCutOff": null,
                    "bargePortCode": "2222",
                    "bargeTdTime": null,
                    "bindOrderTime": null,
                    "bkgReqNo": "111111",
                    "cancelReason": "222",
                    "cancelType": "222",
                    "containerInfo": "222",
                    "createdBy": 0,
                    "createdTime": null,
                    "cutOffDate": null,
                    "etdTime": null,
                    "isBindOrder": "2222",
                    "isCancel": "222",
                    "isHeavy": "222",
                    "isThrowOff": "222",
                    "oid": 1,
                    "parseStatus": "222",
                    "podPortCode": "222",
                    "polPortCode": "222",
                    "remark": "222",
                    "revision": 0,
                    "so": "134234234",
                    "soFileNo": "222",
                    "state": "222",
                    "transitPortCode": "22222",
                    "updatedBy": 0,
                    "updatedTime": null,
                    "vessel": "222",
                    "voyage": "222"
                }
            ],
            "pageSize": 10,
            "totalCount": 1,
            "totalPage": 1
        },
        "msg": "success"
    }
}