module.exports = (prams) => {
    return {
        "code": 0,
        "data":{
            "menu":[
                {
                    "auth":"no",
                    "childrenCount":1,
                    "icon":"",
                    "level":1,
                    "menuCode":"order_menu1",
                    "menuId":1,
                    "menuName":"订单中心",
                    "parentMenuId":0,
                    "seq":1,
                    "state":"valid",
                    "subMenu":[
                        {
                            "auth":"no",
                            "childrenCount":2,
                            "icon":"",
                            "level":2,
                            "menuCode":"order_menu1_list",
                            "menuId":2,
                            "menuName":"订单列表",
                            "parentMenuId":1,
                            "seq":12,
                            "state":"valid",
                            "subMenu":[
                                {
                                    "auth":"no",
                                    "childrenCount":0,
                                    "icon":"",
                                    "level":3,
                                    "menuCode":"order_menu1_list_PKZnsp",
                                    "menuId":95,
                                    "menuName":"订单新增",
                                    "parentMenuId":2,
                                    "seq":2,
                                    "state":"valid",
                                    "subMenu":[
    
                                    ],
                                    "sysAuthorityId":0,
                                    "url":""
                                },
                                {
                                    "auth":"no",
                                    "childrenCount":0,
                                    "icon":"",
                                    "level":3,
                                    "menuCode":"order_menu1_list_ZtvVjY",
                                    "menuId":97,
                                    "menuName":"订单编辑",
                                    "parentMenuId":2,
                                    "seq":2,
                                    "state":"valid",
                                    "subMenu":[
    
                                    ],
                                    "sysAuthorityId":0,
                                    "url":""
                                }
                            ],
                            "sysAuthorityId":0,
                            "url":"/order/list"
                        }
                    ],
                    "sysAuthorityId":0,
                    "url":"/test/1"
                },
                {
                    "auth":"no",
                    "childrenCount":0,
                    "icon":"",
                    "level":1,
                    "menuCode":"ilSgdy2",
                    "menuId":94,
                    "menuName":"基础数据",
                    "parentMenuId":0,
                    "seq":1,
                    "state":"valid",
                    "subMenu":[
    
                    ],
                    "sysAuthorityId":0,
                    "url":""
                },
                {
                    "auth":"no",
                    "childrenCount":1,
                    "icon":"",
                    "level":1,
                    "menuCode":"财务中心_子菜单2",
                    "menuId":3,
                    "menuName":"财务中心",
                    "parentMenuId":0,
                    "seq":2,
                    "state":"valid",
                    "subMenu":[
                        {
                            "auth":"no",
                            "childrenCount":0,
                            "icon":"",
                            "level":2,
                            "menuCode":"_HFmM",
                            "menuId":5,
                            "menuName":"财务中心_子菜单1",
                            "parentMenuId":3,
                            "seq":12,
                            "state":"valid",
                            "subMenu":[
    
                            ],
                            "sysAuthorityId":0,
                            "url":"/order/list"
                        }
                    ],
                    "sysAuthorityId":0,
                    "url":"/order/list"
                },
                {
                    "auth":"yes",
                    "childrenCount":2,
                    "icon":"",
                    "level":1,
                    "menuCode":"Finance",
                    "menuId":98,
                    "menuName":"财务",
                    "parentMenuId":0,
                    "seq":3,
                    "state":"valid",
                    "subMenu":[
                        {
                            "auth":"yes",
                            "childrenCount":0,
                            "icon":"",
                            "level":2,
                            "menuCode":"OtherFeeList",
                            "menuId":99,
                            "menuName":"订单费用",
                            "parentMenuId":98,
                            "seq":1,
                            "state":"valid",
                            "subMenu":[
    
                            ],
                            "sysAuthorityId":0,
                            "url":""
                        },
                        {
                            "auth":"yes",
                            "childrenCount":2,
                            "icon":"",
                            "level":2,
                            "menuCode":"Settlement",
                            "menuId":100,
                            "menuName":"结算单",
                            "parentMenuId":98,
                            "seq":2,
                            "state":"valid",
                            "subMenu":[
                                {
                                    "auth":"yes",
                                    "childrenCount":0,
                                    "icon":"",
                                    "level":3,
                                    "menuCode":"SettlementFeeList",
                                    "menuId":101,
                                    "menuName":"费用列表",
                                    "parentMenuId":100,
                                    "seq":1,
                                    "state":"valid",
                                    "subMenu":[
    
                                    ],
                                    "sysAuthorityId":0,
                                    "url":""
                                },
                                {
                                    "auth":"yes",
                                    "childrenCount":0,
                                    "icon":"",
                                    "level":3,
                                    "menuCode":"SettlementList",
                                    "menuId":102,
                                    "menuName":"结算单列表",
                                    "parentMenuId":100,
                                    "seq":2,
                                    "state":"valid",
                                    "subMenu":[
    
                                    ],
                                    "sysAuthorityId":0,
                                    "url":""
                                }
                            ],
                            "sysAuthorityId":0,
                            "url":""
                        }
                    ],
                    "sysAuthorityId":0,
                    "url":""
                }
            ]
        },
        "msg": "success"
    }
};