let prefix = "api/v1"
module.exports = [
    // 公共、字典
    { api: prefix + "/base/webapi/port/portList", routeName: "港口下拉" },
    { api: prefix + "/base/webapi/port/list/codes", routeName: "港口信息" },
    { api: prefix + "/base/webapi/systemLine/dictList", routeName: "系统航线下拉" },
    { api: prefix + "/base/webapi/systemLine/portSystemLine", routeName: "港口航线信息" },
    { api: prefix + "/base/webapi/systemLine/info", routeName: "系统航线详情" },
    { api: prefix + "/base/webapi/shippingCarrier/shippingCarrierList", routeName: "船司详情" },
    { api: prefix + "/base/webapi/shippingCarrier/info", routeName: "船司下拉" },
    { api: prefix + "/base/webapi/shipTerms/dictList", routeName: "运输条款" },
    { api: prefix + "/base/webapi/dict/list", routeName: "数据字典" },
    { api: prefix + "/base/webapi/feeitem/feeItemList", routeName: "费用项" },
    { api: prefix + "/base/webapi/currency/currencyList", routeName: "币别" },
    { api: prefix + "/base/webapi/currency/actualExchangeRate", routeName: "获取今日结算汇率" },
    { api: prefix + "/base/webapi/business/list", routeName: "业务类型" },
    { api: prefix + "/base/webapi/business/service/list", routeName: "业务类型" },
    { api: prefix + "/base/webapi/dept/employee/list", routeName: "获取员工" },
    { api: prefix + "/base/webapi/dept/employee/list/name", routeName: "模糊查询员工" },
    { api: prefix + "/base/webapi/dept/company/list", routeName: "获取所有公司" },
    { api: prefix + "/base/webapi/supplier/list", routeName: "供应商列表" },
    { api: prefix + "/order/book/free/save", routeName: "免用免堆信息录入"},
    { api: prefix + "/base/common/login", routeName: "登录" },
    { api: prefix + "/base/common/logout", routeName: "退出" },
    { api: prefix + "/base/common/session/refreshToken", routeName: "刷新获取新token" },
    { api: prefix + "/base/webapi/dept/employeeSelectlist", routeName: "员工信息下拉框数据" },
    { api: prefix + "/base/webapi/sysUser/info", routeName: "用户信息" },
    { api: prefix + "/base/webapi/cargo/hscode/list", routeName: "hscode模糊查询" },
    { api: prefix + "/base/webapi/cargo/type/list", routeName: "货品分类" },
    { api: prefix + "/base/webapi/cargo/unno/list", routeName: "国际危险品编码" },
    { api: prefix + "/base/webapi/file/class/list", routeName: "业务模块" },
    { api: prefix + "/base/webapi/file/type/list", routeName: "附件类型" },
    { api: prefix + "/base/webapi/file/upload", routeName: "单个文件上传" },
    { api: prefix + "/base/webapi/file/download", routeName: "单个文件下载" },
    { api: prefix + "/base/webapi/menu/allMenuCheckAuth", routeName: "单个文件下载" },
    { api: prefix + "/base/webapi/pageResource/allPageModuleCheckAuth", routeName: "单个文件下载" },
    // 分公司信息
    { api: prefix + "/base/webapi/company/pageList", routeName: "分公司列表分页查询" },
    { api: prefix + "/base/webapi/company/info", routeName: "详情" },
    { api: prefix + "/base/webapi/company/update", routeName: "修改" },
    // 分公司银行信息
    { api: prefix + "/base/webapi/companyBankAcct/pageList", routeName: "分公司银行账号列表分页查询" },
    { api: prefix + "/base/webapi/companyBankAcct/save", routeName: "增加" },
    { api: prefix + "/base/webapi/companyBankAcct/update", routeName: "修改" },
    { api: prefix + "/base/webapi/companyBankAcct/info", routeName: "详情" },
    { api: prefix + "/base/webapi/companyBankAcct/enabled", routeName: "启用/禁用" },
    // 包装类型
    { api: prefix + "/base/package/list", routeName: "包装类型" },
    // 船名航次
    { api: prefix + "/base/shipInfo/vessel/list", routeName: "船名查询" },
    { api: prefix + "/base/shipInfo/voyage/list", routeName: "航次查询" },
    // 用户相关
    { api: prefix + "/user/menu", routeName: "菜单" },
    { api: prefix + "/user/info", routeName: "" },
    { api: prefix + "/user/list", routeName: "" },
    { api: prefix + "/user/save", routeName: "" },
    { api: prefix + "/user/change-pwd", routeName: "" },
    { api: prefix + "/user/delete", routeName: "" },

    // 运价
    { api: prefix + "/charge/surcharge/list", routeName: "" },
    { api: prefix + "/charge/surcharge/add", routeName: "" },
    { api: prefix + "/charge/surcharge/info", routeName: "" },
    { api: prefix + "/charge/surcharge/update", routeName: "" },
    { api: prefix + "/charge/surcharge/delete", routeName: "" },
    { api: prefix + "/charge/surcharge/userSurchargeList", routeName: "" },
    { api: prefix + "/charge/weightLimitCharge/list", routeName: "" },
    { api: prefix + "/charge/weightLimitCharge/add", routeName: "" },
    { api: prefix + "/charge/weightLimitCharge/info", routeName: "" },
    { api: prefix + "/charge/weightLimitCharge/update", routeName: "" },
    { api: prefix + "/charge/weightLimitCharge/delete", routeName: "" },
    { api: prefix + "/charge/routeImport/list", routeName: "" },
    { api: prefix + "/charge/routeImport/info", routeName: "" },
    { api: prefix + "/charge/route/list", routeName: "" },
    { api: prefix + "/charge/route/feederList", routeName: "" },
    { api: prefix + "/charge/route/info", routeName: "" },
    { api: prefix + "/charge/route/sailingDateInfo", routeName: "" },

    // 运价维护
    // 大船
    { api: prefix + "/charge/mainRoute/list", routeName: "列表" },
    { api: prefix + "/charge/mainRoute/add", routeName: "新增" },
    { api: prefix + "/charge/mainRoute/edit", routeName: "编辑" },
    { api: prefix + "/charge/mainRoute/save", routeName: "列表单条保存" },
    { api: prefix + "/charge/mainRoute/info", routeName: "详情" },
    { api: prefix + "/charge/mainRoute/invalidRoute", routeName: "失效"},
    { api: prefix + "/charge/mainRoute/publishBatch", routeName: "批量发布"},
    { api: prefix + "/charge/mainRoute/invalidBatch", routeName: "批量失效"},
    { api: prefix + "/charge/mainRoute/mutiEdit", routeName: "批量修改"},
    { api: prefix + "/charge/mainRoute/export", routeName: "导出"},
    { api: prefix + "/charge/mainRoute/freeTime", routeName: "获取免用免堆信息"},

    { api: prefix + "/charge/feederRoute/surchargeInfo", routeName: "附加费下拉详情" },

    // 驳船
    { api: prefix + "/charge/feederRoute/list", routeName: "列表" },
    { api: prefix + "/charge/feederRoute/add", routeName: "新增" },
    { api: prefix + "/charge/feederRoute/edit", routeName: "编辑" },
    { api: prefix + "/charge/feederRoute/save", routeName: "列表保存" },
    { api: prefix + "/charge/feederRoute/info", routeName: "详情" },
    { api: prefix + "/charge/feederRoute/invalid", routeName: "失效" },
    { api: prefix + "/charge/feederRoute/invalidBatch", routeName: "批量失效" },
    { api: prefix + "/charge/feederRoute/publishBatch", routeName: "批量发布"},
    { api: prefix + "/charge/feederRoute/updateBatch", routeName: "批量修改"},
    { api: prefix + "/charge/feederRoute/export", routeName: "导出"},

    // 订单相关
    { api: prefix + "/order/shiporder/list", routeName: "订单查询列表"},
    { api: prefix + "/order/shiporder/create", routeName: "新建订单"},
    { api: prefix + "/order/shiporder/charge/create", routeName: "运价新建订单"},
    { api: prefix + "/order/shiporder/save", routeName: "订单保存"},
    { api: prefix + "/order/shiporder/info", routeName: "订单详情"},
    { api: prefix + "/order/shiporder/edit", routeName: "操作员编辑"},
    { api: prefix + "/order/shiporder/list/export", routeName: "订列表导出"},
    { api: prefix + "/order/shiporder/work", routeName: "分配岗位查询"},
    { api: prefix + "/order/shiporder/book/audit/refuse", routeName: "订单审核拒绝"},
    { api: prefix + "/order/shiporder/book/audit/pass", routeName: "订单审核通过"},
    { api: prefix + "/order/shiporder/book/free/save", routeName: "免用免堆信息录入"},
    { api: prefix + "/order/shiporder/book/notify/release", routeName: "业务通知放舱"},
    { api: prefix + "/order/shiporder/book/crash", routeName: "业务通知BKG加急订舱"},
    { api: prefix + "/order/shiporder/book/release", routeName: "操作放舱给客户"},
    { api: prefix + "/order/shiporder/book/release/cancel", routeName: "取消放舱给客户"},
    { api: prefix + "/order/shiporder/book/info", routeName: "订舱信息详情"},
    { api: prefix + "/order/shiporder/book/change/info", routeName: "做柜后改船"},
    { api: prefix + "/order/shiporder/book/change/save", routeName: "做柜后改船"},
    { api: prefix + "/order/shiporder/cancelRequest", routeName: "业务发起取消订单"},
    { api: prefix + "/order/shiporder/cancelHandle", routeName: "操作取消订单"},
    { api: prefix + "/order/shipping/workService/updateStatus", routeName: "服务项状态修改"},
    { api: prefix + "/order/shiporder/sellers", routeName: "查询销售"},
    { api: prefix + "/order/shiporder/copy", routeName: "复制订单"},
    { api: prefix + "/order/shiporder/finish", routeName: "订单完结"},
    { api: prefix + "/order/shiporder/book/so/list", routeName: "客户自定-so列表"},
    { api: prefix + "/order/shiporder/book/so/upload", routeName: "客户自定-上传so"},
    { api: prefix + "/order/shiporder/book/so/delete", routeName: "客户自定-so列表删除"},
    { api: prefix + "/order/shiporder/self/save", routeName: "客户自定-bd保存"},
    { api: prefix + "/order/shiporder/self/edit", routeName: "客户自定-op保存"},
    { api: prefix + "/order/shiporder/usbmit/cancel", routeName: "业务撤回已提交订单"},
    // 散货
    { api: prefix + "/order/shiporder/lcl/save", routeName: "委托订舱保存"},
    { api: prefix + "/order/shiporder/lcl/self/save", routeName: "客户自定保存"},
    { api: prefix + "/order/shiporder/lcl/audit/list", routeName: "订仓审核列表"},
    { api: prefix + "/order/shiporder/lcl/audit/list/export", routeName: "订仓审核列表导出"},
    { api: prefix + "/order/shiporder/lcl/audit/pass", routeName: "审核通过"},
    { api: prefix + "/order/shiporder/lcl/audit/refuse", routeName: "审核拒绝"},
    { api: prefix + "/order/shiporder/lcl/edit", routeName: "订单编辑"},
    { api: prefix + "/order/shiporder/lcl/cargo/edit", routeName: "修改货物信息"},
    { api: prefix + "/order/shipping/workService/edit/confirm", routeName: "服务修改提醒确认"},
    { api: prefix + "/order/shiporder/lcl/info", routeName: "订仓详情"},
    { api: prefix + "/order/shiporder/lcl/child/list", routeName: "订单散货子单列表"},
    { api: prefix + "/order/shiporder/lcl/create", routeName: "散货单创建整柜订单"},
    { api: prefix + "/order/shipping/whbook/save", routeName: "订仓保存"},
    { api: prefix + "/order/shipping/whbook/po/release", routeName: "业务放仓给客户"},
    { api: prefix + "/order/shipping/whbook/po/confirm", routeName: "仓核实单确认"},
    { api: prefix + "/order/shipping/whbook/lcl/confirm", routeName: "拼箱完成确认"},
    { api: prefix + "/order/shipping/whbook/lcl/confirm", routeName: "拼箱完成确认"},
    { api: prefix + "/order/shipping/whbook/file/upload", routeName: "客户自订上传PO"},
    { api: prefix + "/order/shipping/whbook/file/list", routeName: "文件列表"},
    { api: prefix + "/order/shipping/whbook/file/delete", routeName: "文件删除"},
    // 订舱相关
    { api: prefix + "/order/shiporder/spacebook/list", routeName: "订舱查询列表"},
    { api: prefix + "/order/shiporder/spacebook/info", routeName: "订舱单详情"},
    { api: prefix + "/order/shiporder/spacebook/so/list", routeName: "so列表查询"},
    { api: prefix + "/order/shiporder/spacebook/audit/joint/cancel", routeName: "协同审核人员撤回"},
    // 托书
    { api: prefix + "/order/shiporder/file/book/list", routeName: "列表"},
    { api: prefix + "/order/shiporder/file/book/delete", routeName: "删除"},
    { api: prefix + "/order/shiporder/file/book/upload", routeName: "新增"},
    // 附件
    { api: prefix + "/order/shiporder/file/list", routeName: "列表"},
    { api: prefix + "/order/shiporder/file/delete", routeName: "删除"},
    { api: prefix + "/order/shiporder/file/upload", routeName: "新增"},
    { api: prefix + "/order/shiporder/file/temp/download", routeName: "模板文件下载" },
    // 集装箱
    { api: prefix + "/order/shiporder/container/list", routeName: "列表"},
    { api: prefix + "/order/shiporder/container/create", routeName: "新增"},
    { api: prefix + "/order/shiporder/container/update", routeName: "更新"},
    { api: prefix + "/order/shiporder/container/drop", routeName: "甩柜"},
    { api: prefix + "/order/shiporder/container/import", routeName: "导入"},
    // 协同服务项
    { api: prefix + "/order/shiporder/joint/service/create", routeName: "新增协同服务项"},
    { api: prefix + "/order/shiporder/joint/service/list", routeName: "列表"},
    { api: prefix + "/order/shiporder/joint/service/delete", routeName: "删除"},
    { api: prefix + "/order/shiporder/joint/service/cancel", routeName: "撤回"},
    { api: prefix + "/order/shiporder/joint/service/cancel/audit", routeName: "撤回审核"},
    // 协同订单
    { api: prefix + "/order/joint/list", routeName: "列表"},
    { api: prefix + "/order/joint/list/export", routeName: "列表导出"},
    { api: prefix + "/order/joint/info", routeName: "详情"},
    { api: prefix + "/order/joint/service/refuse", routeName: "协同订单服务项拒绝"},
    // 服务项-报关
    { api: prefix + "/order/shipping/customs/list", routeName: "报关委托列表"},
    { api: prefix + "/order/shipping/customs/detail", routeName: "报关委托明细"},
    { api: prefix + "/order/shiporder/joint/list", routeName: "列表"},
    { api: prefix + "/order/shiporder/joint/list/export", routeName: "列表导出"},
    { api: prefix + "/order/shiporder/joint/info", routeName: "详情"},
    { api: prefix + "/order/shipping/customs/intrustDoc", routeName: "打印报关委托单详情"},
    { api: prefix + "/order/shiporder/joint/service/refuse", routeName: "协同订单服务项拒绝"},
    // 代理报检
    { api: prefix + "/order/shipping/inspection/list", routeName: "代理报检委托列表"},
    { api: prefix + "/order/shipping/inspection/getIntrustNo", routeName: "获取代理报检委托编号"},
    { api: prefix + "/order/shipping/inspection/save", routeName: "新增代理报检委托信息"},
    { api: prefix + "/order/shipping/inspection/updateStatus", routeName: "代理报检委托信息状态修改"},
    { api: prefix + "/order/shipping/inspection/delete", routeName: "代理报检信息删除"},
    { api: prefix + "/order/shipping/inspection/detail", routeName: "代理报检详情"},
    { api: prefix + "/order/shipping/inspection/temp/download", routeName: "代理报检模板文件下载"},
    { api: prefix + "/order/shipping/inspection/import", routeName: "代理报检解析上传箱单清单"},
    { api: prefix + "/order/shipping/inspection/fileList", routeName: "代理报检委托信息附件列表"},
    { api: prefix + "/order/shipping/inspection/deleteFile", routeName: "代理报检委托信息删除附件"},
    { api: prefix + "/order/shipping/inspection/file/upload", routeName: "代理报检委托信息附件上传"},
    { api: prefix + "/order/shipping/inspection/attachmentList", routeName: "附件类型列表"},
    // 检验检测-CIQ
    { api: prefix + "/order/shipping/ciq/list", routeName: "CIQ委托信息列表"},
    { api: prefix + "/order/shipping/ciq/getIntrustNo", routeName: "获取CIQ委托信息委托编号"},
    { api: prefix + "/order/shipping/ciq/save", routeName: "保存CIQ信息"},
    { api: prefix + "/order/shipping/ciq/updateStatus", routeName: "CIQ状态变更"},
    { api: prefix + "/order/shipping/ciq/delete", routeName: "删除CIQ信息"},
    { api: prefix + "/order/shipping/ciq/detail", routeName: "获取CIQ信息详情"},
    { api: prefix + "/order/shipping/ciq/import", routeName: "CIQ解析上传箱单清单"},
    { api: prefix + "/order/shipping/ciq/fileList", routeName: "CIQ附件列表"},
    { api: prefix + "/order/shipping/ciq/deleteFile", routeName: "CIQ删除附件"},
    { api: prefix + "/order/shipping/ciq/file/upload", routeName: "CIQ附件上传"},
    // 检验检测-BV
    { api: prefix + "/order/shipping/bv/list", routeName: "BV委托信息列表"},
    { api: prefix + "/order/shipping/bv/getIntrustNo", routeName: "获取BV委托信息委托编号"},
    { api: prefix + "/order/shipping/bv/save", routeName: "保存BV信息"},
    { api: prefix + "/order/shipping/bv/updateStatus", routeName: "BV状态变更"},
    { api: prefix + "/order/shipping/bv/delete", routeName: "删除BV信息"},
    { api: prefix + "/order/shipping/bv/detail", routeName: "获取BV信息详情"},
    { api: prefix + "/order/shipping/bv/import", routeName: "BV解析上传箱单清单"},
    { api: prefix + "/order/shipping/bv/fileList", routeName: "BV附件列表"},
    { api: prefix + "/order/shipping/bv/deleteFile", routeName: "BV删除附件"},
    { api: prefix + "/order/shipping/bv/file/upload", routeName: "BV附件上传"},
    // 检验检测-COC
    { api: prefix + "/order/shipping/coc/list", routeName: "COC/SOSA检验检测委托信息列表"},
    { api: prefix + "/order/shipping/coc/getIntrustNo", routeName: "获取COC/SOSA委托信息委托编号"},
    { api: prefix + "/order/shipping/coc/save", routeName: "保存COC/SOSA委托信息"},
    { api: prefix + "/order/shipping/coc/updateStatus", routeName: "COC/SOSA委托信息状态更新"},
    { api: prefix + "/order/shipping/coc/delete", routeName: "删除COC/SOSA委托信息"},
    { api: prefix + "/order/shipping/coc/detail", routeName: "获取COC/SOSA委托信息详情"},
    { api: prefix + "/order/shipping/coc/import", routeName: "COC/SOSA解析上传箱单清单"},
    { api: prefix + "/order/shipping/coc/fileList", routeName: "COC/SOSA附件列表"},
    { api: prefix + "/order/shipping/coc/deleteFile", routeName: "COC/SOSA删除附件"},
    { api: prefix + "/order/shipping/coc/file/upload", routeName: "COC/SOSA附件上传"},
    // 目的港-委托清关
    { api: prefix + "/order/shipping/customsClearance/file/zipDownload", routeName: "委托清关打包下载附件"},
    { api: prefix + "/order/shipping/customsClearance/list", routeName: "目的港委托清关列表"},
    { api: prefix + "/order/shipping/customsClearance/getIntrustNo", routeName: "获取清关委托单号"},
    { api: prefix + "/order/shipping/customsClearance/save", routeName: "保存委托清关"},
    { api: prefix + "/order/shipping/customsClearance/updateStatus", routeName: "更新委托清关状态"},
    { api: prefix + "/order/shipping/customsClearance/delete", routeName: "删除委托清关"},
    { api: prefix + "/order/shipping/customsClearance/detail", routeName: "委托清关详情"},
    { api: prefix + "/order/shipping/customsClearance/fileList", routeName: "委托清关H单附件列表"},
    { api: prefix + "/order/shipping/customsClearance/deleteFile", routeName: "委托清关删除附件"},
    { api: prefix + "/order/shipping/customsClearance/file/upload", routeName: "委托清关附件上传"},
    { api: prefix + "/order/shipping/customsClearance/attachmentList", routeName: "委托清关附件类别列表"},
    // 目的港-拖柜派送
    { api: prefix + "/order/shipping/delivery/fcl/intrust/list", routeName: "拖柜派送委托列表"},
    { api: prefix + "/order/shipping/delivery/fcl/reqno", routeName: "拖柜派送委托编号"},
    { api: prefix + "/order/shipping/delivery/fcl/intrust/save", routeName: "拖柜派送委托保存"},
    { api: prefix + "/order/shipping/delivery/fcl/intrust/delete", routeName: "拖柜派送委托删除"},
    { api: prefix + "/order/shipping/delivery/fcl/intrust/info", routeName: "拖柜派送详情"},
    { api: prefix + "/order/shipping/delivery/fcl/status/change", routeName: "拖柜派送状态变更"},
    { api: prefix + "/order/shipping/delivery/fcl/file/upload", routeName: "拖柜派送文件签收"},
    { api: prefix + "/order/shipping/delivery/fcl/file/delete", routeName: "文件删除"},
    { api: prefix + "/order/shipping/delivery/fcl/load/save", routeName: "拖柜派送配载保存"},
    { api: prefix + "/order/shipping/delivery/fcl/load/delete", routeName: "拖柜派送配载删除"},
    // 目的港-仓储-进仓计划
    { api: prefix + "/order/podwh/inplan/reqno", routeName: "获取进仓计划编号"},
    { api: prefix + "/order/podwh/inplan/save", routeName: "进仓计划保存"},
    { api: prefix + "/order/podwh/inplan/list", routeName: "进仓计划列表"},
    { api: prefix + "/order/podwh/inplan/info", routeName: "进仓计划详情"},
    { api: prefix + "/order/podwh/inplan/delete", routeName: "进仓计划删除"},
    // 目的港-仓储-实际进仓
    { api: prefix + "/order/podwh/in/reqno", routeName: "获取实际进仓编号"},
    { api: prefix + "/order/podwh/in/save", routeName: "实际进仓保存"},
    { api: prefix + "/order/podwh/in/list", routeName: "实际进仓列表"},
    { api: prefix + "/order/podwh/in/info", routeName: "实际进仓详情"},
    { api: prefix + "/order/podwh/in/delete", routeName: "实际进仓删除"},
    { api: prefix + "/order/podwh/in/item/list", routeName: "实际进仓项目明细"},
    // 目的港-仓储-出仓计划
    { api: prefix + "/order/podwh/outplan/reqno", routeName: "获取出仓计划编号"},
    { api: prefix + "/order/podwh/outplan/save", routeName: "出仓计划保存"},
    { api: prefix + "/order/podwh/outplan/list", routeName: "出仓计划列表"},
    { api: prefix + "/order/podwh/outplan/info", routeName: "出仓计划详情"},
    { api: prefix + "/order/podwh/outplan/delete", routeName: "出仓计划删除"},
    // 目的港-仓储-实际出仓
    { api: prefix + "/order/podwh/out/reqno", routeName: "获取出仓编号"},
    { api: prefix + "/order/podwh/out/save", routeName: "出仓保存"},
    { api: prefix + "/order/podwh/out/list", routeName: "出仓列表"},
    { api: prefix + "/order/podwh/out/info", routeName: "出仓详情"},
    { api: prefix + "/order/podwh/out/delete", routeName: "出仓删除"},
    // 目的港-仓储-散车派送
    { api: prefix + "/order/shipping/delivery/ltl/intrust/list", routeName: "散车派送委托列表"},
    { api: prefix + "/order/shipping/delivery/ltl/reqno", routeName: "散车派送委托编号"},
    { api: prefix + "/order/shipping/delivery/ltl/intrust/save", routeName: "散车派送委托保存"},
    { api: prefix + "/order/shipping/delivery/ltl/intrust/delete", routeName: "散车派送委托删除"},
    { api: prefix + "/order/shipping/delivery/ltl/intrust/info", routeName: "散车派送详情"},
    { api: prefix + "/order/shipping/delivery/ltl/status/change", routeName: "散车派送状态变更"},
    { api: prefix + "/order/shipping/delivery/ltl/file/upload", routeName: "散车派送文件签收"},
    { api: prefix + "/order/shipping/delivery/ltl/file/delete", routeName: "散车派送文件签收删除"},
    // 目的港-仓储-进仓事项
    { api: prefix + "/order/podwh/matter/list", routeName: "进仓事项列表"},
    { api: prefix + "/order/podwh/matter/save", routeName: "进仓事项保存"},
    { api: prefix + "/order/podwh/matter/info", routeName: "进仓事项详情"},
    { api: prefix + "/order/podwh/matter/delete", routeName: "进仓事项删除"},
    { api: prefix + "/order/podwh/matter/status/change", routeName: "进仓事项状态变更"},
    // 服务项-拖车
    { api: prefix + "/order/shipping/customsClearanceckIntrust/list", routeName: "车队委托列表"},
    { api: prefix + "/order/shipping/customsClearanceckIntrust/save", routeName: "车队委托新增"},
    { api: prefix + "/order/shipping/truckIntrust/delete", routeName: "车队委托删除"},
    { api: prefix + "/order/shipping/truckIntrust/updateIntrustStatus", routeName: "车队委托状态修改"},
    { api: prefix + "/order/shipping/truckIntrust/updateDispatchStatus", routeName: "车队派车状态修改"},
    { api: prefix + "/order/shipping/truckIntrust/getIntrustNo", routeName: "车队委托单号获取"},
    { api: prefix + "/order/shipping/truckLoad/list", routeName: "车队配载列表"},
    { api: prefix + "/order/shipping/truckLoad/save", routeName: "车队配载新增"},
    { api: prefix + "/order/shipping/truckLoad/delete", routeName: "车队配载删除"},
    { api: prefix + "/order/shipping/truckIntrust/saveBulk", routeName: "散车收货保存"},
    { api: prefix + "/order/shipping/truckIntrust/bulkDetail", routeName: "散车收货详情"},
    // 服务项-单证
    { api: prefix + "/order/shipping/bl/list", routeName: "提单列表"},
    { api: prefix + "/order/shipping/bl/listBox", routeName: "提单列表下拉"},
    { api: prefix + "/order/shipping/bl/save", routeName: "提单新增"},
    { api: prefix + "/order/shipping/bl/delete", routeName: "提单删除"},
    { api: prefix + "/order/shipping/bl/updateStatus", routeName: "提单状态保存"},
    { api: prefix + "/order/shipping/bl/detail", routeName: "详情"},
    { api: prefix + "/order/shipping/bl/createSerialNo", routeName: "生成提单号"},
    { api: prefix + "/order/shipping/bl/separate", routeName: "提单拆分"},
    { api: prefix + "/order/shipping/bl/merge", routeName: "提单并单"},
    { api: prefix + "/order/shipping/bl/createBlFromExist", routeName: "提单生成提单"},
    { api: prefix + "/order/shipping/bl/draft/export", routeName: "提单草单导出"},
    { api: prefix + "/order/shipping/bl/draft/confirm", routeName: "提单草单确认"},
    { api: prefix + "/order/shipping/bl/release/cancel", routeName: "提单撤回"},
    { api: prefix + "/order/shipping/bl/release/agree", routeName: "客户同意放货"},
    { api: prefix + "/order/shipping/bl/copy/confirm", routeName: "MBLCopy件确认"},
    { api: prefix + "/order/shipping/bl/si/list", routeName: "补料列表"},
    { api: prefix + "/order/shipping/bl/si/info", routeName: "补料详情"},
    { api: prefix + "/order/shipping/bl/si/save", routeName: "补料保存"},
    { api: prefix + "/order/shipping/bl/si/dn/pass", routeName: "船东费用商务审核通过"},
    { api: prefix + "/order/shipping/bl/si/dn/refuse", routeName: "船东费用商务审核拒绝"},
    { api: prefix + "/order/shipping/bl/si/export", routeName: "补料列表导出"},
    { api: prefix + "/order/shipping/bl/file/list", routeName: "提单附件列表"},
    { api: prefix + "/order/shipping/bl/file/upload", routeName: "提单附件列表"},
    { api: prefix + "/order/shipping/bl/file/delete", routeName: "提单附件删除"},
    { api: prefix + "/order/shipping/bl/take/list", routeName: "取单列表"},
    { api: prefix + "/order/shipping/bl/take/info", routeName: "取单详情"},
    { api: prefix + "/order/shipping/bl/take/save", routeName: "取单保存"},
    { api: prefix + "/order/shipping/bl/take/export", routeName: "取单列表导出"},
    { api: prefix + "/order/shipping/bl/put/list", routeName: "取单列表"},
    { api: prefix + "/order/shipping/bl/put/info", routeName: "取单详情"},
    { api: prefix + "/order/shipping/bl/put/save", routeName: "取单保存"},
    { api: prefix + "/order/shipping/bl/put/mail", routeName: "邮件发送"},
    { api: prefix + "/order/shipping/bl/fin/list", routeName: "业务及财务放单审核列表"},
    { api: prefix + "/order/shipping/bl/fin/apply", routeName: "业务发起放单给财务审核"},
    { api: prefix + "/order/shipping/bl/fin/audit/pass", routeName: "放单财务审核通过"},
    { api: prefix + "/order/shipping/bl/fin/audit/processing", routeName: "放单财务审核处理中"},
    { api: prefix + "/order/shipping/bl/pledge/order/list", routeName: "待押单订单列表"},
    { api: prefix + "/order/shipping/bl/log/list", routeName: "提单日志列表"},
    // 服务项-VGM
    { api: "api/v1/order/shipping/vgm/list", routeName: "VGM列表"},
    { api: "api/v1/order/shipping/vgm/save", routeName: "VGM新增"},
    { api: "api/v1/order/shipping/vgm/delete", routeName: "VGM删除"},
    { api: "api/v1/order/shipping/vgm/updateStatus", routeName: "VGM更新状态"},
    // 服务项-危险品申报
    { api: "api/v1/order/shipping/dangerous/list", routeName: "危险品列表"},
    { api: "api/v1/order/shipping/dangerous/detail", routeName: "危险品详情"},
    { api: "api/v1/order/shipping/dangerous/createSerialNo", routeName: "列编号"},
    { api: "api/v1/order/shipping/dangerous/save", routeName: "危险品新增"},
    { api: "api/v1/order/shipping/dangerous/delete", routeName: "危险品删除"},
    { api: "api/v1/order/shipping/dangerous/updateStatus", routeName: "更新状态"},
    { api: "api/v1/order/shipping/dangerous/uploadFile", routeName: "上传"},
    // 服务项-堆场装箱
    { api: prefix + "/order/shipping/yardBox/list", routeName: "堆场装箱列表"},
    { api: prefix + "/order/shipping/yardBox/detail", routeName: "堆场装箱详情"},
    { api: prefix + "/order/shipping/yardBox/save", routeName: "堆场装箱保存"},
    { api: prefix + "/order/shipping/yardBox/updateStatus", routeName: "堆场装箱状态更新"},
    // 仓储
    { api: prefix + "/order/warehouseInplan/listPage", routeName: "入仓计划列表"},
    { api: prefix + "/order/warehouseInplan/list", routeName: "入仓计划列表"},
    { api: prefix + "/order/warehouseInplan/detail", routeName: "入仓计划详情"},
    { api: prefix + "/order/warehouseIn/detail", routeName: "实际入仓详情"},
    { api: prefix + "/order/warehouseIn/createSerialNo", routeName: "实际入仓编号"},
    { api: prefix + "/order/warehouseInplan/delete", routeName: "入仓计划删除"},
    { api: prefix + "/order/warehouseInplan/createSerialNo", routeName: "入仓计划编号"},
    { api: prefix + "/order/warehouseInplan/save", routeName: "入仓计划保存"},
    { api: prefix + "/order/warehouseIn/listPage", routeName: "实际入仓列表"},
    { api: prefix + "/order/warehouseIn/list", routeName: "实际入仓列表"},
    { api: prefix + "/order/warehouseIn/save", routeName: "实际入仓保存"},
    { api: prefix + "/order/warehouseIn/listStock", routeName: "实际入仓库存列表"},
    { api: prefix + "/order/warehouseOutplan/listPage", routeName: "出仓计划列表"},
    { api: prefix + "/order/warehouseOutplan/list", routeName: "出仓计划列表"},
    { api: prefix + "/order/warehouseOutplan/detail", routeName: "出仓计划详情"},
    { api: prefix + "/order/warehouseOutplan/save", routeName: "出仓计划保存"},
    { api: prefix + "/order/warehouseOutplan/getSerialNo", routeName: "出仓计划编号"},
    { api: prefix + "/order/warehouseOut/getSerialNo", routeName: "实际出仓编号"},
    { api: prefix + "/order/warehouseOutplan/delete", routeName: "出仓计划删除"},
    { api: prefix + "/order/warehouseOut/listPage", routeName: "实际出仓列表"},
    { api: prefix + "/order/warehouseOut/list", routeName: "实际出仓列表"},
    { api: prefix + "/order/warehouseOut/detail", routeName: "实际出仓详情"},

    // 仓库
    { api: prefix + "/order/warehouse/list", routeName: "仓库列表"},
    { api: prefix + "/order/warehouse/save", routeName: "仓库保存"},
    { api: prefix + "/order/warehouse/delete", routeName: "仓库列表删除"},
    { api: prefix + "/order/warehouseStock/listPage", routeName: "库存列表"},
    { api: prefix + "/order/warehouseStock/log", routeName: "库存操作日志"},
    { api: prefix + "/order/warehouse/uploadFile", routeName: "仓位图上传文件"},
    { api: prefix + "/order/warehouse/updateStatus", routeName: "仓库状态修改"},

    // 服务项-熏蒸
    { api: prefix + "/order/shipping/fume/list", routeName: "熏蒸列表"},
    { api: prefix + "/order/shipping/fume/detail", routeName: "熏蒸详情"},
    { api: prefix + "/order/shipping/fume/save", routeName: "熏蒸保存"},
    { api: prefix + "/order/shipping/fume/delete", routeName: "熏蒸删除"},
    { api: prefix + "/order/shipping/fume/createSerialNo", routeName: "熏蒸委托编号"},
    { api: prefix + "/order/shipping/fume/uploadFile", routeName: "熏蒸上传附件"},
    { api: prefix + "/order/shipping/fume/updateStatus", routeName: "熏蒸上传附件"},
    // 货品
    { api: prefix + "/order/cargo/listPage", routeName: "货品列表"},
    { api: prefix + "/order/cargo/delete", routeName: "货品删除"},
    { api: prefix + "/order/cargo/save", routeName: "货品保存"},
    // 服务项-贸易单证
    // { api: prefix + "/order/shipping/document/list", routeName: "贸易单证列表"},
    // { api: prefix + "/order/shipping/document/save", routeName: "贸易单证保存"},
    // { api: prefix + "/order/shipping/document/delete", routeName: "贸易单证删除"},
    // { api: prefix + "/order/shipping/document/updateStatus", routeName: "贸易单证状态修改"},
    // { api: prefix + "/order/shipping/document/docDataDetail", routeName: "贸易单证数据"},
    // { api: prefix + "/order/shipping/document/saveDocData", routeName: "贸易单证数据保存"},
    // { api: prefix + "/order/shipping/document/uploadFile", routeName: "贸易单证附件上传"},
    { api: prefix + "/order/shipping/tradeDoc/list", routeName: "贸易单证列表"},
    { api: prefix + "/order/shipping/tradeDoc/save", routeName: "贸易单证保存"},
    { api: prefix + "/order/shipping/tradeDoc/delete", routeName: "贸易单证删除"},
    { api: prefix + "/order/shipping/tradeDoc/updateStatus", routeName: "贸易单证状态修改"},
    { api: prefix + "/order/shipping/tradeDoc/docDataDetail", routeName: "贸易单证数据"},
    { api: prefix + "/order/shipping/tradeDoc/saveDocData", routeName: "贸易单证数据保存"},
    { api: prefix + "/order/shipping/tradeDoc/uploadFile", routeName: "贸易单证附件上传"},
    { api: prefix + "/order/shipping/grtDoc/list", routeName: "保函列表"},
    { api: prefix + "/order/shipping/grtDoc/save", routeName: "保函保存"},
    { api: prefix + "/order/shipping/grtDoc/delete", routeName: "保函删除"},
    { api: prefix + "/order/shipping/grtDoc/updateStatus", routeName: "保函状态修改"},
    { api: prefix + "/order/shipping/grtDoc/docDataDetail", routeName: "保函数据"},
    { api: prefix + "/order/shipping/grtDoc/saveDocData", routeName: "保函数据保存"},
    { api: prefix + "/order/shipping/grtDoc/uploadFile", routeName: "保函附件上传"},
    // 寄单管理
    { api: prefix + "/order/shipping/post/list", routeName: "寄单列表"},
    { api: prefix + "/order/shipping/express/list", routeName: "寄单列表"},
    { api: prefix + "/order/shipping/post/save", routeName: "寄单保存"},
    { api: prefix + "/order/shipping/express/save", routeName: "寄单列表"},
    { api: prefix + "/order/shipping/post/delete", routeName: "寄单删除"},
    { api: prefix + "/order/shipping/express/delete", routeName: "寄单删除"},
    { api: prefix + "/order/shipping/post/detail", routeName: "寄单详情"},
    { api: prefix + "/order/shipping/express/detail", routeName: "寄单详情"},
    { api: prefix + "/order/shipping/post/getOrderDocs", routeName: "寄单获取订单单证"},
    { api: prefix + "/order/shipping/express/getOrderDoc", routeName: "寄单获取订单单证"},
    { api: prefix + "/order/shipping/post/updateStatus", routeName: "寄单状态修改"},
    { api: prefix + "/order/shipping/express/updateStatus", routeName: "寄单状态修改"},
    { api: prefix + "/order/shipping/express/confirmFee", routeName: "费用确认"},
    // 异常管理
    { api: prefix + "/order/shipping/workException/list", routeName: "异常列表"},
    { api: prefix + "/order/shipping/workException/save", routeName: "异常保存"},
    { api: prefix + "/order/shipping/workException/delete", routeName: "异常删除"},
    { api: prefix + "/order/shipping/workException/detail", routeName: "异常详情"},
    { api: prefix + "/order/shipping/workException/saveItem", routeName: "异常项保存"},
    { api: prefix + "/order/shipping/workException/saveProgress", routeName: "异常跟进保存"},
    { api: prefix + "/order/shipping/workException/deleteItem", routeName: "异常项删除"},
    { api: prefix + "/order/shipping/workException/deleteProgress", routeName: "异常项跟进记录删除"},
    { api: prefix + "/order/shipping/workException/uploadFile", routeName: "上传文件"},
    { api: prefix + "/order/shipping/workException/updateStatus", routeName: "异常项状态更新"},
    { api: prefix + "/order/shipping/workException/updateItemStatus", routeName: "异常跟进项状态更新"},
    { api: prefix + "/order/shipping/workException/getSerialNo", routeName: "获取异常编号"},
    // 目的港服务-换单
    { api: prefix + "/order/shipping/blExchange/list", routeName: "换单状态列表"},
    { api: prefix + "/order/shipping/blExchange/updateStatus", routeName: "换单状态更新"},
    { api: prefix + "/order/shipping/blExchange/uploadGuarantee", routeName: "上传放单保函附件"},
    // 财务-订单费用
    { api: prefix + "/fin/fee/uploadBusinessFee", routeName: "业务费用选择模板导入---自己定义的"},
    { api: prefix + "/fin/fee/saveOrderBizFee", routeName: "保存业务费用"},
    { api: prefix + "/fin/fee/orderFeeList", routeName: "订单费用列表"},
    { api: prefix + "/fin/fee/saveAsTemplate", routeName: "保存业务费用为模板"},
    { api: prefix + "/fin/fee/batchModifySettleUnit", routeName: "批量修改结算单位"},
    { api: prefix + "/fin/fee/confirmOrderFeeInvoiceStatus", routeName: "确认费用是否开票"},
    { api: prefix + "/fin/fee/confirmOrderFee", routeName: "确认应收或者应付费用"},
    { api: prefix + "/fin/fee/saveOrderSpecialFee", routeName: "保存专项管理费用（关账前）"},
    { api: prefix + "/fin/fee/myTemplate", routeName: "下拉显示我的费用模板"},
    // { api: prefix + "/fin/fee/getTemplateFee", routeName: "业务费用-选择模板创建费用"},
    { api: prefix + "/fin/fee/getOrderProfit", routeName: "获取订单的利润，是个列表，按月份进行的统计"},
    { api: prefix + "/fin/fee/getOrderFeeStat", routeName: "获取订单费用统计"},
    // { api: prefix + "/fin/fee/saveOrderBizFeeAfFinClose", routeName: "关账之后，进行业务费用调整保存"},
    // { api: prefix + "/fin/fee/saveOrderSpecialFeeAfFinClose", routeName: "保存专项管理费用（关账后）"},
    { api: prefix + "/fin/fee/orderProfitShareList", routeName: "查看订单利润分成（BD/OBD模式）"},
    { api: prefix + "/fin/fee/orderFeeHistory", routeName: "查看订单费用的变更历史"},
    { api: prefix + "/fin/fee/getOrderTaxStat", routeName: "获取订单税率"},
    { api: prefix + "/fin/fee/orderFeeCount", routeName: "获取订单的费用条数"},
    { api: prefix + "/fin/fee/mySpecialList", routeName: "我的专项管理"},
    { api: prefix + "/fin/fee/mySpecialDetail", routeName: "我的专项管理详情"},
    { api: prefix + "/fin/fee/orderCloseInfo", routeName: "获取订单关帐信息"},
    // 财务-feeitem
    { api: prefix + "/fin/feeitem/feeItemList", routeName: "费用项下拉列表"},
    { api: prefix + "/fin/feeitem/feeItemService", routeName: "获取费用项默认的服务项"}, // 弃用
    // { api: prefix + "/fin/feeitem/feeItemServiceCode", routeName: "获取费用项默认的服务项"}, // 废弃
    { api: prefix + "/fin/feeitem/specialList", routeName: "获取专项管理费用项"},
    // { api: prefix + "/fin/feeitem/feeItemList", routeName: "搜索获取费用项"},
    { api: prefix + "/fin/feeitem/feeClassList", routeName: "费用类别列表"},
    // 财务-结算单位
    { api: prefix + "/fin/settleUnit/list", routeName: "搜索获取结算单位（包含分公司，客户，供应商）"},
    { api: prefix + "/fin/settleUnit/bankAccountList", routeName: "结算单位银行账号信息查询"},
    // 财务-银行账号
    { api: prefix + "/fin/settleUnitBankAcct/bankAccountList", routeName: "查询所有有效的银行账号信息"},
    { api: prefix + "/fin/settleUnitBankAcct/companyBankAccountList", routeName: "分公司银行账号列表"},
    // 财务-账单
    { api: prefix + "/fin/bill/list", routeName: "订单关联的账单列表"},
    { api: prefix + "/fin/bill/getBillDetail", routeName: "展示账单的详细信息"},
    { api: prefix + "/fin/bill/exportBill", routeName: "在账单详情页上，导出账单"},
    { api: prefix + "/fin/bill/sendBillMail", routeName: "在账单详情页上，发送账单给客户"},
    { api: prefix + "/fin/bill/print", routeName: "账单打印记录信息"},
    { api: prefix + "/fin/bill/generateBill", routeName: "生成账单"},
    { api: prefix + "/fin/bill/customerConfirm", routeName: "在账单列表上，进行账单费用确认"},
    { api: prefix + "/fin/bill/billGenerateSo", routeName: "在账单列表上，发起由账单生成结算单的操作"},
    { api: prefix + "/fin/bill/invoiceConfirm", routeName: "在账单列表上，客户确认开票"},
    { api: prefix + "/fin/bill/listPage", routeName: "独立账单搜索列表分页查询页面"},
    // 财务-结算单
    { api: prefix + "/fin/settleOrder/listPage", routeName: "结算单列表"},
    { api: prefix + "/fin/settleOrder/generateSettleOrder", routeName: "选择费用 生成结算单 数据 默认是按照原币别进行计算"},
    { api: prefix + "/fin/settleOrder/settleOrderSave", routeName: "结算单保存"},
    { api: prefix + "/fin/settleOrder/settleOrderAdd", routeName: "结算单新增"},
    { api: prefix + "/fin/settleOrder/listAddFeePage", routeName: "列表:结算单添加费用"},
    { api: prefix + "/fin/settleOrder/listAddAllFee", routeName: "列表:结算单添加全部费用"},
    { api: prefix + "/fin/settleOrder/info", routeName: "详情:结算单查看详情"},
    { api: prefix + "/fin/settleOrder/settleOrderUpdate", routeName: "结算单编辑 费用项如果有 settleOrderId"},
    { api: prefix + "/fin/settleOrder/close", routeName: "关闭结算单"},
    { api: prefix + "/fin/settleOrder/merge", routeName: "合并结算单"},
    { api: prefix + "/fin/settleOrder/settleOrderFeeStatistics", routeName: "结算单申请付款页面费用汇总统计"},
    { api: prefix + "/fin/fee/listPage", routeName: "费用列表数据"},
    { api: prefix + "/fin/settleOrder/invoiceConfirm", routeName: "在账单列表上，客户确认开票"},
    // 财务-结算对账单
    { api: prefix + "/fin/settleOrderBill/listPage", routeName: "结算单对账单列表"},
    { api: prefix + "/fin/settleOrderBill/info", routeName: "结算单对账单详情"},
    { api: prefix + "/fin/settleOrderBill/export", routeName: "结算单对账单导出"},
    { api: prefix + "/fin/settleOrderBill/sendBillMail", routeName: "结算单对账单发送邮件"},
    // 财务-费用单
    { api: prefix + "/fin/finBill/listPage", routeName: "费用单列表"},
    { api: prefix + "/fin/finBill/getFinBillDetail", routeName: "费用单详情"},
    { api: prefix + "/fin/finBill/saveFinBill", routeName: "新增财务费用单"},
    { api: prefix + "/fin/finBill/finBillGenerateSo", routeName: "费用单生成结算单"},
    { api: prefix + "/fin/finBill/confirmFee", routeName: "费用单费用确认"},
    // 财务-关账调费
    { api: prefix + "/fin/feeAdjust/saveOrderBizFee", routeName: "关账之后，进行业务费用调整保存"},
    { api: prefix + "/fin/feeAdjust/saveOrderSpecialFee", routeName: "保存专项管理费用（关账后）"},
    { api: prefix + "/fin/feeAdjust/orderFeeAdjustList", routeName: "获取单个订单的关账调费列表"},
    { api: prefix + "/fin/feeAdjust/adjustAudit", routeName: "对调整申请进行审批，如果是审批未通过，那么需要填写说明"},
    { api: prefix + "/fin/feeAdjust/orderFeeAdjustDetail", routeName: "获取费用调整申请详情"},
    { api: prefix + "/fin/feeAdjust/feeAdjustList", routeName: "独立的关账调费列表"},
    // 财务-应收发票
    { api: prefix + "/fin/invoiceReceivableApply/listPage", routeName: "开票申请列表分页查询"},
    { api: prefix + "/fin/invoiceReceivableApply/createPaperInvoiceBatch", routeName: "开票申请批量打印，通过申请ids查询，返回发票列表"},
    { api: prefix + "/fin/invoiceReceivable/print", routeName: "应收发票打印"},
    { api: prefix + "/fin/invoiceReceivableApply/close", routeName: "开票申请关闭"},
    { api: prefix + "/fin/invoiceReceivableApply/getPaperInvoiceList", routeName: "获取纸质发票待开票列表"},
    // 财务-凭证
    { api: prefix + "/fin/voucher/receipayWriteOffGenerate", routeName: "收款单核销，付款单核销生成凭证"},
    { api: prefix + "/fin/voucher/nopayWriteOffGenerate", routeName: "其它核销，对冲生成凭证"},  
    // { api: prefix + "/fin/voucher/nopayWriteOffGenerate", routeName: "其它核销，坏账生成凭证"},
    // 财务-应付
    { api: prefix + "/fin/pay/prepay/queryPrepayApplyPage", routeName: "预付款申请列表"},
    { api: prefix + "/fin/pay/prepay/savePrepayApply", routeName: "预付款申请保存"},
    { api: prefix + "/fin/pay/prepay/queryPrepayApplyInfo", routeName: "预付款申请详情"},
    { api: prefix + "/fin/pay/prepay/approvePrepayApply", routeName: "预付款申请审批"},
    { api: prefix + "/fin/pay/prepay/prepayAccountListPage", routeName: "供应商预付余额列表"},
    { api: prefix + "/fin/pay/prepay/prepayAccountLogListPage", routeName: "预付出入明细列表"},
    { api: prefix + "/fin/pay/settle/savePayApplySettle", routeName: "结算付款申请保存"},
    { api: prefix + "/fin/pay/settle/queryPayApplySettlePage", routeName: "结算单付款申请列表"},
    { api: prefix + "/fin/pay/settle/queryPayApplySettleInfo", routeName: "结算单付款申请详情"},
    { api: prefix + "/fin/pay/settle/approvePayApplySettle", routeName: "结算付款单申请审批"},
    { api: prefix + "/fin/pay/settle/prepaymentPreView", routeName: "结算付款申请预付抵账数据查询"},
    { api: prefix + "/fin/pay/settle/delayInvoice", routeName: "标记后补发票"},
    { api: prefix + "/fin/pay/order/queryPayOrderPage", routeName: "付款单列表分页查询"},
    { api: prefix + "/fin/pay/order/queryPayOrderInfo", routeName: "付款单详情查询"},
    { api: prefix + "/fin/pay/order/acceptancePayOrder", routeName: "付款单受理"},
    { api: prefix + "/fin/pay/order/payOrderInvoiceRelation", routeName: "付款单关联发票"},
    { api: prefix + "/fin/pay/order/savePayOrderBankTransferInfo", routeName: "付款单转账手续费新增或更新"},
    { api: prefix + "/fin/pay/order/markPayOrderWrong", routeName: "付款单付错登记"},
    { api: prefix + "/fin/pay/order/payOrderPrepayRefund", routeName: "付款单预付退款"},
    { api: prefix + "/fin/pay/order/payOrderWriteOffPreview", routeName: "付款单核销申请数据查询，用于付款单跳转核销申请页面时的数据获取"},
    { api: prefix + "/fin/pay/order/mergeMultiPayOrder", routeName: "合并付款"},
    { api: prefix + "/fin/pay/order/queryPayApplySettle", routeName: "结算付款单申请审批操作"},
    { api: prefix + "/fin/pay/order/queryPayOrderList", routeName: "付款单列表查询（导出"},
    { api: prefix + "/fin/pay/payInfo/queryPayInfoInvoices", routeName: "付款信息已关联的发票信息"},
    { api: prefix + "/fin/writeoffPay/queryWriteoffPayPageList", routeName: "付款核销分页查询"},
    { api: prefix + "/fin/writeoffPay/saveWriteoffPayOrder", routeName: "结算付款核销"},
    { api: prefix + "/fin/writeoffPay/queryPayWriteoff", routeName: "应付核销详情查询"},
    { api: prefix + "/fin/writeoffPay/confirmPayWriteoff", routeName: "核销复核"},
    { api: prefix + "/fin/writeoffPay/writeoffUnlock", routeName: "核销结算"},
    { api: prefix + "/fin/writeoffPay/writeoffRollback", routeName: "反核销"},
    { api: prefix + "/fin/writeoffPay/afreshWriteoff", routeName: "重新核销"},
    { api: prefix + "/fin/pay/settle/queryPayApplySettle", routeName: "结算单发起付款申请详情"},
    // 财务-应收
    { api: prefix + "/fin/receivableReg/listPage", routeName: "收款登记列表"},
    { api: prefix + "/fin/receivableReg/info", routeName: "收款登记详情"},
    { api: prefix + "/fin/receivableReg/add", routeName: "收款登记添加"},
    { api: prefix + "/fin/receivableReg/update", routeName: "收款登记修改"},
    { api: prefix + "/fin/receivableReg/listInvoiceReceivable", routeName: "应收发票查询"},
    { api: prefix + "/fin/receivableReg/relateInvoiceReceivable", routeName: "关联发票"},
    { api: prefix + "/fin/receivableReg/transfer", routeName: "收款登记转移"},
    { api: prefix + "/fin/receivableRegTransfer/listPage", routeName: "收款登记转移列表"},
    { api: prefix + "/fin/receivableRegTransfer/confirm", routeName: "收款登记转移审核确认"},
    { api: prefix + "/fin/receivableRegTransfer/refund", routeName: "收款登记退款申请"},
    { api: prefix + "/fin/receivableRegTransfer/uploadBankseqFile", routeName: "上传水单"},
    { api: prefix + "/fin/receivableRegTransfer/uploadProxyFile", routeName: "上传委托书"},
    { api: prefix + "/fin/invoiceReceivableApply/registerInvoice", routeName: "手填发票号"},
    { api: prefix + "/fin/invoiceReceivableApply/createElectronicInvoiceBatch", routeName: "批量电子发票生成"},
    { api: prefix + "/fin/invoiceReceivableApply/getSettleUnitInvoiceInfo", routeName: "结算单位开票信息查询"},
    { api: prefix + "/fin/invoiceReceivableApply/settleOrderFeeList", routeName: "结算单费用列表"},
    { api: prefix + "/fin/invoiceReceivableApply/invoiceApplySave", routeName: "开票申请保存"},
    { api: prefix + "/fin/invoiceReceivableApply/previewPrint", routeName: "开票申请预览打印"},
    { api: prefix + "/fin/invoiceReceivable/listPage", routeName: "应收列表分页查询"},
    { api: prefix + "/fin/invoiceReceivable/cancel", routeName: "发票冲红作废"},
    { api: prefix + "/fin/invoiceReceivable/info", routeName: "应收发票详情"},
    { api: prefix + "/fin/payApplyReceiveRefund/listPage", routeName: "收款退款申请单列表分页查询"},
    { api: prefix + "/fin/payApplyReceiveRefund/info", routeName: "收款退款申请单详情"},
    { api: prefix + "/fin/payApplyReceiveRefund/confirm", routeName: "收款退款申请单确认"},
    { api: prefix + "/fin/writeoffRecv/invoiceReceivableFeeList", routeName: "可核销发票费用列表"},
    { api: prefix + "/fin/writeoffRecv/settleOrderList", routeName: "可核销结算单列表"},
    { api: prefix + "/fin/writeoffRecv/settleOrderFeeList", routeName: "结算单费用列表"},
    { api: prefix + "/fin/writeoffRecv/writeoff", routeName: "收款核销"},
    { api: prefix + "/fin/writeoffRecv/listPage", routeName: "收款核销列表分页查询"},
    { api: prefix + "/fin/writeoffRecv/info", routeName: "收款核销详情"},
    { api: prefix + "/fin/writeoffRecv/invoiceReceivableApply", routeName: "收款核销开票申请"},
    { api: prefix + "/fin/writeoffRecv/recheck", routeName: "收款核销"},
    { api: prefix + "/fin/writeoffRecv/unlock", routeName: "收款核销"},
    { api: prefix + "/fin/writeoffRecv/reverse", routeName: "收款核销反核销"},
    { api: prefix + "/fin/writeoffRecv/toReWriteoff", routeName: "收款核销重新核销"},
    { api: prefix + "/fin/writeoffRecv/uploadBankseqFile", routeName: "上传水单"},
    { api: prefix + "/fin/writeoffRecv/uploadProxyFile", routeName: "上传委托书"},
    { api: prefix + "/fin/receivableReg/writeoff", routeName: "收款登记核销"},
    { api: prefix + "/fin/receivableReg/listInvoiceReceivable", routeName: "应收发票列表查询"},
    { api: prefix + "/fin/receivableReg/relateInvoiceReceivable", routeName: "关联发票"},
    { api: prefix + "/fin/receivableReg/addTransferFee", routeName: "收款登记手续费添加"},
    { api: prefix + "/fin/receivableReg/deleteTransferFee", routeName: "收款登记手续费删除"},
    { api: prefix + "/fin/receivablePrerev/listPage", routeName: "预收列表"},
    { api: prefix + "/fin/receivablePrerev/info", routeName: "预收款详情"},
    { api: prefix + "/fin/receivablePrerev/refund", routeName: "预收款退款申请"},
    { api: prefix + "/fin/receivablePrerev/toWriteoff", routeName: " 转到预收抵账"},
    { api: prefix + "/fin/receivablePrerev/writeoff", routeName: " 预收抵账核销"},
    { api: prefix + "/fin/receivablePrerev/transfer", routeName: " 预收转移"},
    { api: prefix + "/fin/receivableReg/uploadBankseqFile", routeName: "上传水单"},
    { api: prefix + "/fin/receivableReg/uploadProxyFile", routeName: "上传委托书"},
    { api: prefix + "/fin/receivableReg/importBatch", routeName: "批量导入"},
    { api: prefix + "/fin/receivableReg/toPrerev", routeName: "收款登记转预收"},
    { api: prefix + "/fin/receivableReg/refund", routeName: "收款登记退款申请"},
    { api: prefix + "/fin/receivableReg/confirm", routeName: "收款登记确认"},
    { api: prefix + "/fin/receivableReg/delete", routeName: "收款登记删除"},
    //客商预收预付
    { api: prefix + "/fin/prerevAccount/listPage", routeName: "预收余额列表"},
    { api: prefix + "/fin/prerevAccountLog/listPage", routeName: "预收账户余额日志列表"},
    // 财务-应付发票
    { api: prefix + "/fin/invoicePayment/listPage", routeName: "应收发票列表分页查询"},
    { api: prefix + "/fin/invoicePayment/info", routeName: "应付发票详情"},
    { api: prefix + "/fin/invoicePayment/add", routeName: "应付发票登记"},
    { api: prefix + "/fin/invoicePayment/receive", routeName: "应收发票财务标记已收"},
    { api: prefix + "/fin/invoicePayment/relatePayInfo", routeName: "应付发票关联付款单"},
    { api: prefix + "/fin/invoicePayment/delete", routeName: "删除发票"},
    { api: prefix + "/fin/invoicePayment/listPayInfo", routeName: "请款单列表查询"},
    { api: prefix + "/fin/invoicePayment/usableList", routeName: "查询指定付款分公司及供应商已登记未且可使用的应付发票列表"},
    // 财务-坏账核销
    { api: prefix + "/fin/settleOrderBaddebt/listPage", routeName: "坏账核销列表"},
    { api: prefix + "/fin/settleOrderBaddebt/applyDetail", routeName: "申请发起详情"},
    { api: prefix + "/fin/settleOrderBaddebt/info", routeName: "申请详情"},
    // { api: prefix + "/fin/settleOrderBaddebt/edit", routeName: "提交申请"},
    { api: prefix + "/fin/settleOrderBaddebt/apply", routeName: "提交申请"},
    { api: prefix + "/fin/settleOrderBaddebt/audit", routeName: "坏账审批"},
    { api: prefix + "/fin/writeoffNopay/unlock", routeName: "坏账-核销解锁"},
    { api: prefix + "/fin/writeoffNopay/reverse", routeName: "坏账-反核销"},
    { api: prefix + "/fin/writeoffNopay/confirmWriteoff", routeName: "坏账-核销复核"},
    // { api: prefix + "/fin/settleOrderBaddebt/audit", routeName: "坏账-生成凭证"},
    { api: prefix + "/fin/writeoffNopay/gedging/listPage", routeName: "对冲核销列表"},
    //订单-通知
    { api: prefix + "/order/notice/list", routeName: "通知列表"},
    { api: prefix + "/order/notice/detail", routeName: "通知详情"},
    //订单-供应商
    { api: prefix + "/crm/supplier/list", routeName: "供应商信息模糊查询"},
    { api: prefix + "/crm/supplier/info", routeName: "根据供应商ID获取供应商信息"},
    { api: prefix + "/crm/customer/list", routeName: "客商信息模糊查询"},
    { api: prefix + "/crm/customer/info", routeName: "根据客商ID获取客商信息"},
    //订单-供应商对账单
    { api: prefix + "/fin/supplierBill/listPage", routeName: "供应商对账单列表"},
    { api: prefix + "/fin/supplierBill/saveSupplierBill", routeName: "保存导入的供应商对账单"},
    { api: prefix + "/fin/supplierBill/getSupplierBillDetail", routeName: "供应商账单详情"},
    { api: prefix + "/fin/supplierBill/listSupplierBillFeePage", routeName: "对账详情的供应商账单（费用）列表"},
    { api: prefix + "/fin/supplierBill/listCompanyFeePage", routeName: "对账详情的费用信息列表"},
    { api: prefix + "/fin/supplierBill/importFee", routeName: "费用导入（自动导入、结算单导入）"},
    { api: prefix + "/fin/supplierBill/confirmAll", routeName: "对账详情费用确认（删除无关费用）"},
    { api: prefix + "/fin/supplierBill/lockOrUnlockFee", routeName: "费用解锁和锁定"},
    { api: prefix + "/fin/supplierBill/supplierGenerateSo", routeName: "对账单生成结算单"},
    { api: prefix + "/fin/supplierBill/diffCompare", routeName: "对账单明细差异查看"},
    //订单-对冲
    { api: prefix + "/fin/gedging/listPage", routeName: "列表:对冲申请" },
    { api: prefix + "/fin/gedging/applyDetailBySettleOrder", routeName: "详情:结算单列表发起对冲" },
    { api: prefix + "/fin/gedging/applyDetailBySettleOrderDetail", routeName: "详情:结算单详情发起对冲" },
    { api: prefix + "/fin/gedging/apply", routeName: "对冲申请提交" },
    { api: prefix + "/fin/gedging/audit", routeName: "列表:对冲审批" },
    { api: prefix + "/fin/gedging/info", routeName: "对冲单详情" },
    { api: prefix + "/fin/gedging/edit", routeName: "对冲申请修改接口" },
    { api: prefix + "/fin/gedging/autoCompulateGedgingFee", routeName: "对冲申请详情，自动计算对冲金额" },
    //财务-凭证管理
    { api: prefix + "/fin/acct/subjectList", routeName: "凭证管理:会计科目列表" },
    { api: prefix + "/fin/acct/subjectSave", routeName: "凭证管理:新增会计科目管理" },
    { api: prefix + "/fin/acct/feeItemSubjectList", routeName: "凭证管理:费用项科目管理列表" },
    { api: prefix + "/fin/acct/feeItemSubjectSave", routeName: "凭证管理:新增或修改费用项科目" },
    { api: prefix + "/fin/acct/voucherClassList", routeName: "凭证管理:凭证字列表" },
    { api: prefix + "/fin/acct/voucherClassSave", routeName: "凭证管理:新增凭证字" },
    { api: prefix + "/fin/acct/submatchList", routeName: "凭证管理:业务子科目列表" },
    { api: prefix + "/fin/acct/submatchSave", routeName: "凭证管理:新增业务子科目" },
    { api: prefix + "/fin/acct/acBookList", routeName: "凭证管理:账簿列表" },
    { api: prefix + "/fin/acct/acBookSave", routeName: "凭证管理:新增账簿" },
    { api: prefix + "/fin/acct/dimensionList", routeName: "凭证管理:核算维度列表" },
    { api: prefix + "/fin/acct/sceneList", routeName: "凭证管理:凭证场景查询列表" },
    { api: prefix + "/fin/acct/sceneSave", routeName: "凭证管理:新增凭证场景" },
    { api: prefix + "/fin/acct/sceneGroupList", routeName: "凭证场景:凭证场景分组" },
    { api: prefix + "/fin/voucher/voucherList", routeName: "凭证管理:凭证列表" },
    { api: prefix + "/fin/voucher/voucherView", routeName: "凭证管理:凭证详情" },
    { api: prefix + "/fin/voucher/voucherDelete", routeName: "凭证管理:删除凭证" },
    //财务-关账
    { api: prefix + "/fin/finClose/precloseApplyAudit", routeName: "预关账:预关账申请审批" },
    { api: prefix + "/fin/finClose/failPreclosingList", routeName: "预关账:获取当前预关账失败列表" },
    { api: prefix + "/fin/finClose/precloseApply", routeName: "预关账:发起预关账申请" },
    { api: prefix + "/fin/finClose/precloseApplyList", routeName: "预关账:预关账申请列表" },
    { api: prefix + "/fin/finClose/preclose", routeName: "预关账:手动预关账" },
    { api: prefix + "/fin/finClose/precloseApplyLog", routeName: "预关账:预关账申请日志" },
    { api: prefix + "/fin/finClose/close", routeName: "预关账:总关账" },
    { api: prefix + "/fin/finClose/closeList", routeName: "预关账:总关账列表" },
    //财务-财务日期
    { api: prefix + "/fin/sysDate/getSysDate", routeName: "财务-财务日期" },
    //财务-快递费
    { api: prefix + "/fin/expressBill/listPage", routeName: "快递费-快递费对账分页列表" },
    { api: prefix + "/fin/expressBill/importBill", routeName: "快递费-快递费账单导入" },
    { api: prefix + "/fin/expressBill/info", routeName: "快递费-快递费账单数据详情" },
    { api: prefix + "/fin/expressBill/detail", routeName: "快递费-快递费账单数据详情" },
    { api: prefix + "/fin/expressBill/deleteExpressBillFee", routeName: "快递费-快递费账单费用删除" },
    { api: prefix + "/fin/expressBill/listExpressBillFeePage", routeName: "快递费-供应商账单费用列表分页" },
    { api: prefix + "/fin/expressBill/listCompanyFeePage", routeName: "快递费-公司寄单费用列表分页" },
    { api: prefix + "/fin/expressBill/getCompareDetail", routeName: "快递费-快递账单对账结果详情" },
    { api: prefix + "/fin/expressBill/listExpressBillFeeCompareLogPage", routeName: "快递费-供应商账单费用对账明细列表" },
    { api: prefix + "/fin/expressBill/listCompanyFeeCompareLogPage", routeName: "快递费-公司寄单费用对账明细列表" },
    { api: prefix + "/fin/expressBill/confirm", routeName: "快递费-对账详情费用确认" },
    { api: prefix + "/fin/expressBill/compare", routeName: "快递费-对账详情费用确认" },
    { api: prefix + "/fin/expressBill/createSettleOrder", routeName: "快递费-对账详情费用确认" },
    { api: prefix + "/fin/expressBill/getCompanyFeeTotal", routeName: "快递费-公司寄单费用汇总查询" },
    //基础数据-通用数据-税率配置
    { api: prefix + "/fin/tax/taxRateConfigPageList", routeName: "税率配置-列表" },
    { api: prefix + "/fin/tax/saveTaxRateConfig", routeName: "税率配置-新增" },
    { api: prefix + "/fin/tax/updateTaxRateConfig", routeName: "税率配置-修改" },
    { api: prefix + "/fin/tax/deleteTaxRateConfig", routeName: "税率配置-删除" },
    { api: prefix + "/fin/tax/updateTaxRateConfigEnabled", routeName: "税率配置-启用/停用" },
    { api: prefix + "/fin/tax/taxRateConfigInfo", routeName: "税率配置-税率配置详情" },
    //基础数据-通用数据-费用项
    { api: prefix + "/fin/feeitem/pageList", routeName: "费用项-列表" },
    { api: prefix + "/fin/feeitem/save", routeName: "费用项-费用项保存" },
    { api: prefix + "/fin/feeitem/update", routeName: "费用项-修改" },
    { api: prefix + "/fin/feeitem/feeItemInfo", routeName: "费用项-详情查询" },
    { api: prefix + "/fin/feeitem/updateEnabled", routeName: "费用项-启用/禁用" },
    //基础数据-海运基础信息-专项管理费用
    { api: prefix + "/fin/feeitem/specialLimitRolePageList", routeName: "专项管理费-列表" },
    { api: prefix + "/fin/feeitem/updateSpecialLimitRole", routeName: "专项管理费-角色限制修改" },
    { api: prefix + "/fin/feeitem/deleteSpecialLimitRole", routeName: "专项管理费-角色限制删除" },
    { api: prefix + "/fin/feeitem/updateSpecialLimitRoleEnabled", routeName: "专项管理费-角色限制启用/禁用" },
    { api: prefix + "/fin/feeitem/saveSpecialLimitRole", routeName: "专项管理费-角色限制新增" },
];