module.exports = (prams) => {
    return {
        "code": 0,
        "data": [
            {
                "cname":"澳新线",
                "createdBy":0,
                "createdTime":null,
                "ename":"",
                "lineId":0,
                "remark":"",
                "sort":0,
                "state":"",
                "sysLineCode":"AXX",
                "updatedBy":0,
                "updatedTime":null
            },
            {
                "cname":"加拿大线",
                "createdBy":0,
                "createdTime":null,
                "ename":"",
                "lineId":0,
                "remark":"",
                "sort":0,
                "state":"",
                "sysLineCode":"100074994",
                "updatedBy":0,
                "updatedTime":null
            },
            {
                "cname":"加勒比线",
                "createdBy":0,
                "createdTime":null,
                "ename":"",
                "lineId":0,
                "remark":"",
                "sort":0,
                "state":"",
                "sysLineCode":"100074995",
                "updatedBy":0,
                "updatedTime":null
            },
            {
                "cname":"中美线",
                "createdBy":0,
                "createdTime":null,
                "ename":"",
                "lineId":0,
                "remark":"",
                "sort":0,
                "state":"",
                "sysLineCode":"100074996",
                "updatedBy":0,
                "updatedTime":null
            },
            {
                "cname":"美东线",
                "createdBy":0,
                "createdTime":null,
                "ename":"",
                "lineId":0,
                "remark":"",
                "sort":0,
                "state":"",
                "sysLineCode":"100074997",
                "updatedBy":0,
                "updatedTime":null
            }
        ],
        "msg": "success"
    }
};