module.exports = (prams) => {
  return {
    "code":0,
    "msg":"success",
    "data":{
        "pageNum":1,
        "totalPage":100,
        "pageSize":100,
        "allColumns": [
            "polEname",
            "endDate",
            "transitPort3Ename",
            "feederMatchMode",
            "publishDate",
            "allin",
            "sailingDate",
            "bkgAgent",
            "effectiveType",
            "transitPort2Ename",
            "freeTimeDesc",
            "shipCarrierCode",
            "priceGp20",
            "podCode",
            "state",
            "podCountryName",
            "externalDesc",
            "carrierService",
            "surchargeList",
            "blankSailing",
            "polCname",
            "recommendLevel",
            "voyage",
            "pricerName",
            "guidanceDesc",
            "feederRouteId",
            "sysLineCode",
            "weightDesc",
            "transitPort3Cname",
            "publisher",
            "transitPort1Ename",
            "shipTerms",
            "transitPort1Cname",
            "sameFlagCode",
            "feederPolCname",
            "podCityName",
            "priceGp40",
            "cargoLimited",
            "podEname",
            "routeId",
            "pricerDeptCode",
            "surchargeDesc",
            "internalDesc",
            "pricer",
            "transitVoyage",
            "polCityName",
            "feederPolEname",
            "feederPolCode",
            "priceHq40",
            "cutoffDate",
            "polCode",
            "blType",
            "beginDate",
            "schedule",
            "issueWay",
            "transitPort2Cname",
            "priceHq45",
            "podCname",
            "attention",
            "subRouteList",
            "carrierLineName"
        ],
        "configColumns": [
            "priceGp20",
            "priceGp40",
            "priceHq40",
            "priceHq45",
            "attention",
            "effectiveType",
            "schedule",
            "transitPortEname",
            "beginDate",
            "polCode",
            "polEname",
            "polCname",
            'podCode',
            'podEname',
            'podCname',
            'currency',
            'priceGp20',
            'currency',
            'priceGp40',
            'weightCurrency',
            'weightPriceGp40',
            'weightCurrency',
            'weightPriceGp20',
            "state",
            "externalDesc",
            "carrierService",
            "surchargeList",
            "shipCarrierCode",
            "issueWay"
        ],
        "list":[
            {
                "routeId":1,
                "routeCode":"xxxx",
                "polCode":"SHEKOU",
                "polCname":"SHEKOU",
                "polEname":"",
                "polCityCode":"",
                "polCityCname":"",
                "podCode":"xxx",
                "podCname":"KOLKATA",
                "podEname":"CALCUTTA",
                "podCityCode":"",
                "podCityCname":"",
                "mainPolCode":"",
                "mainPolCname":"大船汽运港",
                "mainPolEname":"",
                "mainPolCityCode":"",
                "mainPolCityCname":"",
                "transitPort1Code":"",
                "transitPort1Cname":"KRISHNAPHATNAM(KATTUPALLI)",
                "transitPort1Ename":"",
                "transitPort1CityCode":"",
                "transitPort1CityCname":"",
                "transitPort2Code":"",
                "transitPort2Cname":"",
                "transitPort2Ename":"",
                "transitPort2CityCode":"",
                "transitPort2CityCname":"",
                "transitPort3Code":"",
                "transitPort3Cname":"",
                "transitPort3Ename":"",
                "transitPort3CityCode":"",
                "transitPort3CityCname":"",
                "feederMatchMode":"auto",
                "isExclusive":"Y",
                "bkgAgent":"xxx",
                "transitVoyage":"10",
                "sysLineCode":"",
                "sysLineCname":"",
                "carrierLineName":"澳新线",
                "carrierService":"Mapple",
                "shipCarrierCode": "PO",
                "shipCarrierCname": "海南泛洋",
                "cargoLimited":"不能送灯泡类",
                "validFrom":"2020-08-18",
                "validTo":"2020-09-18",
                "beginDate":"2020-08-18",
                "endDate":"2020-09-18",
                "effectiveType":"sailing_day",
                "sailingDate":"2020-08-20",
                "cutoffDate":"2020-08-19",
                "schedule":"5/1",
                "voyage":"30",
                "shipTerms":"test",
                "issueWay":"SWB",
                "billType":"M/H",
                "attention":"注意注意",
                "isRecommend":"Y",
                "allin":"Y",
                "surchargeDesc":"附加费说明",
                "weightDesc":"限重说明",
                "guidance":"收获指引",
                "internalRemark":"内部备注",
                "freeTime":"暂无",
                "pricer":"max",
                "pricerOffice":"深圳硕沃",
                "currency": "USD",
                "list":[
                    {
                        "routeId":12,
                        "routeCode":"xxxx",
                        "polCode":"SHEKOU",
                        "polCname":"SHEKOU123",
                        "polEname":"",
                        "polCityCode":"",
                        "polCityCname":"",
                        "podCode":"fds",
                        "podCname":"CALCUTTA(KOLKATA)",
                        "podEname":"",
                        "podCityCode":"",
                        "podCityCname":"",
                        "mainPolCode":"",
                        "mainPolCname":"大船汽运港",
                        "mainPolEname":"",
                        "mainPolCityCode":"",
                        "mainPolCityCname":"",
                        "transitPort1Code":"",
                        "transitPort1Cname":"KRISHNAPHATNAM(KATTUPALLI)",
                        "transitPort1Ename":"",
                        "transitPort1CityCode":"",
                        "transitPort1CityCname":"",
                        "transitPort2Code":"",
                        "transitPort2Cname":"",
                        "transitPort2Ename":"",
                        "transitPort2CityCode":"",
                        "transitPort2CityCname":"",
                        "transitPort3Code":"",
                        "transitPort3Cname":"",
                        "transitPort3Ename":"",
                        "transitPort3CityCode":"",
                        "transitPort3CityCname":"",
                        "feederMatchMode":"auto",
                        "isExclusive":"Y",
                        "bkgAgent":"xxx",
                        "transitVoyage":"10",
                        "sysLineCode":"",
                        "sysLineCname":"",
                        "carrierLineName":"澳新线",
                        "carrierService":"Mapple",
                        "shipCarrierCode": "HMM",
                        "shipCarrierCname": "HMM",
                        "cargoLimited":"不能送灯泡类",
                        "validFrom":"2020-08-18",
                        "validTo":"2020-09-18",
                        "beginDate":"2020-08-18",
                        "endDate":"2020-09-18",
                        "effectiveType":"entry_time",
                        "sailingDate":"2020-08-20",
                        "cutoffDate":"2020-08-19",
                        "schedule":"5/1",
                        "voyage":"30",
                        "shipTerms":"test",
                        "issueWay":"SWB",
                        "billType":"M/H",
                        "attention":"注意注意",
                        "isRecommend":"Y",
                        "allin":"Y",
                        "surchargeDesc":"附加费说明",
                        "weightDesc":"限重说明",
                        "guidance":"收获指引",
                        "internalRemark":"内部备注",
                        "freeTime":"暂无",
                        "pricer":"max",
                        "pricerOffice":"深圳硕沃",
                    }
                ],
                "oceanFreight":[],
                "surchargeList": [
                    {
                        "chargeCode": "DOC",
                        "chargeName": "文件费",
                        "chargeMode": "basePrice",
                        "chargeType": "起运港LOCAL",
                        "createdBy": 0,
                        "createdTime": null,
                        "currency": "USD",
                        "oid": 3,
                        "payMode": "预付",
                        "price": 52.3,
                        "priceGp20": '',
                        "priceGp40": '',
                        "priceHq40": '',
                        "priceHq45": '',
                        "rateUnit": "箱",
                        "state": "valid",
                        "templateId": 2,
                        "updatedBy": 0,
                        "updatedTime": null
                    },
                    {
                        "chargeCode": "SEAL",
                        "chargeName": "封条费",
                        "chargeMode": "basePrice",
                        "chargeType": "目的港LOCAL",
                        "createdBy": 0,
                        "createdTime": null,
                        "currency": "USD",
                        "oid": 3,
                        "payMode": "到付",
                        "price": 52.3,
                        "priceGp20": 45,
                        "priceGp40": 45,
                        "priceHq40": 45,
                        "priceHq45": 45,
                        "rateUnit": "箱型",
                        "state": "valid",
                        "templateId": 2,
                        "updatedBy": 0,
                        "updatedTime": null
                    },
                    {
                        "chargeCode": "GKABF",
                        "chargeName": "港口安保费",
                        "chargeMode": "basePrice",
                        "chargeType": "运费附加费",
                        "createdBy": 0,
                        "createdTime": null,
                        "currency": "ASP",
                        "oid": 4,
                        "payMode": "无限制",
                        "price": 521.3,
                        "priceGp20": 121.2,
                        "priceGp40": 43,
                        "priceHq40": 23,
                        "priceHq45": 43,
                        "rateUnit": "票",
                        "state": "valid",
                        "templateId": 2,
                        "updatedBy": 0,
                        "updatedTime": null
                    }
                ],
                "priceGp20": '12',
                "priceGp40": '13',
                "priceHq40": '23',
                "priceHq45": '54',
                "weightPriceGp20": '1',
                "weightPriceGp40": '11',
                "weightPriceHq40": '111',
                "weightPriceHq45": '11',
                "portList": [
                    {
                        "cityCname": "深圳",
                        "cityCode": "",
                        "cityEname": "",
                        "cname": "盐田",
                        "countryName": "",
                        "ename": "YANTIAN",
                        "parentCname": "",
                        "parentEname": "",
                        "portAttribute": "",
                        "portCode": "CNYTN",
                        "portType": "",
                        "routeId": 1,
                        "sysLineCode": ""
                    },
                    {
                        "cityCname": "深圳",
                        "cityCode": "",
                        "cityEname": "",
                        "cname": "大铲湾",
                        "countryName": "",
                        "ename": "DA CHAN BAY",
                        "parentCname": "",
                        "parentEname": "",
                        "portAttribute": "",
                        "portCode": "CNDCW",
                        "portType": "",
                        "routeId": 1,
                        "sysLineCode": ""
                    }
                ],
            },
            {
                "routeId":2,
                "routeCode":"xxxx",
                "polCode":"",
                "polCname":"SHEKOU",
                "polEname":"",
                "polCityCode":"",
                "polCityCname":"",
                "podCode":"yyy",
                "podCname":"CALCUTTA(KOLKATA)",
                "podEname":"",
                "podCityCode":"",
                "podCityCname":"",
                "mainPolCode":"",
                "mainPolCname":"",
                "mainPolEname":"",
                "mainPolCityCode":"",
                "mainPolCityCname":"",
                "transitPort1Code":"",
                "transitPort1Cname":"",
                "transitPort1Ename":"",
                "transitPort1CityCode":"",
                "transitPort1CityCname":"",
                "transitPort2Code":"",
                "transitPort2Cname":"",
                "transitPort2Ename":"",
                "transitPort2CityCode":"",
                "transitPort2CityCname":"",
                "transitPort3Code":"",
                "transitPort3Cname":"",
                "transitPort3Ename":"",
                "transitPort3CityCode":"",
                "transitPort3CityCname":"",
                "feederMatchMode":"auto",
                "isExclusive":"Y",
                "bkgAgent":"xxx",
                "transitVoyage":"10",
                "sysLineCode":"",
                "sysLineCname":"",
                "carrierLineName":"澳新线",
                "carrierService":"Mapple",
                "shipCarrierCode":"ANL",
                "shipCarrierCname":"澳洲国家航运澳航",
                "cargoLimited":"不能送灯泡类",
                "validFrom":"2020-08-18",
                "validTo":"2020-09-18",
                "effectiveType":"cutoff_time",
                "sailingDate":"2020-08-20",
                "cutoffDate":"2020-08-19",
                "schedule":"5/1",
                "voyage":"30",
                "shipTerms":"test",
                "issueWay":"SWB",
                "billType":"M/H",
                "attention":"注意注意",
                "isRecommend":"N",
                "allin":"Y",
                "surchargeDesc":"附加费说明",
                "weightDesc":"限重说明",
                "guidance":"收获指引",
                "internalRemark":"内部备注",
                "freeTime":"暂无",
                "pricer":"max",
                "pricerOffice":"深圳硕沃",
                "list":[],
                "currency": "USD",
                "oceanFreight":[],
                "surchargeList":[],
                "beginDate": "2020-08-16",
                "endDate":"2020-09-18",
                "portList": [
                    {
                        "cityCname": "深圳",
                        "cityCode": "",
                        "cityEname": "",
                        "cname": "盐田2",
                        "countryName": "",
                        "ename": "YANTIAN2",    
                        "parentCname": "",
                        "parentEname": "",
                        "portAttribute": "",
                        "portCode": "CNYTN2",
                        "portType": "",
                        "routeId": 1,
                        "sysLineCode": ""
                    }
                ],
            },
            {
                "routeId":3,
                "routeCode":"xxxx",
                "polCode":"",
                "polCname":"",
                "polEname":"",
                "polCityCode":"",
                "polCityCname":"",
                "podCode":"",
                "podCname":"",
                "podEname":"",
                "podCityCode":"",
                "podCityCname":"",
                "mainPolCode":"",
                "mainPolCname":"",
                "mainPolEname":"",
                "mainPolCityCode":"",
                "mainPolCityCname":"",
                "transitPort1Code":"",
                "transitPort1Cname":"",
                "transitPort1Ename":"",
                "transitPort1CityCode":"",
                "transitPort1CityCname":"",
                "transitPort2Code":"",
                "transitPort2Cname":"",
                "transitPort2Ename":"",
                "transitPort2CityCode":"",
                "transitPort2CityCname":"",
                "transitPort3Code":"",
                "transitPort3Cname":"",
                "transitPort3Ename":"",
                "transitPort3CityCode":"",
                "transitPort3CityCname":"",
                "feederMatchMode":"auto",
                "isExclusive":"Y",
                "bkgAgent":"xxx",
                "transitVoyage":"10",
                "sysLineCode":"",
                "sysLineCname":"",
                "carrierLineName":"澳新线",
                "carrierService":"Mapple",
                "shipCarrierCode":"",
                "shipCarrierCname":"",
                "cargoLimited":"不能送灯泡类",
                "validFrom":"2020-08-18",
                "validTo":"2020-09-18",
                "effectiveType":"cutoff_time",
                "sailingDate":"2020-08-20",
                "cutoffDate":"2020-08-19",
                "schedule":"5/1",
                "voyage":"30",
                "shipTerms":"test",
                "issueWay":"SWB",
                "billType":"M/H",
                "attention":"注意注意注意注意注意注意注意注意注意注意注意注意注意注意",
                "isRecommend":"N",
                "allin":"Y",
                "surchargeDesc":"附加费说明",
                "weightDesc":"限重说明",
                "guidance":"收获指引",
                "internalRemark":"内部备注",
                "freeTime":"暂无",
                "pricer":"max",
                "pricerOffice":"深圳硕沃",
                "oceanFreight":[],
                "surchargeList":[],
                "priceGp20": 1,
                "priceGp40": 2,
                "priceHq40": 3,
                "priceHq45": 4,
                "currency": "USD",
                "beginDate": "2020-08-17",
                "endDate":"2020-09-17",
                "portList": [
                    
                ],
            }
        ]
    }
}
};
