module.exports = (params) => {
    return {
        "code": 0,
        "data": {
            "auditStatus": "",
            "baseFile": null,
            "companyFeeInfo": { 
              "gedgingSettleFeeList": [
                    {
                        "canGedgingAmt": 30.00,
                        "currency": "USD",
                        "exGedgingAmt": 0,
                        "exNoWriteoffAmt": 0,
                        "feeCode": "truck001",
                        "feeId": 78,
                        "feeName": "拖车费",
                        "finGroup": "incomecost", 
                        "finLockStatus": "unlock", 
                        "gedgingAmt": 20.00, 
                        "gedgingCurrency": "USD", 
                        "gedgingRate": 0, 
                        "noWriteoffAmt": 10.00, 
                        "receipayType": "receive", 
                        "settleAmt": 30.00, 
                        "settleCompCode": "000001", 
                        "settleCompName": "深圳分公司", 
                        "settleCorpCode": "code111", 
                        "settleCorpName": "测试客户1", 
                        "settleExRate": 1.0000000000, 
                        "settleLock": "unlock", 
                        "settleOrderFeeId": 238, 
                        "settleOrderId": 72, 
                        "settleOrderNo": "Settle20201204195641000011", 
                        "sourceBizNo": "S202009230000553", 
                        "sourceType": "order", 
                        "tempReceipayType": "", 
                        "writeoffAmt": 0.00 
                    }, 
                    { 
                        "canGedgingAmt": 20.00, 
                        "currency": "USD", 
                        "exGedgingAmt": 0, 
                        "exNoWriteoffAmt": 0,
                        "feeCode": "truck001", 
                        "feeId": 81, 
                        "feeName": "拖车费", 
                        "finGroup": "incomecost", 
                        "finLockStatus": "unlock", 
                        "gedgingAmt": 20.00, 
                        "gedgingCurrency": "USD", 
                        "gedgingRate": 0, 
                        "noWriteoffAmt": 0.00, 
                        "receipayType": "pay", 
                        "settleAmt": 20.00, 
                        "settleCompCode": "000001", 
                        "settleCompName": "深圳分公司", 
                        "settleCorpCode": "code111", 
                        "settleCorpName": "测试客户1", 
                        "settleExRate": 1.0000000000, 
                        "settleLock": "unlock", 
                        "settleOrderFeeId": 239, 
                        "settleOrderId": 72, 
                        "settleOrderNo": "Settle20201204195641000011", 
                        "sourceBizNo": "S202009230000553", 
                        "sourceType": "order", 
                        "tempReceipayType": "", 
                        "writeoffAmt": 0.00 
                    }, 
                    { 
                        "canGedgingAmt": 60.00, 
                        "currency": "CNY", 
                        "exGedgingAmt": 0, 
                        "exNoWriteoffAmt": 0, 
                        "feeCode": "truck001", 
                        "feeId": 82, 
                        "feeName": "拖车费", 
                        "finGroup": "incomecost", 
                        "finLockStatus": "unlock", 
                        "gedgingAmt": 60.00, 
                        "gedgingCurrency": "USD", 
                        "gedgingRate": 0, 
                        "noWriteoffAmt": 0.00, 
                        "receipayType": "pay", 
                        "settleAmt": 60.00, 
                        "settleCompCode": "000001", 
                        "settleCompName": "深圳分公司",
                        "settleCorpCode": "code111", 
                        "settleCorpName": "测试客户1", 
                        "settleExRate": 0.1550000000, 
                        "settleLock": "unlock", 
                        "settleOrderFeeId": 240, 
                        "settleOrderId": 72, 
                        "settleOrderNo": "Settle20201204195641000011", 
                        "sourceBizNo": "S202009230000553", 
                        "sourceType": "order", 
                        "tempReceipayType": "", 
                        "writeoffAmt": 0.00 
                    }
                ], 
                "settleCompCode": "000001", 
                "settleCompName": "长帆深圳分公司", 
                "sumList": [
                    { 
                        "createdBy": 0, 
                        "createdName": "", 
                        "createdTime": null, 
                        "currency": "USD", 
                        "gedgingAmt": 0, 
                        "gedgingApplyId": 0, 
                        "oid": 0, 
                        "payNegativeAmt": 0, 
                        "payPositiveAmt": 20.00, 
                        "recvNegativeAmt": 0, 
                        "recvPositiveAmt": 20.00, 
                        "settleCompCode": "", 
                        "updatedBy": 0, 
                        "updatedName": "", 
                        "updatedTime": null 
                    }, 
                    { 
                        "createdBy": 0, 
                        "createdName": "", 
                        "createdTime": null, 
                        "currency": "CNY", 
                        "gedgingAmt": 0, 
                        "gedgingApplyId": 0, 
                        "oid": 0, 
                        "payNegativeAmt": 0, 
                        "payPositiveAmt": 60.00, 
                        "recvNegativeAmt": 0, 
                        "recvPositiveAmt": 0, 
                        "settleCompCode": "", 
                        "updatedBy": 0, 
                        "updatedName": "", 
                        "updatedTime": null 
                    }
                ] 
            }, 
            "confirmFileName": "", 
            "confirmFileNo": "", 
            "exchangeRateList": [], 
            "gedgingApplyNo": "", 
            "gedgingCurrency": "", 
            "gedgingType": "company_gedging", 
            "rivalCorpCode": "000010", 
            "rivalCorpName": "美国分公司", 
            "settleCompCode": "000001", 
            "settleCompName": "长帆深圳分公司", 
            "settleUnitFeeInfo": { 
                "gedgingSettleFeeList": [
                    { 
                        "canGedgingAmt": -500.00, 
                        "currency": "CNY", 
                        "exGedgingAmt": 0, 
                        "exNoWriteoffAmt": 0, 
                        "feeCode": "truck001", 
                        "feeId": 288, 
                        "feeName": "拖车费", 
                        "finGroup": "incomecost", 
                        "finLockStatus": "unlock", 
                        "gedgingAmt": -60.00, 
                        "gedgingCurrency": "CNY", 
                        "gedgingRate": 0, 
                        "noWriteoffAmt": -440.00, 
                        "receipayType": "pay", 
                        "settleAmt": 100.00, 
                        "settleCompCode": "000010", 
                        "settleCompName": "美国分公司", 
                        "settleCorpCode": "code111", 
                        "settleCorpName": "测试客户1", 
                        "settleExRate": 1.0000000000, 
                        "settleLock": "unlock", 
                        "settleOrderFeeId": 153, 
                        "settleOrderId": 49, 
                        "settleOrderNo": "Settle2020110500007", 
                        "sourceBizNo": "S202009230000553", 
                        "sourceType": "order", 
                        "tempReceipayType": "", 
                        "writeoffAmt": 600.00 
                    }, 
                    { 
                        "canGedgingAmt": -500.00, 
                        "currency": "CNY", 
                        "exGedgingAmt": 0, 
                        "exNoWriteoffAmt": 0, 
                        "feeCode": "truck001", 
                        "feeId": 289, 
                        "feeName": "拖车费", 
                        "finGroup": "incomecost", 
                        "finLockStatus": "unlock", 
                        "gedgingAmt": 0.00, 
                        "gedgingCurrency": "CNY", 
                        "gedgingRate": 0, 
                        "noWriteoffAmt": -500.00, 
                        "receipayType": "pay", 
                        "settleAmt": 100.00, 
                        "settleCompCode": "000010", 
                        "settleCompName": "美国分公司", 
                        "settleCorpCode": "code111", 
                        "settleCorpName": "测试客户1", 
                        "settleExRate": 1.0000000000, 
                        "settleLock": "unlock", 
                        "settleOrderFeeId": 154, 
                        "settleOrderId": 49, 
                        "settleOrderNo": "Settle2020110500007", 
                        "sourceBizNo": "S202009230000553", 
                        "sourceType": "order", 
                        "tempReceipayType": "", 
                        "writeoffAmt": 600.00 
                    }, 
                    { 
                        "canGedgingAmt": -100.00, 
                        "currency": "CNY", 
                        "exGedgingAmt": 0, 
                        "exNoWriteoffAmt": 0, 
                        "feeCode": "NBWLUSA", 
                        "feeId": 292, 
                        "feeName": "内部往来(美国)", 
                        "finGroup": "intrabranch", 
                        "finLockStatus": "unlock", 
                        "gedgingAmt": 0.00, 
                        "gedgingCurrency": "CNY", 
                        "gedgingRate": 0, 
                        "noWriteoffAmt": -100.00, 
                        "receipayType": "pay", 
                        "settleAmt": 100.00, 
                        "settleCompCode": "000010", 
                        "settleCompName": "美国分公司", 
                        "settleCorpCode": "code111", 
                        "settleCorpName": "测试客户1", 
                        "settleExRate": 1.0000000000, 
                        "settleLock": "unlock", 
                        "settleOrderFeeId": 157, 
                        "settleOrderId": 49, 
                        "settleOrderNo": "Settle2020110500007", 
                        "sourceBizNo": "2020110500000043",
                        "sourceType": "fin_order", 
                        "tempReceipayType": "", 
                        "writeoffAmt": 200.00 
                    }, 
                    { 
                        "canGedgingAmt": -100.00, 
                        "currency": "CNY", 
                        "exGedgingAmt": 0, 
                        "exNoWriteoffAmt": 0, 
                        "feeCode": "NBWLUSA", 
                        "feeId": 293, 
                        "feeName": "内部往来(美国)", 
                        "finGroup": "intrabranch", 
                        "finLockStatus": "unlock", 
                        "gedgingAmt": 0.00, 
                        "gedgingCurrency": "CNY", 
                        "gedgingRate": 0, 
                        "noWriteoffAmt": -100.00, 
                        "receipayType": "pay", 
                        "settleAmt": 100.00, 
                        "settleCompCode": "000010", 
                        "settleCompName": "美国分公司", 
                        "settleCorpCode": "code111", 
                        "settleCorpName": "测试客户1", 
                        "settleExRate": 1.0000000000, 
                        "settleLock": "unlock", 
                        "settleOrderFeeId": 158, 
                        "settleOrderId": 49, 
                        "settleOrderNo": "Settle2020110500007", 
                        "sourceBizNo": "2020110500000043", 
                        "sourceType": "fin_order", 
                        "tempReceipayType": "", 
                        "writeoffAmt": 200.00 
                    }
                ], 
                "settleCompCode": "000010", 
                "settleCompName": "美国分公司", 
                "sumList": [
                    { 
                        "createdBy": 0, 
                        "createdName": "", 
                        "createdTime": null, 
                        "currency": "CNY", 
                        "gedgingAmt": 0, 
                        "gedgingApplyId": 0, 
                        "oid": 0, 
                        "payNegativeAmt": -60.00, 
                        "payPositiveAmt": 0.00, 
                        "recvNegativeAmt": 0, 
                        "recvPositiveAmt": 0, 
                        "settleCompCode": "", 
                        "updatedBy": 0, 
                        "updatedName": "", 
                        "updatedTime": null 
                    }
                ] 
            }
        },
        "msg": "success"
    }
}