module.exports = (params) => {
  return {
    "code": 0,
    "data": {
        "auditStatus": "",
        "baseFile": null,
        "companyFeeInfo": {
            "gedgingSettleFeeList": [
                {
                    "canGedgingAmt": 6.00,
                    "currency": "USD",
                    "exGedgingAmt": 40.2000,
                    "exNoWriteoffAmt": 0.0000,
                    "feeCode": "FKC",
                    "feeId": 525,
                    "feeName": "叉车费",
                    "finGroup": "incomecost",
                    "finLockStatus": "unlock",
                    "gedgingAmt": 6.00,
                    "gedgingCurrency": "USD",
                    "gedgingRate": 0,
                    "noWriteoffAmt": 0.00,
                    "receipayType": "receive",
                    "settleAmt": 6.00,
                    "settleCompCode": "000001",
                    "settleCompName": "深圳分公司",
                    "settleCorpCode": "000001",
                    "settleCorpName": "长帆深圳分公司",
                    "settleExRate": 6.7,
                    "settleLock": "lock",
                    "settleOrderFeeId": 269,
                    "settleOrderId": 90,
                    "settleOrderNo": "Settle20201215121637000054",
                    "sourceBizNo": "S202012010000953",
                    "sourceType": "order",
                    "tempReceipayType": "",
                    "writeoffAmt": 0.00
                },
                {
                    "canGedgingAmt": 1.00,
                    "currency": "USD",
                    "exGedgingAmt": 6.7000,
                    "exNoWriteoffAmt": 0.0000,
                    "feeCode": "GUIJIANFEI",
                    "feeId": 526,
                    "feeName": "柜检费",
                    "finGroup": "incomecost",
                    "finLockStatus": "unlock",
                    "gedgingAmt": 1.00,
                    "gedgingCurrency": "USD",
                    "gedgingRate": 0,
                    "noWriteoffAmt": 0.00,
                    "receipayType": "receive",
                    "settleAmt": 1.00,
                    "settleCompCode": "000001",
                    "settleCompName": "深圳分公司",
                    "settleCorpCode": "000001",
                    "settleCorpName": "长帆深圳分公司",
                    "settleExRate": 6.7,
                    "settleLock": "lock",
                    "settleOrderFeeId": 270,
                    "settleOrderId": 90,
                    "settleOrderNo": "Settle20201215121637000054",
                    "sourceBizNo": "S202012010000953",
                    "sourceType": "order",
                    "tempReceipayType": "",
                    "writeoffAmt": 0.00
                },
                {
                    "canGedgingAmt": 5.00,
                    "currency": "USD",
                    "exGedgingAmt": 33.5000,
                    "exNoWriteoffAmt": 0.0000,
                    "feeCode": "XZF",
                    "feeId": 527,
                    "feeName": "熏蒸费",
                    "finGroup": "incomecost",
                    "finLockStatus": "unlock",
                    "gedgingAmt": 5.00,
                    "gedgingCurrency": "USD",
                    "gedgingRate": 0,
                    "noWriteoffAmt": 0.00,
                    "receipayType": "receive",
                    "settleAmt": 5.00,
                    "settleCompCode": "000001",
                    "settleCompName": "深圳分公司",
                    "settleCorpCode": "000001",
                    "settleCorpName": "长帆深圳分公司",
                    "settleExRate": 6.7,
                    "settleLock": "lock",
                    "settleOrderFeeId": 271,
                    "settleOrderId": 90,
                    "settleOrderNo": "Settle20201215121637000054",
                    "sourceBizNo": "S202012010000953",
                    "sourceType": "order",
                    "tempReceipayType": "",
                    "writeoffAmt": 0.00
                },
                {
                    "canGedgingAmt": 670.00,
                    "currency": "CNY",
                    "exGedgingAmt": 80.4000,
                    "exNoWriteoffAmt": 589.6000,
                    "feeCode": "YINHANGNK",
                    "feeId": 528,
                    "feeName": "银行内扣手续费",
                    "finGroup": "commonfee",
                    "finLockStatus": "unlock",
                    "gedgingAmt": 80.40,
                    "gedgingCurrency": "CNY",
                    "gedgingRate": 0,
                    "noWriteoffAmt": 589.60,
                    "receipayType": "pay",
                    "settleAmt": 670.00,
                    "settleCompCode": "000001",
                    "settleCompName": "深圳分公司",
                    "settleCorpCode": "000001",
                    "settleCorpName": "长帆深圳分公司",
                    "settleExRate": 1,
                    "settleLock": "lock",
                    "settleOrderFeeId": 272,
                    "settleOrderId": 90,
                    "settleOrderNo": "Settle20201215121637000054",
                    "sourceBizNo": "S202012010000953",
                    "sourceType": "order",
                    "tempReceipayType": "",
                    "writeoffAmt": 0.00
                }
            ],
            "settleCompCode": "000001",
            "settleCompName": "深圳分公司",
            "sumList": [
                {
                    "createdBy": 0,
                    "createdName": "",
                    "createdTime": null,
                    "currency": "USD",
                    "gedgingAmt": 0,
                    "gedgingApplyId": 0,
                    "oid": 0,
                    "payNegativeAmt": 0,
                    "payPositiveAmt": 0,
                    "recvNegativeAmt": 0,
                    "recvPositiveAmt": 12.00,
                    "settleCompCode": "",
                    "updatedBy": 0,
                    "updatedName": "",
                    "updatedTime": null
                },
                {
                    "createdBy": 0,
                    "createdName": "",
                    "createdTime": null,
                    "currency": "CNY",
                    "gedgingAmt": 0,
                    "gedgingApplyId": 0,
                    "oid": 0,
                    "payNegativeAmt": 0,
                    "payPositiveAmt": 80.40,
                    "recvNegativeAmt": 0,
                    "recvPositiveAmt": 0,
                    "settleCompCode": "",
                    "updatedBy": 0,
                    "updatedName": "",
                    "updatedTime": null
                }
            ]
        },
        "confirmFileName": "",
        "confirmFileNo": "",
        "exchangeRateList": [
            {
                "bocRate": 0,
                "createdBy": 0,
                "createdName": "",
                "createdTime": null,
                "effectDate": null,
                "exchangeRateId": 0,
                "exchangeRateTaskId": 0,
                "expireDate": null,
                "lowerRate": 0,
                "presetStatus": "",
                "rate": 6.7,
                "revision": 0,
                "srcCurrency": "USD",
                "state": "",
                "toCurrency": "CNY",
                "type": "",
                "updatedBy": 0,
                "updatedName": "",
                "updatedTime": null,
                "upperRate": 0,
                "yearMon": ""
            }
        ],
        "gedgingApplyNo": "",
        "gedgingCurrency": "CNY",
        "gedgingType": "client_gedging",
        "rivalCorpCode": "000001",
        "rivalCorpName": "长帆深圳分公司",
        "settleCompCode": "000001",
        "settleCompName": "深圳分公司",
        "settleUnitFeeInfo": null
    },
    "msg": "success"
  }
}