module.exports = (params) => {
  return {
    "code": 0,
    "data": {
        "auditStatus": "pending_audit",
        "baseFile": null,
        "companyFeeInfo": {
            "gedgingSettleFeeList": [
                {
                    "canGedgingAmt": 120,
                    "currency": "CNY",
                    "exGedgingAmt": 0,
                    "exNoWriteoffAmt": 0,
                    "feeCode": "truck001",
                    "feeId": 92,
                    "feeName": "拖车费",
                    "finLockStatus": "lock",
                    "gedgingAmt": 120,
                    "gedgingCurrency": "CNY",
                    "gedgingRate": 1,
                    "noWriteoffAmt": 0,
                    "receipayType": "receive",
                    "settleAmt": 120,
                    "settleCompCode": "000010",
                    "settleCompName": "美国分公司",
                    "settleCorpCode": "000001",
                    "settleCorpName": "深圳分公司",
                    "settleExRate": 0,
                    "settleLock": "lock",
                    "settleOrderFeeId": 0,
                    "settleOrderId": 27,
                    "settleOrderNo": "Settle2020101022005",
                    "sourceBizNo": "S202009230000553",
                    "sourceType": "order",
                    "tempReceipayType": "",
                    "writeoffAmt": 0
                },
                {
                    "canGedgingAmt": 130,
                    "currency": "CNY",
                    "exGedgingAmt": 0,
                    "exNoWriteoffAmt": 0,
                    "feeCode": "truck001",
                    "feeId": 93,
                    "feeName": "拖车费",
                    "finLockStatus": "lock",
                    "gedgingAmt": 130,
                    "gedgingCurrency": "CNY",
                    "gedgingRate": 1,
                    "noWriteoffAmt": 0,
                    "receipayType": "pay",
                    "settleAmt": 130,
                    "settleCompCode": "000010",
                    "settleCompName": "美国分公司",
                    "settleCorpCode": "000001",
                    "settleCorpName": "深圳分公司",
                    "settleExRate": 0,
                    "settleLock": "lock",
                    "settleOrderFeeId": 0,
                    "settleOrderId": 27,
                    "settleOrderNo": "Settle2020101022005",
                    "sourceBizNo": "S202009230000553",
                    "sourceType": "order",
                    "tempReceipayType": "",
                    "writeoffAmt": 0
                },
                {
                    "canGedgingAmt": 140,
                    "currency": "USD",
                    "exGedgingAmt": 0,
                    "exNoWriteoffAmt": 0,
                    "feeCode": "truck001",
                    "feeId": 94,
                    "feeName": "拖车费",
                    "finLockStatus": "lock",
                    "gedgingAmt": 140,
                    "gedgingCurrency": "USD",
                    "gedgingRate": 1,
                    "noWriteoffAmt": 0,
                    "receipayType": "receive",
                    "settleAmt": 140,
                    "settleCompCode": "000010",
                    "settleCompName": "美国分公司",
                    "settleCorpCode": "000001",
                    "settleCorpName": "深圳分公司",
                    "settleExRate": 0,
                    "settleLock": "lock",
                    "settleOrderFeeId": 0,
                    "settleOrderId": 27,
                    "settleOrderNo": "Settle2020101022005",
                    "sourceBizNo": "S202009230000553",
                    "sourceType": "order",
                    "tempReceipayType": "",
                    "writeoffAmt": 0
                }
            ],
            "settleCompCode": "000010",
            "settleCompName": "美国分公司",
            "sumList": [
                {
                    "createdBy": 4,
                    "createdName": "赵斌",
                    "createdTime": "2020-10-28 08:06:42",
                    "currency": "USD",
                    "gedgingAmt": 0,
                    "gedgingApplyId": 51,
                    "oid": 53,
                    "payNegativeAmt": 0,
                    "payPositiveAmt": 0,
                    "recvNegativeAmt": 0,
                    "recvPositiveAmt": 140,
                    "settleCompCode": "000010",
                    "updatedBy": 0,
                    "updatedName": "",
                    "updatedTime": null
                },
                {
                    "createdBy": 4,
                    "createdName": "赵斌",
                    "createdTime": "2020-10-28 08:06:42",
                    "currency": "CNY",
                    "gedgingAmt": 0,
                    "gedgingApplyId": 51,
                    "oid": 54,
                    "payNegativeAmt": 0,
                    "payPositiveAmt": 130,
                    "recvNegativeAmt": 0,
                    "recvPositiveAmt": 120,
                    "settleCompCode": "000010",
                    "updatedBy": 0,
                    "updatedName": "",
                    "updatedTime": null
                }
            ]
        },
        "confirmFileNo": "",
        "exchangeRateList":[{
            "srcCurrency":"USD",
            "toCurrency":"CNY",
            "rate":"6.7"
        }],
        "gedgingApplyNo": "GED2020102800000003",
        "gedgingCurrency": "CNY",
        "gedgingType": "client_gedging",
        "rivalCorpCode": "000001",
        "rivalCorpName": "深圳分公司",
        "settleCompCode": "000010",
        "settleCompName": "美国分公司",
        "settleUnitFeeInfo": {
            "gedgingSettleFeeList": [
                {
                    "canGedgingAmt": 0,
                    "currency": "CNY",
                    "exGedgingAmt": 0,
                    "exNoWriteoffAmt": 0,
                    "feeCode": "truck001",
                    "feeId": 92,
                    "feeName": "拖车费",
                    "finLockStatus": "lock",
                    "gedgingAmt": 120,
                    "gedgingCurrency": "CNY",
                    "gedgingRate": 1,
                    "noWriteoffAmt": 0,
                    "receipayType": "receive",
                    "settleAmt": 0,
                    "settleCompCode": "000010",
                    "settleCompName": "美国分公司",
                    "settleCorpCode": "000001",
                    "settleCorpName": "深圳分公司",
                    "settleExRate": 0,
                    "settleLock": "lock",
                    "settleOrderFeeId": 0,
                    "settleOrderId": 27,
                    "settleOrderNo": "Settle2020101022005",
                    "sourceBizNo": "S202009230000553",
                    "sourceType": "order",
                    "tempReceipayType": "",
                    "writeoffAmt": 0
                },
                {
                    "canGedgingAmt": 0,
                    "currency": "CNY",
                    "exGedgingAmt": 0,
                    "exNoWriteoffAmt": 0,
                    "feeCode": "truck001",
                    "feeId": 93,
                    "feeName": "拖车费",
                    "finLockStatus": "lock",
                    "gedgingAmt": 130,
                    "gedgingCurrency": "CNY",
                    "gedgingRate": 1,
                    "noWriteoffAmt": 0,
                    "receipayType": "pay",
                    "settleAmt": 0,
                    "settleCompCode": "000010",
                    "settleCompName": "美国分公司",
                    "settleCorpCode": "000001",
                    "settleCorpName": "深圳分公司",
                    "settleExRate": 0,
                    "settleLock": "lock",
                    "settleOrderFeeId": 0,
                    "settleOrderId": 27,
                    "settleOrderNo": "Settle2020101022005",
                    "sourceBizNo": "S202009230000553",
                    "sourceType": "order",
                    "tempReceipayType": "",
                    "writeoffAmt": 0
                },
                {
                    "canGedgingAmt": 0,
                    "currency": "USD",
                    "exGedgingAmt": 0,
                    "exNoWriteoffAmt": 0,
                    "feeCode": "truck001",
                    "feeId": 94,
                    "feeName": "拖车费",
                    "finLockStatus": "lock",
                    "gedgingAmt": 140,
                    "gedgingCurrency": "USD",
                    "gedgingRate": 1,
                    "noWriteoffAmt": 0,
                    "receipayType": "receive",
                    "settleAmt": 0,
                    "settleCompCode": "000010",
                    "settleCompName": "美国分公司",
                    "settleCorpCode": "000001",
                    "settleCorpName": "深圳分公司",
                    "settleExRate": 0,
                    "settleLock": "lock",
                    "settleOrderFeeId": 0,
                    "settleOrderId": 27,
                    "settleOrderNo": "Settle2020101022005",
                    "sourceBizNo": "S202009230000553",
                    "sourceType": "order",
                    "tempReceipayType": "",
                    "writeoffAmt": 0
                }
            ],
            "settleCompCode": "000001",
            "settleCompName": "深圳分公司",
            "sumList": [
                {
                    "createdBy": 4,
                    "createdName": "赵斌",
                    "createdTime": "2020-10-28 08:06:42",
                    "currency": "USD",
                    "gedgingAmt": 0,
                    "gedgingApplyId": 50,
                    "oid": 51,
                    "payNegativeAmt": 0,
                    "payPositiveAmt": 0,
                    "recvNegativeAmt": 0,
                    "recvPositiveAmt": 140,
                    "settleCompCode": "000001",
                    "updatedBy": 0,
                    "updatedName": "",
                    "updatedTime": null
                },
                {
                    "createdBy": 4,
                    "createdName": "赵斌",
                    "createdTime": "2020-10-28 08:06:42",
                    "currency": "CNY",
                    "gedgingAmt": 0,
                    "gedgingApplyId": 50,
                    "oid": 52,
                    "payNegativeAmt": 0,
                    "payPositiveAmt": 110,
                    "recvNegativeAmt": 0,
                    "recvPositiveAmt": 100,
                    "settleCompCode": "000001",
                    "updatedBy": 0,
                    "updatedName": "",
                    "updatedTime": null
                }
            ]
        }
    },
    "msg": "success"
  }
}