module.exports = (params) => {
    return {
        "code": 0,
        "data": {
            "allColumns": [],
            "configColumns": [],
            "currPage": 1,
            "list": [
                {
                    "applyAmt": 23000.00,
                    "balanceAmt": 23000.00,
                    "bankSeqNo": "",
                    "bankseqFileNo": "",
                    "confirmName": "",
                    "confirmStatus": "no",
                    "confirmTime": null,
                    "createdName": "业务【勿动】",
                    "createdTime": "2020-10-13 06:59:49",
                    "currency": "CNY",
                    "errorStatus": "no",
                    "hasInvoice": "",
                    "interTransferFee": 0.00,
                    "isMerge": "no",
                    "lessPayAmt": 0.00,
                    "lessPayDealway": "",
                    "orderType": "prepay",
                    "payCompCode": "000001",
                    "payCompName": "深圳分公司",
                    "payOrderNo": "PAY20201013709000006",
                    "paySettleApplyNo": "",
                    "payWay": "prepay",
                    "payWriteoffStatus": "no",
                    "prepayApplyNo": "PREPAY20201012000005",
                    "realPayAmt": 23000.00,
                    "remark": "",
                    "sourceApplyNo": "PREPAY20201012000005",
                    "sourceType": "prepay",
                    "state": "",
                    "toPayOrderId": 0,
                    "transferFeeAmt": 0.00,
                    "writeoffAmt": 0.00,
                    "transferFeeList":[
                        {
                            "transferFeeId":12,
                            "amt":100,
                            "currency":"CNY",
                            "cutType":"inter_cut"
                        }
                    ],
                    "payInfo": {
                        "applyPayAmt": 23000.00,
                        "currency": "CNY",
                        "invoiceNo": "",
                        "payAccountNo": "3728648324",
                        "payBankCode": "BOC",
                        "payBankName": "建设银行",
                        "payCompCode": "000001",
                        "payCompName": "深圳分公司",
                        "payInfoId": 4,
                        "payWay": "prepay",
                        "recvAccountName": "北京北京",
                        "recvAccountNo": "600023232",
                        "recvBankCode": "ABC",
                        "recvBankName": "农业银行",
                        "recvCorpCode": "GYS98773232",
                        "recvCorpName": "上海平安付",
                        "settleOrderNo": ""
                    }
                },
                {
                    "applyAmt": 24000.00,
                    "balanceAmt": 24000.00,
                    "bankSeqNo": "",
                    "bankseqFileNo": "",
                    "confirmName": "",
                    "confirmStatus": "no",
                    "confirmTime": null,
                    "createdName": "业务【勿动】",
                    "createdTime": "2020-10-14 06:59:49",
                    "currency": "CNY",
                    "errorStatus": "no",
                    "hasInvoice": "",
                    "interTransferFee": 0.00,
                    "isMerge": "no",
                    "lessPayAmt": 0.00,
                    "lessPayDealway": "",
                    "orderType": "prepay",
                    "payCompCode": "000002",
                    "payCompName": "深圳分公司",
                    "payOrderNo": "PAY20201013709000007",
                    "paySettleApplyNo": "1",
                    "payWay": "prepay",
                    "payWriteoffStatus": "no",
                    "prepayApplyNo": "PREPAY20201012000006",
                    "realPayAmt": 24000.00,
                    "remark": "",
                    "sourceApplyNo": "PREPAY20201012000006",
                    "sourceType": "prepay",
                    "state": "",
                    "toPayOrderId": 0,
                    "transferFeeAmt": 0.00,
                    "writeoffAmt": 0.00,
                    "payInfo": {
                        "applyPayAmt": 24000.00,
                        "currency": "CNY",
                        "invoiceNo": "",
                        "payAccountNo": "3728648325",
                        "payBankCode": "BOC",
                        "payBankName": "建设银行",
                        "payCompCode": "000002",
                        "payCompName": "深圳分公司",
                        "payInfoId": 5,
                        "payWay": "prepay",
                        "recvAccountName": "北京北京",
                        "recvAccountNo": "600023232",
                        "recvBankCode": "ABC",
                        "recvBankName": "农业银行",
                        "recvCorpCode": "GYS98773232",
                        "recvCorpName": "上海平安付",
                        "settleOrderNo": ""
                    }
                }
            ],
            "pageSize": 10,
            "totalCount": 5,
            "totalPage": 1
        },
        "msg": "success"
    }
}