module.exports = (prams) => {
    return {
        "code": 0,
        "data": [
            {
                "batchNo": "1",
                "createdBy": 16,
                "createdName": "业务【勿动】",
                "createdTime": "2020-11-18 15:00:14",
                "custContact": "張三",
                "custContactPhone": "13888888888",
                "custName": "测试公司1",
                "custid": 1,
                "inRemark": "沒什麼",
                "oid": 1,
                "orderNo": "BS2020110700289",
                "planEnterTime": "2020-12-01 22:00:00",
                "planNo": "1231231232",
                "positionNo": "1001",
                "revision": 0,
                "state": "valid",
                "status": "init",
                "updatedBy": 16,
                "updatedName": "业务【勿动】",
                "updatedTime": "2020-11-18 15:06:56",
                "whId": 1,
                "whName": "测试必须的",
                "quantity": 111,
                "weight": 222,
                "volume": 333,
                "packageType": 'bag',
                "remark": '放大佛挡杀佛的顺丰到付'
            },
            {
                "batchNo": "2",
                "createdBy": 16,
                "createdName": "业务【勿动】",
                "createdTime": "2020-11-18 15:00:14",
                "custContact": "xx",
                "custContactPhone": "13888888123",
                "custName": "测试22公司2",
                "custid": 1,
                "inRemark": "沒什麼2",
                "oid": 1,
                "orderNo": "BS2020110700289",
                "planEnterTime": "2020-12-11 22:00:00",
                "planNo": "43432",
                "positionNo": "1001",
                "revision": 0,
                "state": "valid",
                "status": "init",
                "updatedBy": 16,
                "updatedName": "业务【勿动】",
                "updatedTime": "2020-11-18 15:06:56",
                "whId": 1,
                "whName": "测试仓库",
                "quantity": 11,
                "weight": 111,
                "volume": 222,
                "packageType": 'box',
                "remark": 'test'
            }
        ],
        "msg": "success"
    }
}