module.exports = (prams) => {
    return {
        "code": 0,
        "data": [
            {
                "createdBy": 16,
                "createdName": "业务【勿动】",
                "createdTime": "2020-11-18 19:38:46",
                "custContact": "張三",
                "custContactPhone": "13888888888",
                "custName": "测试公司1",
                "custid": 1,
                "oid": 2,
                "orderNo": "BKG2020110700289",
                "outBatchNo": "2222",
                "outPlanNo": "3333333",
                "outPlanTime": "2020-10-11 00:00:00",
                "remark": "沒什麼",
                "revision": 0,
                "state": "valid",
                "status": "init",
                "updatedBy": 16,
                "updatedName": "业务【勿动】",
                "updatedTime": "2020-11-18 19:39:15",
                "whId": 1,
                "whName": "测试必须的",
                "quantity": 11,
                "weight": 111,
                "volume": 222,
                "packageType": 'box',
                "remark": 'test'
            },
            {
                "createdBy": 17,
                "createdName": "业务【勿动】",
                "createdTime": "2020-11-18 19:38:46",
                "custContact": "張三2",
                "custContactPhone": "13888888882",
                "custName": "测试公司2",
                "custid": 2,
                "oid": 3,
                "orderNo": "BKG2020110700290",
                "outBatchNo": "11111",
                "outPlanNo": "33333332",
                "outPlanTime": "2020-09-11 00:00:00",
                "remark": "沒什麼2",
                "revision": 0,
                "state": "valid",
                "status": "init",
                "updatedBy": 16,
                "updatedName": "业务【勿动】",
                "updatedTime": "2020-11-18 19:39:15",
                "whId": 2,
                "whName": "测试必须的2",
                "quantity": 12,
                "weight": 1121,
                "volume": 2223,
                "packageType": 'box',
                "remark": 'test2'
            }
        ],
        "msg": "success"
    }
}