module.exports = (prams) => {
  return {
    "code":0,
    "msg":"success",
    "data":{
      "applyStatus": "",
      blId: 340,
      "blCargos": [
        {
          "blNo": "M001",
          "cn": "c001",
          "containerType": "40GP",
          "createdBy": 5,
          "createdName": "june",
          "createdTime": "2020-09-06T09:57:09",
          "oid": 1,
          "orderNo": "hello_003",
          "packageType": "bag",
          "quantity": 10,
          "sn": "s001",
          "so": "so001",
          "updatedBy": 5,
          "updatedName": "june",
          "updatedTime": "2020-09-06T09:57:14",
          "volume": 10,
          "weight": 10
        }
      ],
      "blContact": {
        "blNo": "M001",
        "consignee": "1",
        "createdBy": 5,
        "createdName": "june",
        "createdTime": "2020-09-06T09:59:59",
        "notify1": "june1",
        "notify2": "june2",
        "notify3": "june3",
        "oid": 1,
        "orderNo": "hello_003",
        "shipper": "1",
        "updatedBy": 5,
        "updatedName": "june",
        "updatedTime": "2020-09-06T10:00:02"
      },
      "blMode": "original",
      "blNo": "M001",
      "blType": "mbl",
      "cargoDesc": "裤子",
      "cargoMark": "裤子",
      "children": [],
      "copyCount": 3,
      "createdBy": 5,
      "createdName": "june",
      "createdTime": "2020-09-06T09:53:45",
      "issueTime": "2020-09-02T14:30:13",
      "masterBlNo": "",
      "oid": 2,
      "orderNo": "hello_003",
      "originalCount": 3,
      "parentBlNo": "",
      "postStatus": "",
      "releaseStatus": "",
      "remark": "出m单",
      "remarkPrint": "",
      "retrieveStatus": "",
      "signAddress": "深圳蛇口",
      "signEmployeeId": 5,
      "signTime": "2020-09-02T14:30:21",
      "status": "finish",
      "updatedBy": 5,
      "updatedName": "june",
      "updatedTime": "2020-09-06T09:53:48",
      "orderInfo":{
        "bargeVessel": "驳船船名",
        "bargeVoyage":"驳船航次",
        "bargePorPortCode":"ESCAR",
        "vessel":"大船船名",
        "voyage":"大船航次",
        "polPortCode":"PYTER",
        "transitPortCode":"ESCAR,PYTER",
        "podPortCode":"REEW",
        "shipCarrierCode":"ANL",
        "siCutOff":"2020-09-06 14:30:21",
        "deliveryPlace":"目的地",
        "etaTime": "2020-09-06 14:30:21",
        "tdTime": "2020-07-07 11:22:22",
        "payMode":"付款方式",
        "transportTerm":"运输条款",
        "contractNo":"合约号",
        "contractSupplierId":"合约公司ID",
        "contractSupplierName":"合约公司名称",
      }
    }
  }
};
