module.exports = (prams) => {
    return {
        "code":0,
        "msg":"success",
        "data":[
            {
                "applyStatus": "finish",
                "blCargos": [],
                "blContact": null,
                "blMode": "original",
                "blNo": "M001",
                "blType": "master",
                "cargoDesc": "裤子",
                "cargoMark": "裤子",
                "copyCount": 3,
                "createdBy": 5,
                "createdName": "june",
                "createdTime": "2020-09-06T09:53:45",
                "issueTime": "2020-09-02T14:30:13",
                "masterBlNo": "",
                "oid": 2,
                "orderNo": "hello_003",
                "originalCount": 3,
                "parentBlNo": "",
                "postStatus": "finish",
                "releaseStatus": "finish",
                "remark": "出m单",
                "remarkPrint": "",
                "retrieveStatus": "finish",
                "signAddress": "深圳蛇口",
                "signEmployeeId": 5,
                "signTime": "2020-09-02T14:30:21",
                "status": "finish",
                "updatedBy": 5,
                "updatedName": "june",
                "updatedTime": "2020-09-06T09:53:48"
            },
            {
                "applyStatus": "finish",
                "blCargos": [],
                "blContact": null,
                "blMode": "original",
                "blNo": "H001",
                "blType": "house",
                "cargoDesc": "裤子",
                "cargoMark": "裤子",
                "copyCount": 3,
                "createdBy": 5,
                "createdName": "june",
                "createdTime": "2020-09-06T09:53:45",
                "issueTime": "2020-09-02T14:30:13",
                "masterBlNo": "",
                "oid": 20,
                "orderNo": "hello_003",
                "originalCount": 3,
                "parentBlNo": "",
                "postStatus": "finish",
                "releaseStatus": "finish",
                "remark": "出m单",
                "remarkPrint": "",
                "retrieveStatus": "finish",
                "signAddress": "深圳蛇口",
                "signEmployeeId": 5,
                "signTime": "2020-09-02T14:30:21",
                "status": "finish",
                "updatedBy": 5,
                "updatedName": "june",
                "updatedTime": "2020-09-06T09:53:48"
            },
            {
                "applyStatus": "finish",
                "blCargos": [],
                "blContact": null,
                "blMode": "original",
                "blNo": "H003",
                "blType": "house",
                "cargoDesc": "裤子3",
                "cargoMark": "裤子3",
                "children": [],
                "copyCount": 3,
                "createdBy": 5,
                "createdName": "june",
                "createdTime": "2020-09-06T09:53:45",
                "issueTime": "2020-09-02T14:30:13",
                "masterBlNo": "",
                "oid": 21,
                "orderNo": "hello_003",
                "originalCount": 3,
                "parentBlNo": "",
                "postStatus": "finish",
                "releaseStatus": "finish",
                "remark": "出m单3",
                "remarkPrint": "",
                "retrieveStatus": "finish",
                "signAddress": "深圳蛇口3",
                "signEmployeeId": 5,
                "signTime": "2020-09-02T14:30:21",
                "status": "finish",
                "updatedBy": 5,
                "updatedName": "june",
                "updatedTime": "2020-09-06T09:53:48"
            },
            {
                "applyStatus": "finish",
                "blCargos": [],
                "blContact": null,
                "blMode": "original",
                "blNo": "M006",
                "blType": "master",
                "cargoDesc": "裤子4",
                "cargoMark": "裤子4",
                "children": [],
                "copyCount": 3,
                "createdBy": 5,
                "createdName": "june",
                "createdTime": "2020-09-06T09:53:45",
                "issueTime": "2020-09-02T14:30:13",
                "masterBlNo": "",
                "oid": 22,
                "orderNo": "hello_004",
                "originalCount": 3,
                "parentBlNo": "",
                "postStatus": "finish",
                "releaseStatus": "finish",
                "remark": "出m单3",
                "remarkPrint": "",
                "retrieveStatus": "finish",
                "signAddress": "深圳蛇口3",
                "signEmployeeId": 5,
                "signTime": "2020-09-02T14:30:21",
                "status": "finish",
                "updatedBy": 5,
                "updatedName": "june",
                "updatedTime": "2020-09-06T09:53:48"
            }
        ]
    }
};
