module.exports = (params) => {
    return {
        "code": 0,
        "data": [
            {
                "afterWriteoff": "no",
                "currency": "CNY",
                "invoicePaymentId": 1,
                "payInfoId": 22,
                "invoicePayment": {
                    "amt": 20000.00,
                    "copyType": "paper",
                    "currency": "CNY",
                    "fileId": 1,
                    "invoiceIssueDate": "2020-09-09",
                    "invoiceNo": "123456",
                    "invoicePaymentId": 1,
                    "invoiceType": "special",
                    "lockAmt": 10500.00,
                    "receiveBy": 0,
                    "receiveName": "",
                    "receiveNo": "",
                    "receiveState": "no",
                    "receiveTime": null,
                    "remark": "备注",
                    "settleCompCode": "1",
                    "settleCompName": "长帆国际物流",
                    "supplierBank": "中国银行",
                    "supplierBankNo": "12345465",
                    "supplierCorpCode": "com000001",
                    "supplierCorpName": "供应商名称",
                    "supplierTaxpayerNo": "",
                    "taxNo": "纳税人识别号",
                    "taxRate": 0.03,
                    "title": "发票抬头",
                    "writeoffAmt": 0,
                    "createdName": "",
                    "createdTime": "2020-12-12 08:47:20"
                }
            },
            {
                "afterWriteoff": "no",
                "currency": "CNY",
                "invoicePaymentId": 2,
                "payInfoId": 23,
                "invoicePayment": {
                    "amt": 20000.00,
                    "copyType": "paper",
                    "currency": "CNY",
                    "fileId": 2,
                    "invoiceIssueDate": "2020-09-09",
                    "invoiceNo": "123456",
                    "invoicePaymentId": 2,
                    "invoiceType": "special",
                    "lockAmt": 10500.00,
                    "receiveBy": 0,
                    "receiveName": "",
                    "receiveNo": "",
                    "receiveState": "no",
                    "receiveTime": null,
                    "remark": "备注",
                    "settleCompCode": "2",
                    "settleCompName": "长帆国际物流",
                    "supplierBank": "中国银行",
                    "supplierBankNo": "12345467",
                    "supplierCorpCode": "com000001",
                    "supplierCorpName": "供应商名称",
                    "supplierTaxpayerNo": "",
                    "taxNo": "纳税人识别号",
                    "taxRate": 0.03,
                    "title": "发票抬头",
                    "writeoffAmt": 0,
                    "createdName": "",
                    "createdTime": "2020-12-11 08:47:20"
                },
            }
        ],
        "msg": "success"
    }
}