module.exports = (prams) => {
    return {
        "code": 0,
        "data": {
            "currPage": 2,
            "list": [
                {
                    "createdBy": "admin",
                    "createdTime": "2020-07-16 22:30:39",
                    "remark": "",
                    "state": "",
                    "surchargeList": [
                        {
                            "chargeName": "文件费",
                            "chargeCode": "THC",
                            "chargeMode": "basePrice",
                            "chargeType": "起运港LOCAL",
                            "createdBy": 0,
                            "createdTime": null,
                            "currency": "USD",
                            "oid": 9,
                            "payMode": "预付",
                            "price": 52.3,
                            "priceGp20": 12.2,
                            "priceGp40": 32.2,
                            "priceHq40": 42.2,
                            "priceHq45": 52.2,
                            "rateUnit": "箱",
                            "state": "valid",
                            "templateId": 5,
                            "updatedBy": 0,
                            "updatedTime": null
                        },
                        {
                            "chargeName": "文件费1",
                            "chargeCode": "THC",
                            "chargeMode": "basePrice",
                            "chargeType": "起运港LOCAL",
                            "createdBy": 0,
                            "createdTime": null,
                            "currency": "USD",
                            "oid": 9,
                            "payMode": "预付",
                            "price": 52.3,
                            "priceGp20": 12.2,
                            "priceGp40": 32.2,
                            "priceHq40": 42.2,
                            "priceHq45": 52.2,
                            "rateUnit": "箱型",
                            "state": "valid",
                            "templateId": 5,
                            "updatedBy": 0,
                            "updatedTime": null
                        },
                        {   
                            "chargeName": "文件费2",
                            "chargeCode": "THC",
                            "chargeMode": "basePrice",
                            "chargeType": "起运港LOCAL",
                            "createdBy": 0,
                            "createdTime": null,
                            "currency": "USD",
                            "oid": 10,
                            "payMode": "预付",
                            "price": 521.3,
                            "priceGp20": 121.2,
                            "priceGp40": 321.2,
                            "priceHq40": 421.2,
                            "priceHq45": 521.2,
                            "rateUnit": "箱",
                            "state": "valid",
                            "templateId": 5,
                            "updatedBy": 0,
                            "updatedTime": null
                        }
                    ],
                    "templateId": 3,
                    "templateName": "ANL-澳新线1",
                    "userId": 0
                },
                {
                    "createdBy": "admin",
                    "createdTime": "2020-07-16 22:30:39",
                    "remark": "",
                    "state": "",
                    "surchargeList": [
                        {   
                            "chargeName": "文件费",
                            "chargeCode": "THC",
                            "chargeMode": "basePrice",
                            "chargeType": "起运港LOCAL",
                            "createdBy": 0,
                            "createdTime": null,
                            "currency": "USD",
                            "oid": 9,
                            "payMode": "预付",
                            "price": 52.3,
                            "priceGp20": 12.2,
                            "priceGp40": 32.2,
                            "priceHq40": 42.2,
                            "priceHq45": 52.2,
                            "rateUnit": "箱",
                            "state": "valid",
                            "templateId": 5,
                            "updatedBy": 0,
                            "updatedTime": null
                        },
                        {
                            "chargeName": "文件费1",
                            "chargeCode": "THC",
                            "chargeMode": "basePrice",
                            "chargeType": "起运港LOCAL",
                            "createdBy": 0,
                            "createdTime": null,
                            "currency": "USD",
                            "oid": 9,
                            "payMode": "预付",
                            "price": 52.3,
                            "priceGp20": 12.2,
                            "priceGp40": 32.2,
                            "priceHq40": 42.2,
                            "priceHq45": 52.2,
                            "rateUnit": "箱型",
                            "state": "valid",
                            "templateId": 5,
                            "updatedBy": 0,
                            "updatedTime": null
                        },
                        {
                            "chargeName": "文件费2",
                            "chargeCode": "THC",
                            "chargeMode": "basePrice",
                            "chargeType": "起运港LOCAL",
                            "createdBy": 0,
                            "createdTime": null,
                            "currency": "USD",
                            "oid": 10,
                            "payMode": "预付",
                            "price": 521.3,
                            "priceGp20": 121.2,
                            "priceGp40": 321.2,
                            "priceHq40": 421.2,
                            "priceHq45": 521.2,
                            "rateUnit": "箱",
                            "state": "valid",
                            "templateId": 5,
                            "updatedBy": 0,
                            "updatedTime": null
                        }
                    ],
                    "templateId": 4,
                    "templateName": "ANL-澳新线1",
                    "userId": 4
                }
            ],
            "pageSize": 1,
            "totalCount": 2,
            "totalPage": 2
        },
        "msg": "success"
    }
};
