module.exports = (params) => {
    return {
        "code": 0,
        "data": {
            "allColumns": [],
            "configColumns": [],
            "currPage": 1,
            "list": [
                {
                    "accountNo": "749757960768",
                    "bankSeqNo": "1234567",
                    "batchNo": "",
                    "confirmBy": 0,
                    "confirmName": "",
                    "confirmStatus": "unconfirm",
                    "confirmTime": null,
                    "corpPrerevAccountId": 0,
                    "currency": "USD",
                    "fromReceivableRegId": "3",
                    "interTransferFee": 0.00,
                    "lessPayAmt": 0.00,
                    "oldSettleCorpCode": "V000000001",
                    "oldSettleCorpName": "长帆开票测试2",
                    "payAccountNo": "1234567",
                    "payBankName": "",
                    "payCorpCode": "V000000001",
                    "payCorpName": "长帆开票测试2",
                    "realAmt": 2000.00,
                    "reason": "转登原因",
                    "receivableRegNo": "2020101500000004",
                    "receivableRegTransferId": 1,
                    "recvCompCode": "000001",
                    "recvCompName": "深圳分公司",
                    "recvDate": "2020-10-10",
                    "settleCorpCode": "cus000001",
                    "settleCorpName": "长帆开票测试",
                    "toReceivableRegId": "4",
                    "totalAmt": 2000.00,
                    "transferFeeAmt": 0.00,
                    "type": "customer_pay"
                },
                {
                    "accountNo": "749757960769",
                    "bankSeqNo": "1234566",
                    "batchNo": "",
                    "confirmBy": 0,
                    "confirmName": "",
                    "confirmStatus": "unconfirm",
                    "confirmTime": null,
                    "corpPrerevAccountId": 1,
                    "currency": "USD",
                    "fromReceivableRegId": "3",
                    "interTransferFee": 0.00,
                    "lessPayAmt": 0.00,
                    "oldSettleCorpCode": "V000000002",
                    "oldSettleCorpName": "长帆开票测试3",
                    "payAccountNo": "1234567",
                    "payBankName": "",
                    "payCorpCode": "V000000001",
                    "payCorpName": "长帆开票测试3",
                    "realAmt": 2000.00,
                    "reason": "转登原因",
                    "receivableRegNo": "2020101500000004",
                    "receivableRegTransferId": 2,
                    "recvCompCode": "000002",
                    "recvCompName": "深圳分公司",
                    "recvDate": "2021-01-10",
                    "settleCorpCode": "cus000001",
                    "settleCorpName": "长帆开票测试",
                    "toReceivableRegId": "4",
                    "totalAmt": 3000.00,
                    "transferFeeAmt": 0.00,
                    "type": "customer_pay"
                }
            ],
            "pageSize": 5,
            "totalCount": 1,
            "totalPage": 1
        },
        "msg": "success"
    }
}