module.exports = (params) => {
  return {
    "code": 0,
    "data": {
        "amt": 1000.00,
        "copyType": "paper",
        "createdBy": 10,
        "createdName": "",
        "createdTime": "2020-09-11T08:47:20",
        "currency": "CNY",
        "fileId": 1,
        "invoiceIssueDate": "2020-09-09",
        "invoiceNo": "123456",
        "invoicePaymentId": 1,
        "invoicePaymentIds": [],
        "invoiceType": "special",
        "lockAmt": 0,
        "payInfoIds": [],
        "receiveBy": 0,
        "receiveName": "",
        "receiveNo": "",
        "receiveState": "no",
        "receiveTime": null,
        "remark": "备注",
        "settleCompCode": "1",
        "settleCompName": "长帆国际物流",
        "state": "valid",
        "supplierBank": "中国银行",
        "supplierBankNo": "12345465",
        "supplierCorpCode": "供应商编码",
        "supplierCorpName": "供应商名称",
        "supplierTaxpayerNo": "",
        "taxNo": "纳税人识别号",
        "taxRate": 0.03,
        "title": "发票抬头",
        "updatedBy": 0,
        "updatedName": "",
        "updatedTime": null,
        "writeoffAmt": 0
    },
    "msg": "success"
  }
}