module.exports = (prams) => {
    return {
        "code":0,
        "msg":"success",
        "data":{
            "cocBlVos": [
                {
                    "blId": 1,
                    "blNo": "9002",
                    "fileNum": 2,
                    "cocCnVos": [
                        {
                            "cn": "1",
                            "containerId": 1,
                            "cocBoxVos": [
                                {
                                    "blId": 1,
                                    "containerId": 346,
                                    "createdBy": 0,
                                    "createdName": "",
                                    "createdTime": null,
                                    "currency": "CNY",
                                    "intrustNo": "AII2020110700001",
                                    "mark": "长虹视1",
                                    "name": "视机1",
                                    "oid": 11,
                                    "orderNo": "S202009300000571",
                                    "packageType": "box",
                                    "quantity": 123,
                                    "revision": 2,
                                    "state": "valid",
                                    "totalPrice": 94279.5,
                                    "unitPrice": 766.5,
                                    "updatedBy": 20,
                                    "updatedName": "操作【勿动】",
                                    "updatedTime": "2020-11-19 15:10:22",
                                    "volume": 41,
                                    "weight": 1501
                                },
                                {
                                    "containerId": 346,
                                    "createdBy": 0,
                                    "createdName": "",
                                    "createdTime": null,
                                    "currency": "CNY",
                                    "intrustNo": "AII2020110700001",
                                    "mark": "电视2",
                                    "name": "电机2",
                                    "oid": 12,
                                    "orderNo": "S202009300000571",
                                    "packageType": "bag",
                                    "quantity": 120,
                                    "revision": 2,
                                    "state": "valid",
                                    "totalPrice": 95000,
                                    "unitPrice": 766.5,
                                    "updatedBy": 20,
                                    "updatedName": "操作【勿动】",
                                    "updatedTime": "2020-11-19 15:10:22",
                                    "volume": 31,
                                    "weight": 1301
                                }
                            ],
                        },
                        {
                            "cn": "2",
                            "containerId": 2,
                            "cocBoxVos": [
                                {
                                    "blId": 1,
                                    "containerId": 2,
                                    "createdBy": 0,
                                    "createdName": "",
                                    "createdTime": null,
                                    "currency": "CNY",
                                    "intrustNo": "AII2020110700001",
                                    "mark": "长虹视1",
                                    "name": "视机1",
                                    "oid": 11,
                                    "orderNo": "S202009300000571",
                                    "packageType": "box",
                                    "quantity": 123,
                                    "revision": 2,
                                    "state": "valid",
                                    "totalPrice": 94279.5,
                                    "unitPrice": 766.5,
                                    "updatedBy": 20,
                                    "updatedName": "操作【勿动】",
                                    "updatedTime": "2020-11-19 15:10:22",
                                    "volume": 41,
                                    "weight": 1501
                                }
                            ],
                        }
                    ],
                },
                {
                    "blId": 2,
                    "blNo": "9003",
                    "fileNum": 2,
                    "cocCnVos": [
                        {
                            "cn": "2",
                            "containerId": 2,
                            "cocBoxVos": [
                                {
                                    "blId": 1,
                                    "containerId": 346,
                                    "createdBy": 0,
                                    "createdName": "",
                                    "createdTime": null,
                                    "currency": "CNY",
                                    "intrustNo": "AII2020110700001",
                                    "mark": "长虹视1",
                                    "name": "视机1",
                                    "oid": 11,
                                    "orderNo": "S202009300000571",
                                    "packageType": "box",
                                    "quantity": 123,
                                    "revision": 2,
                                    "state": "valid",
                                    "totalPrice": 94279.5,
                                    "unitPrice": 766.5,
                                    "updatedBy": 20,
                                    "updatedName": "操作【勿动】",
                                    "updatedTime": "2020-11-19 15:10:22",
                                    "volume": 41,
                                    "weight": 1501
                                },
                                {
                                    "containerId": 346,
                                    "createdBy": 0,
                                    "createdName": "",
                                    "createdTime": null,
                                    "currency": "CNY",
                                    "intrustNo": "AII2020110700001",
                                    "mark": "电视2",
                                    "name": "电机2",
                                    "oid": 12,
                                    "orderNo": "S202009300000571",
                                    "packageType": "bag",
                                    "quantity": 120,
                                    "revision": 2,
                                    "state": "valid",
                                    "totalPrice": 95000,
                                    "unitPrice": 766.5,
                                    "updatedBy": 20,
                                    "updatedName": "操作【勿动】",
                                    "updatedTime": "2020-11-19 15:10:22",
                                    "volume": 31,
                                    "weight": 1301
                                }
                            ],
                        }
                    ],
                }
            ],
            "checkContact": "22",
            "checkContactPhone": "2222",
            "checkSupplierId": 123,
            "checkSupplierName": "321",
            "checkType": "coc",
            "countryCode": "",
            "countryName": "墨西哥",
            "createdBy": 20,
            "createdName": "操作【勿动】",
            "createdTime": "2020-11-20 10:05:31",
            "declareContact": "小胖子",
            "declareContactPhone": "13458888888",
            "declareCustName": "长江一号",
            "declareCustid": 1,
            "examineGoodsTime": "2020-11-16 10:04:19",
            "intrustNo": "AII2020110700001",
            "oid": 7,
            "orderNo": "S202009300000571",
            "remark": "2323",
            "revision": 1,
            "state": "valid",
            "status": "init",
            "updatedBy": 0,
            "updatedName": "",
            "updatedTime": null
        }
    }
};
