module.exports = (params) => {
    return {
        "code": 0,
        "data": {
            "applyNo": "PYSETT20201015000004",
            "confirmName": "业务【勿动】",
            "confirmStatus": "approved",
            "confirmTime": "2020-10-15 03:45:03",
            "createdName": "业务【勿动】",
            "createdTime": "2020-10-15 02:51:44",
            "earliestDate": "2020-10-15",
            "latestDate": "2020-10-18",
            "applyPayAmountSumByCurrency": "HKD800.0 USD600.0 CNY5000.0 ",
            "currency": "CNY,USD,HKD",
            "recvCorpName": "远东货轮",
            "settleOrderNo": "123132,342313",
            "usablePrepayment":"USD100 CNY10000",
            "payInfoList": [
                {
                    "applyPayAmt": 5000.00,
                    "currency": "CNY",
                    "invoiceNo": "",
                    "payAccountNo": "663728648324",
                    "payBankCode": "BOC",
                    "payBankName": "建设银行",
                    "payCompCode": "000001",
                    "payCompName": "长帆",
                    "payInfoId": 10,
                    "payWay": "cash",
                    "recvAccountName": "南京分局",
                    "recvAccountNo": "62600023232",
                    "recvBankCode": "ABC",
                    "recvBankName": "农业银行",
                    "recvCorpCode": "GYS98773232",
                    "recvCorpName": "远东货轮",
                    "settleOrderNo": "123132",
                },
                {
                    "applyPayAmt": 600.00,
                    "currency": "USD",
                    "invoiceNo": "",
                    "payAccountNo": "233728648324",
                    "payBankCode": "BOC",
                    "payBankName": "汇丰银行",
                    "payCompCode": "000001",
                    "payCompName": "长帆",
                    "payInfoId": 11,
                    "payWay": "cash",
                    "recvAccountName": "南京分局",
                    "recvAccountNo": "10600023232",
                    "recvBankCode": "",
                    "recvBankName": "东亚银行",
                    "recvCorpCode": "GYS98773232",
                    "recvCorpName": "远东货轮",
                    "revision": 0,
                    "settleOrderNo": "123132"
                },
                {
                    "applyPayAmt": 800.00,
                    "currency": "HKD",
                    "invoiceNo": "",
                    "payAccountNo": "233728648324",
                    "payBankCode": "BOC",
                    "payBankName": "平安银行",
                    "payCompCode": "000001",
                    "payCompName": "长帆",
                    "payInfoId": 12,
                    "payWay": "cash",
                    "recvAccountName": "南京分局",
                    "recvAccountNo": "10600023232",
                    "recvBankCode": "",
                    "recvBankName": "渣打银行",
                    "recvCorpCode": "GYS98773232",
                    "recvCorpName": "远东货轮",
                    "settleOrderNo": "342313"
                }
            ],
            "refuseReason": "",
            "remark": "USD：2020 CNY:320",
            "settleCompCode": "000001",
            "settleCompName": "长帆",
        },
        "msg": "success"
    }
}