module.exports = (params) => {
    return {
        "code": 0,
        "data": {
            "accountNo": "744557928354",
            "acountShortName": "",
            "bankSeqNo": "123456",
            "bankseqFileStatus": "",
            "bankseqFileCode": "",
            "bankseqFileName": "ddls.jpg",
            "bankseqFilePath": "/path/ddls.jpg",
            "proxyFileCode": "",
            "proxyFileName": "slsl.jpg",
            "proxyFilePath": "/path/slsl.jpg",
            "batchNo": "2020110300000015",
            "compBankAccountId": 1,
            "confirmBy": 0,
            "confirmName": "",
            "confirmStatus": 0,
            "confirmTime": null,
            "createdBy": 13,
            "createdName": "许坤才",
            "createdTime": "2020-10-31 15:50:15",
            "currency": "CNY",
            "interTransferFee": 0.00,
            "invoiceAmt": 0,
            "invoiceNo": "",
            "isCash": "no",
            "lessPayAmt": 10.00,
            "payAccountNo": "123456",
            "payBankName": "中国银行",
            "payCorpCode": "code111",
            "payCorpName": "测试客户1",
            "preceiveAmt": 0,
            "preceiveBalance": 0,
            "proxyFileCode": "",
            "realAmt": 380.00,
            "receivableMoneyFlowList": [
                {
                    "createdBy": 0,
                    "createdName": "",
                    "createdTime": null,
                    "receivableMoneyFlowId": 3,
                    "receivableRegId": 18,
                    "receivableRegNo": "SZAR20201100034",
                    "settleCorpCode": "code111",
                    "settleCorpName": "测试客户1",
                    "updatedBy": 0,
                    "updatedName": "",
                    "updatedTime": null,
                    "useAmt": 1036.50,
                    "useScene": "收款转预收",
                    "writeoffBy": 13,
                    "writeoffName": "许坤才",
                    "writeoffReceipayId": 82,
                    "writeoffReceipayNo": "SZAR20201100034-1",
                    "writeoffTime": "2020-11-16 17:11:38",
                    "writeoffType": "money_receive_writeoff"
                },
                {
                    "createdBy": 0,
                    "createdName": "",
                    "createdTime": null,
                    "receivableMoneyFlowId": 4,
                    "receivableRegId": 18,
                    "receivableRegNo": "SZAR20201100034",
                    "settleCorpCode": "code111",
                    "settleCorpName": "测试客户1",
                    "updatedBy": 0,
                    "updatedName": "",
                    "updatedTime": null,
                    "useAmt": 963.50,
                    "useScene": "收款核销",
                    "writeoffBy": 13,
                    "writeoffName": "许坤才",
                    "writeoffReceipayId": 82,
                    "writeoffReceipayNo": "SZAR20201100034-1",
                    "writeoffTime": "2020-11-16 17:11:38",
                    "writeoffType": "money_receive_writeoff"
                },
                {
                    "createdBy": 0,
                    "createdName": "",
                    "createdTime": null,
                    "receivableMoneyFlowId": 5,
                    "receivableRegId": 18,
                    "receivableRegNo": "SZAR20201100034",
                    "settleCorpCode": "code111",
                    "settleCorpName": "测试客户1",
                    "updatedBy": 0,
                    "updatedName": "",
                    "updatedTime": null,
                    "useAmt": 30.00,
                    "useScene": "预收抵账",
                    "writeoffBy": 13,
                    "writeoffName": "许坤才",
                    "writeoffReceipayId": 83,
                    "writeoffReceipayNo": "SZAR20201100034-2",
                    "writeoffTime": "2020-11-16 19:23:43",
                    "writeoffType": "prereceive_deduction_writeoff"
                }
            ],
            "receivableRegId": 3,
            "receivableRegNo": "REC2020110300028",
            "recvCompCode": "000001",
            "recvCompName": "深圳分公司",
            "recvDate": "2020-10-10",
            "remark": "备注",
            "settleCorpCode": "code111",
            "settleCorpName": "测试客户1",
            "state": "valid",
            "toReceivableRegId": 0,
            "totalAmt": 380.00,
            "transferFeeAmt": 20.00,
            "transferFeeList": [
                {
                    "transferFeeId":12,
                    "amt":680.00,
                    "currency":"CNY",
                    "cutType":"inter_cut"
                },
                {
                    "transferFeeId":13,
                    "amt":100.00,
                    "currency":"USD",
                    "cutType":"exter_cut"
                }
            ],
            "type": "customer_pay",
            "updatedBy": 13,
            "updatedName": "许坤才",
            "updatedTime": "2020-11-04 19:32:05",
            "writeoffAmt": 340.00,
            "writeoffBalance": 40.00,
            "writeoffStatus": "finished"
        },
        "msg": "success"
    }
}