module.exports = (params) => {
    return {
        "code": 0,
        "data": [
            {
                "amt": 1000.00,
                "applyBy": 0,
                "applyItemGroupList": [],
                "applyName": "",
                "applyTime": null,
                "cancelBy": 0,
                "cancelName": "",
                "cancelRemark": "",
                "cancelTime": null,
                "copyType": "electronic",
                "createdBy": 13,
                "createdName": "许坤才",
                "createdTime": "2020-09-16 10:05:11",
                "currency": "USD",
                "emailAddrs": "",
                "emailStatus": "no",
                "fileId": 1021,
                "invoiceGroup": "normal",
                "invoiceNo": "00596469",
                "invoiceReceivableApplyId": 10,
                "invoiceReceivableApplyNo": "2020092800000012",
                "invoiceReceivableId": 6,
                "invoiceType": "electronic",
                "issueTime": "2020-09-28 17:56:50",
                "itemGoupType": "",
                "latestDate": null,
                "lockAmt": 0,
                "manualType": "",
                "postAddr": "",
                "postPhone": "",
                "postType": "",
                "printStatus": "no",
                "rate": 6.9870000000,
                "reason": "",
                "receivableRegNo": "",
                "remark": "",
                "reverseType": "",
                "saleCompAddr": "",
                "saleCompBank": "中国银行",
                "saleCompBankNo": "123456",
                "settleCompCode": "000001",
                "settleCompName": "深圳分公司",
                "splitNo": 0,
                "splitUnitAmt": 0,
                "state": "valid",
                "status": "normal",
                "statusTime": "2020-09-16 10:05:11",
                "taxNo": "",
                "taxRate": 0,
                "taxpayerNo": "440301999999980",
                "title": "硕沃信息技术",
                "updatedBy": 13,
                "updatedName": "许坤才",
                "updatedTime": "2020-09-17 10:03:04",
                "writeoffAmt": 0
            },
            {
                "amt": 1000.00,
                "applyBy": 0,
                "applyItemGroupList": [],
                "applyName": "",
                "applyTime": null,
                "cancelBy": 0,
                "cancelName": "",
                "cancelRemark": "",
                "cancelTime": null,
                "copyType": "electronic",
                "createdBy": 13,
                "createdName": "许坤才",
                "createdTime": "2020-09-18 10:05:11",
                "currency": "USD",
                "emailAddrs": "",
                "emailStatus": "no",
                "fileId": 1022,
                "invoiceGroup": "normal",
                "invoiceNo": "00921193",
                "invoiceReceivableApplyId": 10,
                "invoiceReceivableApplyNo": "2020092800000012",
                "invoiceReceivableId": 7,
                "invoiceType": "electronic",
                "issueTime": "2020-09-28 17:57:29",
                "itemGoupType": "",
                "latestDate": null,
                "lockAmt": 0,
                "manualType": "",
                "postAddr": "",
                "postPhone": "",
                "postType": "",
                "printStatus": "no",
                "rate": 6.9870000000,
                "reason": "",
                "receivableRegNo": "",
                "remark": "",
                "reverseType": "",
                "saleCompAddr": "",
                "saleCompBank": "中国银行",
                "saleCompBankNo": "123456",
                "settleCompCode": "000001",
                "settleCompName": "深圳分公司",
                "splitNo": 0,
                "splitUnitAmt": 0,
                "state": "valid",
                "status": "normal",
                "statusTime": "2020-09-18 10:05:11",
                "taxNo": "",
                "taxRate": 0,
                "taxpayerNo": "440301999999980",
                "title": "硕沃信息技术",
                "updatedBy": 13,
                "updatedName": "许坤才",
                "updatedTime": "2020-09-19 10:27:19",
                "writeoffAmt": 0
            },
            {
                "amt": 2000.00,
                "applyBy": 0,
                "applyItemGroupList": [],
                "applyName": "",
                "applyTime": null,
                "cancelBy": 0,
                "cancelName": "",
                "cancelRemark": "",
                "cancelTime": null,
                "copyType": "paper",
                "createdBy": 13,
                "createdName": "许坤才",
                "createdTime": "2020-09-30 01:13:52",
                "currency": "USD",
                "emailAddrs": "",
                "emailStatus": "no",
                "fileId": 1,
                "invoiceGroup": "normal",
                "invoiceNo": "123456",
                "invoiceReceivableApplyId": 11,
                "invoiceReceivableApplyNo": "2020093000000013",
                "invoiceReceivableId": 8,
                "invoiceType": "ordinary",
                "issueTime": "2020-09-29 16:00:00",
                "itemGoupType": "",
                "latestDate": null,
                "lockAmt": 0,
                "manualType": "yes",
                "postAddr": "",
                "postPhone": "",
                "postType": "",
                "printStatus": "no",
                "rate": 6.9870000000,
                "reason": "",
                "receivableRegNo": "",
                "remark": "",
                "reverseType": "",
                "saleCompAddr": "",
                "saleCompBank": "中国银行",
                "saleCompBankNo": "123456",
                "settleCompCode": "000001",
                "settleCompName": "深圳分公司",
                "splitNo": 0,
                "splitUnitAmt": 0,
                "state": "valid",
                "status": "normal",
                "statusTime": "2020-09-30 01:13:52",
                "taxNo": "",
                "taxRate": 0,
                "taxpayerNo": "440301999999980",
                "title": "硕沃信息技术",
                "updatedBy": 13,
                "updatedName": "许坤才",
                "updatedTime": "2020-09-30 02:34:54",
                "writeoffAmt": 0
            },
            {
                "amt": 2000.00,
                "applyBy": 0,
                "applyItemGroupList": [],
                "applyName": "",
                "applyTime": null,
                "cancelBy": 0,
                "cancelName": "",
                "cancelRemark": "",
                "cancelTime": null,
                "copyType": "paper",
                "createdBy": 13,
                "createdName": "许坤才",
                "createdTime": "2020-09-30 02:38:22",
                "currency": "USD",
                "emailAddrs": "",
                "emailStatus": "no",
                "fileId": 0,
                "invoiceGroup": "normal",
                "invoiceNo": "",
                "invoiceReceivableApplyId": 12,
                "invoiceReceivableApplyNo": "2020093000000014",
                "invoiceReceivableId": 9,
                "invoiceType": "ordinary",
                "issueTime": null,
                "itemGoupType": "",
                "latestDate": null,
                "lockAmt": 0,
                "manualType": "",
                "postAddr": "",
                "postPhone": "",
                "postType": "",
                "printStatus": "no",
                "rate": 6.9870000000,
                "reason": "",
                "receivableRegNo": "",
                "remark": "",
                "reverseType": "",
                "saleCompAddr": "",
                "saleCompBank": "中国银行",
                "saleCompBankNo": "123456",
                "settleCompCode": "000001",
                "settleCompName": "深圳分公司",
                "splitNo": 0,
                "splitUnitAmt": 0,
                "state": "valid",
                "status": "normal",
                "statusTime": "2020-09-30 02:38:22",
                "taxNo": "",
                "taxRate": 0,
                "taxpayerNo": "440301999999980",
                "title": "硕沃信息技术",
                "updatedBy": 0,
                "updatedName": "",
                "updatedTime": null,
                "writeoffAmt": 0
            },
            {
                "amt": 2000.00,
                "applyBy": 0,
                "applyItemGroupList": [],
                "applyName": "",
                "applyTime": null,
                "cancelBy": 0,
                "cancelName": "",
                "cancelRemark": "",
                "cancelTime": null,
                "copyType": "paper",
                "createdBy": 13,
                "createdName": "许坤才",
                "createdTime": "2020-09-30 09:20:02",
                "currency": "USD",
                "emailAddrs": "",
                "emailStatus": "no",
                "fileId": 0,
                "invoiceGroup": "normal",
                "invoiceNo": "",
                "invoiceReceivableApplyId": 13,
                "invoiceReceivableApplyNo": "2020093000000015",
                "invoiceReceivableId": 10,
                "invoiceType": "ordinary",
                "issueTime": null,
                "itemGoupType": "",
                "latestDate": null,
                "lockAmt": 0,
                "manualType": "",
                "postAddr": "",
                "postPhone": "",
                "postType": "",
                "printStatus": "no",
                "rate": 6.9870000000,
                "reason": "",
                "receivableRegNo": "",
                "remark": "",
                "reverseType": "",
                "saleCompAddr": "",
                "saleCompBank": "中国银行",
                "saleCompBankNo": "123456",
                "settleCompCode": "000001",
                "settleCompName": "深圳分公司",
                "splitNo": 0,
                "splitUnitAmt": 0,
                "state": "valid",
                "status": "normal",
                "statusTime": "2020-09-30 09:20:02",
                "taxNo": "",
                "taxRate": 0,
                "taxpayerNo": "440301999999980",
                "title": "硕沃信息技术",
                "updatedBy": 0,
                "updatedName": "",
                "updatedTime": null,
                "writeoffAmt": 0
            }
        ],
        "msg": "success"
    }
}