module.exports = (params) => {
    return {
        "code": 0,
        "data": {
                    "accountNo": "744557928354",
                    "bankSeqNo": "",
                    "bankseqFileCode": "",
                    "batchNo": "",
                    "compBankAccountId": 0,
                    "corpPrerevAccountId": 6,
                    "createdBy": 13,
                    "createdName": "许坤才",
                    "createdTime": "2020-11-04 17:02:28",
                    "currency": "CNY",
                    "isCash": "",
                    "lessPayAmt": 0,
                    "payAccountNo": "6210488826832500",
                    "payBankName": "中国工商银行",
                    "payCorpCode": "code111",
                    "payCorpName": "测试客户1",
                    "preceiveAmt": 380.00,
                    "proxyFileCode": "",
                    "realAmt": 0,
                    "receivablePrerevId": 7,
                    "receivableRegId": 4,
                    "receivableRegNo": "REC2020110300029",
                    "receiveAmt": 380.00,
                    "recvCompCode": "000001",
                    "recvCompName": "深圳分公司",
                    "recvDate": "2021-5-10",
                    "remark": "remark",
                    "settleCorpCode": "code111",
                    "settleCorpName": "测试客户1",
                    "writeoffReceipayNo": "0001532123",
                    "voucherNo": "99900003",
                    "invoiceNo": "0000000000003",
                    "transferFeeAmt": 0,
                    "transferFeeList": [],
                    "receivableRegInfo": {
                        "receivableRegId":'11',
                        "bankSeqNo":'8000003285520',
                        "recvCompCode":'收款分公司编码',
                        "recvCompName":'收款分公司名称',
                        "recvDate":'2021-6-10',
                        "type":'收款登记类型',
                        "receivableRegNo":'收款登记编号',
                        "batchNo":'批量上传编号',
                        "payAccountNo":'付款款账号',
                        "payBankName":'中国农业银行',
                        "payCorpName":'硕沃公司',
                        "accountNo":'620800025205632828',
                        "createdName":'刘昌杰',
                        "createdTime":'2020-12-30',
                        "currency":'CNY',
                        "realAmt":'实际收款金额',
                        "lessPayAmt":'客户短款金额',
                        "transferFeeAmt":'手续费总额',
                        "interTransferFee":'内扣手续费总额',
                        "totalAmt":'可核销金额',
                        "settleCorpName":'长帆国际物流开发工程师',
                    },
                    "receivableMoneyFlowList": [
                        {
                            "receivableMoneyFlowId":1,
                            "writeoffReceipayId":77,
                            "receivableRegId":122,
                            "writeoffReceipayNo":'SF123000',
                            "useAmt":'20.00',
                            "settleCorpName":'长帆国际物流开发工程师',
                            "settleCorpCode":'000000021',
                            "writeoffType":'核销类型',
                            "writeoffName":'刘昌杰',
                            "writeoffTime":'2020-12-30',
                        }
                    ],
                    "type": "",
                    "updatedBy": 0,
                    "updatedName": "",
                    "updatedTime": null,
                    "writeoffStatus": "",
                    
                },
        "msg": "success"
    }
}