module.exports = (params) => {
    return {
        "code": 0,
        "data": {
            "allColumns": [],
            "configColumns": [],
            "currPage": 1,
            "list": [
                {
                    "accountNo": "744557928354",
                    "bankSeqNo": "",
                    "bankseqFileCode": "",
                    "batchNo": "",
                    "compBankAccountId": 0,
                    "corpPrerevAccountId": 6,
                    "createdBy": 13,
                    "createdName": "许坤才",
                    "createdTime": "2020-11-04 17:02:28",
                    "currency": "CNY",
                    "isCash": "",
                    "lessPayAmt": 0,
                    "payAccountNo": "",
                    "payBankName": "",
                    "payCorpCode": "code111",
                    "payCorpName": "测试客户1",
                    "preceiveAmt": 380.00,
                    "proxyFileCode": "",
                    "realAmt": 0,
                    "receivablePrerevId": 7,
                    "receivableRegId": 4,
                    "receivableRegNo": "REC2020110300029",
                    "receiveAmt": 380.00,
                    "recvCompCode": "000001",
                    "recvCompName": "深圳分公司",
                    "recvDate": "2020-10-10",
                    "remark": "",
                    "settleCorpCode": "code111",
                    "settleCorpName": "测试客户1",
                    "transferFeeAmt": 0,
                    "transferFeeList": [],
                    "type": "",
                    "updatedBy": 0,
                    "updatedName": "",
                    "updatedTime": null,
                    "writeoffStatus": ""
                },
                {
                    "accountNo": "744557928354",
                    "bankSeqNo": "",
                    "bankseqFileCode": "",
                    "batchNo": "",
                    "compBankAccountId": 0,
                    "corpPrerevAccountId": 6,
                    "createdBy": 13,
                    "createdName": "许坤才",
                    "createdTime": "2020-11-04 19:32:05",
                    "currency": "CNY",
                    "isCash": "",
                    "lessPayAmt": 0,
                    "payAccountNo": "",
                    "payBankName": "",
                    "payCorpCode": "code111",
                    "payCorpName": "测试客户1",
                    "preceiveAmt": 40.00,
                    "proxyFileCode": "",
                    "realAmt": 0,
                    "receivablePrerevId": 8,
                    "receivableRegId": 3,
                    "receivableRegNo": "REC2020110300028",
                    "receiveAmt": 380.00,
                    "recvCompCode": "000001",
                    "recvCompName": "深圳分公司",
                    "recvDate": "2020-10-10",
                    "remark": "",
                    "settleCorpCode": "code111",
                    "settleCorpName": "测试客户1",
                    "transferFeeAmt": 0,
                    "transferFeeList": [],
                    "type": "",
                    "updatedBy": 0,
                    "updatedName": "",
                    "updatedTime": null,
                    "writeoffStatus": ""
                }
            ],
            "pageSize": 5,
            "totalCount": 2,
            "totalPage": 1
        },
        "msg": "success"
    }
}