module.exports = (params) => {
    return {
        "code": 0,
        "data": {
            "accountNo": "744557928354",
            "balance": 40.00,
            "bankSeqNo": "123456",
            "bankseqFileCode": "",
            "batchNo": "",
            "compBankAccountId": 1,
            "corpPrerevAccountId": 6,
            "createdBy": 13,
            "createdName": "许坤才",
            "createdTime": "2020-11-04 19:32:05",
            "currency": "CNY",
            "isCash": "",
            "payAccountNo": "123456",
            "payBankName": "",
            "payCorpCode": "code111",
            "payCorpName": "测试客户1",
            "preceiveAmt": 40.00,
            "proxyFileCode": "",
            "receivablePrerevId": 8,
            "receivableRegId": 3,
            "receivableRegNo": "REC2020110300028",
            "receiveAmt": 380.00,
            "recvCompCode": "000001",
            "recvCompName": "深圳分公司",
            "recvDate": "2020-10-10",
            "refundAmt": 0.00,
            "settleCorpCode": "code111",
            "settleCorpName": "测试客户1",
            "transferFeeList": [
                {
                    "amt": 20.00,
                    "bankSeqNo": "123456",
                    "batchNo": "2020110300000015",
                    "createdBy": 13,
                    "createdName": "许坤才",
                    "createdTime": "2020-11-03 07:50:15",
                    "currency": "CNY",
                    "cutType": "exter_cut",
                    "feeId": 202,
                    "hasAllotAmt": 20.00,
                    "payOrderId": 0,
                    "receipayType": "receive",
                    "receivableRegId": 3,
                    "revision": 0,
                    "settleCompCode": "000001",
                    "settleCompName": "深圳分公司",
                    "state": "valid",
                    "transferFeeId": 3,
                    "updatedBy": 13,
                    "updatedName": "许坤才",
                    "updatedTime": "2020-11-04 19:32:05",
                    "writeoffReceipayNo": "WR202011049964000059"
                }
            ],
            "type": "customer_pay",
            "updatedBy": 0,
            "updatedName": "",
            "updatedTime": null,
            "writeoffAmt": 0.00
        },
        "msg": "success"
    }
}