module.exports = (prams) => {
    return {
        "code": 0,
        "data": {
            "allColumns": [],
            "configColumns": [],
            "currPage": 1,
            "list": [
                {
                    "closeTime": "2020-09-15T17:50:11",
                    "eventCloseCode": "ShipAuditPassEvent",
                    "eventCode": "ShipOrderSubmitEvent",
                    "eventType": "order",
                    "handleStatus": "y",
                    "noticeContent": "订单号：S202009150000524已提交审核,请点击<a style='color:#409EFF' href=\"http://www.baidu.com?orderNo=S202009150000524\">这里</a> 审核",
                    "noticeEmployeeId": 9,
                    "noticePriority": 'low',
                    "noticeTime": null,
                    "noticeTitle": "订单号S202009150000524已提交审核,请尽快审核",
                    "noticeType": "todo",
                    "oid": 1,
                    "relateNo": "S202009150000524",
                    "revision": 2,
                    "state": "valid",
                    "templateNo": "TEST001",
                    "viewStatus": "y",
                    "viewTime": null,
                    "updatedBy": 9,
                    "updatedName": "安亮",
                    "updatedTime": "2020-09-15T17:50:11",
                    "createdBy": 9,
                    "createdName": "安亮",
                    "createdTime": "2020-09-15T17:30:00",
                },
                {
                    "closeTime": "2020-09-15T17:50:11",
                    "eventCloseCode": "ShipAuditPassEvent",
                    "eventCode": "ShipOrderSubmitEvent",
                    "eventType": "order",
                    "handleStatus": "n",
                    "noticeContent": "订单号：S202009150000524已提交审核,请点击<a style='color:#409EFF' href=\"http://www.baidu.com?orderNo=S202009150000524\">这里</a> 审核",
                    "noticeEmployeeId": 9,
                    "noticePriority": 'middle',
                    "noticeTime": null,
                    "noticeTitle": "订单号S202009150000524已提交审核,请尽快审核",
                    "noticeType": "todo",
                    "oid": 2,
                    "relateNo": "S202009150000524",
                    "revision": 2,
                    "state": "valid",
                    "templateNo": "TEST001",
                    "viewStatus": "y",
                    "viewTime": null,
                    "updatedBy": 9,
                    "updatedName": "安亮",
                    "updatedTime": "2020-09-15T17:50:11",
                    "createdBy": 9,
                    "createdName": "安亮",
                    "createdTime": "2020-09-15T17:30:00",
                },
                {
                    "closeTime": "2020-09-15T17:50:11",
                    "eventCloseCode": "ShipAuditPassEvent",
                    "eventCode": "ShipOrderSubmitEvent",
                    "eventType": "order",
                    "handleStatus": "y",
                    "noticeContent": "订单号：S202009150000524已提交审核,请点击<a style='color:#409EFF' href=\"http://www.baidu.com?orderNo=S202009150000524\">这里</a> 审核",
                    "noticeEmployeeId": 9,
                    "noticePriority": 'high',
                    "noticeTime": null,
                    "noticeTitle": "订单号S202009150000524已提交审核,请尽快审核",
                    "noticeType": "todo",
                    "oid": 3,
                    "relateNo": "S202009150000524",
                    "revision": 2,
                    "state": "valid",
                    "templateNo": "TEST001",
                    "viewStatus": "n",
                    "viewTime": null,
                    "updatedBy": 9,
                    "updatedName": "安亮",
                    "updatedTime": "2020-09-15T17:50:11",
                    "createdBy": 9,
                    "createdName": "安亮",
                    "createdTime": "2020-09-15T17:30:00",
                },
                {
                    "closeTime": "2020-09-15T17:50:11",
                    "eventCloseCode": "ShipAuditPassEvent",
                    "eventCode": "ShipOrderSubmitEvent",
                    "eventType": "order",
                    "handleStatus": "y",
                    "noticeContent": "订单号：S202009150000524已提交审核,请点击<a style='color:#409EFF' href=\"http://www.baidu.com?orderNo=S202009150000524\">这里</a> 审核",
                    "noticeEmployeeId": 9,
                    "noticePriority": 'middle',
                    "noticeTime": null,
                    "noticeTitle": "订单号S202009150000524已提交审核,请尽快审核",
                    "noticeType": "todo",
                    "oid": 1,
                    "relateNo": "S202009150000524",
                    "revision": 2,
                    "state": "valid",
                    "templateNo": "TEST001",
                    "viewStatus": "y",
                    "viewTime": null,
                    "updatedBy": 9,
                    "updatedName": "安亮",
                    "updatedTime": "2020-09-15T17:50:11",
                    "createdBy": 9,
                    "createdName": "安亮",
                    "createdTime": "2020-09-15T17:30:00",
                },
            ],
            "pageSize": 10,
            "totalCount": 17,
            "totalPage": 2
        },
        "msg": "success"
    }
  };