module.exports = (params) => {
  return {
    "code": 0,
    "data": {
                "amt": 2000.00,
                "applyFeeList": [],
                "applyItemGroupList": [],
                "applySource": "quickly_invoice",
                "createdBy": 13,
                "createdName": "许坤才",
                "createdTime": "2020-09-15T01:39:20",
                "currency": "USD",
                "emailAddrs": "abc@abc.com",
                "invoiceNo": "",
                "invoiceReceivableApplyId": 2,
                "invoiceReceivableApplyNo": "2020091500000004",
                "invoiceStatus": "",
                "invoiceSubitems": "",
                "invoiceType": "ordinary",
                "itemGoupType": "detail",
                "latestDate": "2020-09-14",
                "manualType": "",
                "postAddr": "文化大厦2楼",
                "postPhone": "15888888888",
                "postType": "express",
                "rate": 6.9870000000,
                "remark": "备注",
                "remarkInUse": "",
                "settleCompCode": "000001",
                "settleCompName": "深圳分公司",
                "settleCorpCode": "12321",
                "settleCorpName": "硕沃信息技术",
                "settleOrderNo": "123132",
                "splitNo": 1,
                "splitUnitAmt": 1000.00,
                "state": "valid",
                "taxNo": "123231",
                "taxRate": 0.03,
                "title": "硕沃信息技术",
                "updatedBy": 0,
                "updatedName": "",
                "updatedTime": null
            },
    "msg": "success"
  }
}