module.exports = (prams) => {
    return {
        "code": 0,
        "data":{
            "pages":[
                {
                    "modules":[
    
                    ],
                    "openAssess":"",
                    "pageAuth":"no",
                    "pageCode":"order_menu1",
                    "pageId":1,
                    "pageName":"订单中心",
                    "pageType":"menu",
                    "pageUrl":"/test/1",
                    "state":""
                },
                {
                    "modules":[
    
                    ],
                    "openAssess":"",
                    "pageAuth":"no",
                    "pageCode":"order_menu1_list",
                    "pageId":2,
                    "pageName":"订单列表",
                    "pageType":"menu",
                    "pageUrl":"/order/list",
                    "state":""
                },
                {
                    "modules":[
    
                    ],
                    "openAssess":"",
                    "pageAuth":"no",
                    "pageCode":"财务中心_子菜单2",
                    "pageId":3,
                    "pageName":"财务中心",
                    "pageType":"menu",
                    "pageUrl":"/order/list",
                    "state":""
                },
                {
                    "modules":[
    
                    ],
                    "openAssess":"",
                    "pageAuth":"no",
                    "pageCode":"_HFmM",
                    "pageId":6,
                    "pageName":"财务中心_子菜单1",
                    "pageType":"menu",
                    "pageUrl":"/order/list",
                    "state":""
                },
                {
                    "modules":[
    
                    ],
                    "openAssess":"",
                    "pageAuth":"no",
                    "pageCode":"_xFpl",
                    "pageId":7,
                    "pageName":"财务_子菜单1",
                    "pageType":"menu",
                    "pageUrl":"/order/list",
                    "state":""
                },
                {
                    "modules":[
    
                    ],
                    "openAssess":"",
                    "pageAuth":"no",
                    "pageCode":"asdfads",
                    "pageId":8,
                    "pageName":"定价中心",
                    "pageType":"page",
                    "pageUrl":"#",
                    "state":""
                },
                {
                    "modules":[
                        {
                            "functions":[
                                {
                                    "auth":"no",
                                    "code":"view",
                                    "name":"显示",
                                    "url":"/test/page1/view"
                                }
                            ],
                            "moduleAuth":"no",
                            "moduleCode":"my_module_code1",
                            "moduleId":2,
                            "moduleName":"我的页面模块1"
                        },
                        {
                            "functions":[
                                {
                                    "auth":"no",
                                    "code":"edit",
                                    "name":"编辑",
                                    "url":"/test/page1/edit2"
                                },
                                {
                                    "auth":"no",
                                    "code":"submit",
                                    "name":"提交",
                                    "url":"/test/page1/submit2"
                                }
                            ],
                            "moduleAuth":"no",
                            "moduleCode":"my_module_code2",
                            "moduleId":3,
                            "moduleName":"我的页面模块2"
                        },
                        {
                            "functions":[
    
                            ],
                            "moduleAuth":"no",
                            "moduleCode":"",
                            "moduleId":4,
                            "moduleName":"我的页面模块3"
                        },
                        {
                            "functions":[
    
                            ],
                            "moduleAuth":"no",
                            "moduleCode":"",
                            "moduleId":5,
                            "moduleName":"我的页面子模块4"
                        }
                    ],
                    "openAssess":"",
                    "pageAuth":"no",
                    "pageCode":"vFwjOS",
                    "pageId":9,
                    "pageName":"我的页面",
                    "pageType":"page",
                    "pageUrl":"/test/page1",
                    "state":""
                },
                {
                    "modules":[
    
                    ],
                    "openAssess":"",
                    "pageAuth":"no",
                    "pageCode":"ilSgdy2",
                    "pageId":142,
                    "pageName":"基础数据",
                    "pageType":"menu",
                    "pageUrl":"",
                    "state":""
                },
                {
                    "modules":[
    
                    ],
                    "openAssess":"",
                    "pageAuth":"no",
                    "pageCode":"ilSgdy_zxQEbe",
                    "pageId":143,
                    "pageName":"海运数据",
                    "pageType":"menu",
                    "pageUrl":"",
                    "state":""
                },
                {
                    "modules":[
    
                    ],
                    "openAssess":"",
                    "pageAuth":"no",
                    "pageCode":"cmwrDV",
                    "pageId":145,
                    "pageName":"测试页面",
                    "pageType":"page",
                    "pageUrl":"1",
                    "state":""
                },
                {
                    "modules":[
                        {
                            "functions":[
    
                            ],
                            "moduleAuth":"yes",
                            "moduleCode":"SettlementFeeList-createSettlement",
                            "moduleId":18,
                            "moduleName":"生成结算单"
                        }
                    ],
                    "openAssess":"",
                    "pageAuth":"yes",
                    "pageCode":"SettlementFeeList",
                    "pageId":146,
                    "pageName":"费用列表",
                    "pageType":"page",
                    "pageUrl":"",
                    "state":""
                },
                {
                    "modules":[
    
                    ],
                    "openAssess":"",
                    "pageAuth":"yes",
                    "pageCode":"SettlementList",
                    "pageId":147,
                    "pageName":"结算单列表",
                    "pageType":"page",
                    "pageUrl":"cs",
                    "state":""
                },
                {
                    "modules":[
    
                    ],
                    "openAssess":"",
                    "pageAuth":"no",
                    "pageCode":"order_menu1_list_PKZnsp",
                    "pageId":149,
                    "pageName":"订单新增",
                    "pageType":"menu",
                    "pageUrl":"",
                    "state":""
                },
                {
                    "modules":[
    
                    ],
                    "openAssess":"",
                    "pageAuth":"no",
                    "pageCode":"order_menu1_list_PKZnsp_mJrydr",
                    "pageId":150,
                    "pageName":"订单编辑",
                    "pageType":"menu",
                    "pageUrl":"",
                    "state":""
                },
                {
                    "modules":[
    
                    ],
                    "openAssess":"",
                    "pageAuth":"no",
                    "pageCode":"order_menu1_list_ZtvVjY",
                    "pageId":151,
                    "pageName":"订单编辑",
                    "pageType":"menu",
                    "pageUrl":"",
                    "state":""
                },
                {
                    "modules":[
    
                    ],
                    "openAssess":"",
                    "pageAuth":"no",
                    "pageCode":"Finance",
                    "pageId":152,
                    "pageName":"财务",
                    "pageType":"menu",
                    "pageUrl":"",
                    "state":""
                },
                {
                    "modules":[
    
                    ],
                    "openAssess":"",
                    "pageAuth":"no",
                    "pageCode":"OtherFeeList",
                    "pageId":153,
                    "pageName":"订单费用",
                    "pageType":"menu",
                    "pageUrl":"",
                    "state":""
                },
                {
                    "modules":[
    
                    ],
                    "openAssess":"",
                    "pageAuth":"no",
                    "pageCode":"Settlement",
                    "pageId":154,
                    "pageName":"结算单",
                    "pageType":"menu",
                    "pageUrl":"",
                    "state":""
                },
                {
                    "modules":[
    
                    ],
                    "openAssess":"",
                    "pageAuth":"no",
                    "pageCode":"SettlementFeeList",
                    "pageId":157,
                    "pageName":"费用列表",
                    "pageType":"menu",
                    "pageUrl":"",
                    "state":""
                },
                {
                    "modules":[
    
                    ],
                    "openAssess":"",
                    "pageAuth":"no",
                    "pageCode":"SettlementList",
                    "pageId":158,
                    "pageName":"结算单列表",
                    "pageType":"menu",
                    "pageUrl":"",
                    "state":""
                }
            ]
        },
        "msg": "success"
    }
};