module.exports = (prams) => {
    return {
        "code":0,
        "msg":"success",
        "data":{
            "bvBlVos": [
                {
                    "blId": 1,
                    "blNo": "9002",
                    "fileNum": 2,
                    "bvCnVos": [
                        {
                            "cn": "1",
                            "containerId": 1,
                            "bvBoxVos": [
                                {
                                    "blId": 1,
                                    "containerId": 346,
                                    "createdBy": 0,
                                    "createdName": "",
                                    "createdTime": null,
                                    "currency": "CNY",
                                    "intrustNo": "AII2020110700001",
                                    "mark": "长虹视1",
                                    "name": "视机1",
                                    "oid": 11,
                                    "orderNo": "S202009300000571",
                                    "packageType": "box",
                                    "quantity": 123,
                                    "revision": 2,
                                    "state": "valid",
                                    "totalPrice": 94279.5,
                                    "unitPrice": 766.5,
                                    "updatedBy": 20,
                                    "updatedName": "操作【勿动】",
                                    "updatedTime": "2020-11-19 15:10:22",
                                    "volume": 41,
                                    "weight": 1501
                                },
                                {
                                    "containerId": 346,
                                    "createdBy": 0,
                                    "createdName": "",
                                    "createdTime": null,
                                    "currency": "CNY",
                                    "intrustNo": "AII2020110700001",
                                    "mark": "电视2",
                                    "name": "电机2",
                                    "oid": 12,
                                    "orderNo": "S202009300000571",
                                    "packageType": "bag",
                                    "quantity": 120,
                                    "revision": 2,
                                    "state": "valid",
                                    "totalPrice": 95000,
                                    "unitPrice": 766.5,
                                    "updatedBy": 20,
                                    "updatedName": "操作【勿动】",
                                    "updatedTime": "2020-11-19 15:10:22",
                                    "volume": 31,
                                    "weight": 1301
                                }
                            ],
                        },
                        {
                            "cn": "2",
                            "containerId": 2,
                            "bvBoxVos": [
                                {
                                    "blId": 1,
                                    "containerId": 2,
                                    "createdBy": 0,
                                    "createdName": "",
                                    "createdTime": null,
                                    "currency": "CNY",
                                    "intrustNo": "AII2020110700001",
                                    "mark": "长虹视1",
                                    "name": "视机1",
                                    "oid": 11,
                                    "orderNo": "S202009300000571",
                                    "packageType": "box",
                                    "quantity": 123,
                                    "revision": 2,
                                    "state": "valid",
                                    "totalPrice": 94279.5,
                                    "unitPrice": 766.5,
                                    "updatedBy": 20,
                                    "updatedName": "操作【勿动】",
                                    "updatedTime": "2020-11-19 15:10:22",
                                    "volume": 41,
                                    "weight": 1501
                                }
                            ],
                        }
                    ],
                },
                {
                    "blId": 2,
                    "blNo": "9003",
                    "fileNum": 2,
                    "bvCnVos": [
                        {
                            "cn": "2",
                            "containerId": 2,
                            "bvBoxVos": [
                                {
                                    "blId": 1,
                                    "containerId": 346,
                                    "createdBy": 0,
                                    "createdName": "",
                                    "createdTime": null,
                                    "currency": "CNY",
                                    "intrustNo": "AII2020110700001",
                                    "mark": "长虹视1",
                                    "name": "视机1",
                                    "oid": 11,
                                    "orderNo": "S202009300000571",
                                    "packageType": "box",
                                    "quantity": 123,
                                    "revision": 2,
                                    "state": "valid",
                                    "totalPrice": 94279.5,
                                    "unitPrice": 766.5,
                                    "updatedBy": 20,
                                    "updatedName": "操作【勿动】",
                                    "updatedTime": "2020-11-19 15:10:22",
                                    "volume": 41,
                                    "weight": 1501
                                },
                                {
                                    "containerId": 346,
                                    "createdBy": 0,
                                    "createdName": "",
                                    "createdTime": null,
                                    "currency": "CNY",
                                    "intrustNo": "AII2020110700001",
                                    "mark": "电视2",
                                    "name": "电机2",
                                    "oid": 12,
                                    "orderNo": "S202009300000571",
                                    "packageType": "bag",
                                    "quantity": 120,
                                    "revision": 2,
                                    "state": "valid",
                                    "totalPrice": 95000,
                                    "unitPrice": 766.5,
                                    "updatedBy": 20,
                                    "updatedName": "操作【勿动】",
                                    "updatedTime": "2020-11-19 15:10:22",
                                    "volume": 31,
                                    "weight": 1301
                                }
                            ],
                        }
                    ],
                }
            ],
            "checkContact": "万里江山",
            "checkContactPhone": "15977776666",
            "checkSupplierId": 22,
            "checkSupplierName": "深发展",
            "createdBy": 0,
            "createdName": "",
            "createdTime": null,
            "declareContact": "东方不败",
            "declareContactPhone": "15899997777",
            "declareCustName": "孤独求败",
            "declareCustid": 11,
            "intrustNo": "AII2020110700001",
            "oid": 1,
            "orderNo": "S202009300000571",
            "remark": "test",
            "revision": 1,
            "state": "valid",
            "status": "1",
            "updatedBy": 0,
            "updatedName": "",
            "updatedTime": null
        }
    }
};
