module.exports = (params) => {
    return {
        "code": 0,
        "data": {
            "applyNo": "2020111800000006",
            "confirmBy": 0,
            "confirmName": "刘昌杰",
            "confirmStatus": "",
            "confirmTime": null,
            "createdBy": 13,
            "createdName": "许坤才",
            "createdTime": "2020-11-18 16:00:36",
            "delayInvoice": "no",
            "emplAbatementId": 0,
            "hasInvoice": "",
            "payApplyReceiveRefundId": 3,
            "payInfoId": 49,
            "payOrderId": 0,
            "payOrderNo": "12342131",
            "realRefundAmt": 100.00,
            "receivablePrerevId": 15,
            "receivableRegId": 21,
            "receivableRegNo": "SZAR20201100037",
            "recvAccountName": "",
            "recvAccountNo": "",
            "recvBankAccountId": 0,
            "recvBankBranch": "",
            "recvBankCode": "",
            "recvBankName": "",
            "refundCurrency": "CNY",
            "refundType": "overpayment",
            "refuseReason": "原因是刘昌杰开发工程师",
            "remark": "退款说明",
            "settleCompCode": "V000000002",
            "settleCompName": "许坤才",
            "settleCorpCode": "",
            "settleCorpName": "",
            "state": "valid",
            "transferChargeType": "customer",
            "transferCharger": "1",
            "transferFeeAmt": 100.00,
            "transferFeeCurrency": "CNY",
            "trustFileId": 0,
            "updatedBy": 0,
            "updatedName": "",
            "updatedTime": null,
            "receivableRegDetail": {
                "accountNo": "744557928354",
                "accountShortName": "深圳长帆中行CNY",
                "bankSeqNo": "123546",
                "bankseqFileCode": "",
                "bankseqFileName": "",
                "bankseqFilePath": "text.xlsx",
                "batchNo": "",
                "compBankAccountId": 1,
                "confirmBy": 13,
                "confirmName": "许坤才",
                "confirmStatus": "yes",
                "confirmTime": "2020-11-17 15:45:04",
                "createdBy": 13,
                "createdName": "许坤才",
                "createdTime": "2020-11-17 15:44:42",
                "currency": "CNY",
                "interTransferFee": 0.00,
                "isCash": "no",
                "lessPayAmt": 0.00,
                "outerTransferFee": 20.00,
                "payAccountNo": "9042",
                "payBankName": "中国银行",
                "payCorpCode": "V000000002",
                "payCorpName": "许坤才",
                "proxyFileCode": "",
                "proxyFileName": "",
                "proxyFilePath": "./text",
                "realAmt": 2000.00,
                "receivableMoneyFlowList": [
                    {
                        "createdBy": 0,
                        "createdName": "",
                        "createdTime": null,
                        "receivableMoneyFlowId": 16,
                        "receivableRegId": 21,
                        "receivableRegNo": "SZAR20201100037",
                        "settleCorpCode": "V000000002",
                        "settleCorpName": "许坤才",
                        "updatedBy": 0,
                        "updatedName": "",
                        "updatedTime": null,
                        "useAmt": 0.00,
                        "useScene": "收款核销",
                        "writeoffBy": 13,
                        "writeoffName": "许坤才",
                        "writeoffReceipayId": 105,
                        "writeoffReceipayNo": "SZAR20201100037-1",
                        "writeoffTime": "2020-11-18 16:00:35",
                        "writeoffType": "prereceive_refund_writeoff"
                    },
                    {
                        "createdBy": 0,
                        "createdName": "",
                        "createdTime": null,
                        "receivableMoneyFlowId": 17,
                        "receivableRegId": 21,
                        "receivableRegNo": "SZAR20201100037",
                        "settleCorpCode": "V000000002",
                        "settleCorpName": "许坤才",
                        "updatedBy": 0,
                        "updatedName": "",
                        "updatedTime": null,
                        "useAmt": 2000.00,
                        "useScene": "收款登记转预收",
                        "writeoffBy": 13,
                        "writeoffName": "许坤才",
                        "writeoffReceipayId": 105,
                        "writeoffReceipayNo": "SZAR20201100037-1",
                        "writeoffTime": "2020-11-18 16:00:35",
                        "writeoffType": "prereceive_refund_writeoff"
                    }
                ],
                "receivableRegId": 21,
                "receivableRegNo": "SZAR20201100037",
                "recvCompCode": "000001",
                "recvCompName": "深圳分公司",
                "recvDate": null,
                "remark": "备注",
                "settleCorpCode": "V000000002",
                "settleCorpName": "许坤才",
                "state": "valid",
                "toReceivableRegId": 0,
                "totalAmt": 2000.00,
                "transferFeeAmt": 20.00,
                "transferFeeList": [
                    {
                        "amt": 20.00,
                        "bankSeqNo": "123546",
                        "batchNo": "",
                        "createdBy": 13,
                        "createdName": "许坤才",
                        "createdTime": "2020-11-17 15:44:42",
                        "currency": "CNY",
                        "cutType": "exter_cut",
                        "feeId": 400,
                        "hasAllotAmt": 0.00,
                        "payOrderId": 0,
                        "receipayType": "receive",
                        "receivableRegId": 21,
                        "revision": 1,
                        "settleCompCode": "000001",
                        "settleCompName": "深圳分公司",
                        "state": "valid",
                        "transferFeeId": 22,
                        "updatedBy": 0,
                        "updatedName": "",
                        "updatedTime": null,
                        "writeoffReceipayNo": ""
                    }
                ],
                "type": "customer_pay",
                "updatedBy": 13,
                "updatedName": "许坤才",
                "updatedTime": "2020-11-18 16:00:36",
                "writeoffAmt": 2000.00,
                "writeoffBalance": 0.00,
                "writeoffStatus": "finished"
            },
            "trustFileList": [
                {
                    "createdBy": 0,
                    "createdName": "",
                    "createdTime": null,
                    "oid": 3,
                    "payApplyReceiveRefundId": 3,
                    "state": "",
                    "trustFileId": 1031,
                    "trustFileName": "5121093785978881.pdf",
                    "trustFileNo": "F2020092915489723170000000001077",
                    "trustFilePath": "D:/upload/20200929/be9b7cc2d98441788940117d04ee2d65.pdf",
                    "updatedBy": 0,
                    "updatedName": "",
                    "updatedTime": null
                }
            ]
        },
        "msg": "success"
    }
}