module.exports = (params) => {
    return {
        "code": 0,
        "data": {
            "allColumns": [],
            "configColumns": [],
            "currPage": 1,
            "list": [
                {
                    "applyNo": "2020102000000002",
                    "confirmBy": 0,
                    "confirmName": "",
                    "confirmStatus": "",
                    "confirmTime": null,
                    "createdBy": 13,
                    "createdName": "许坤才",
                    "createdTime": "2020-10-20 02:40:06",
                    "delayInvoice": "no",
                    "emplAbatementId": 0,
                    "hasInvoice": "",
                    "payApplyReceiveRefundId": 1,
                    "payInfoId": 24,
                    "payOrderId": 0,
                    "payOrderNo": "",
                    "payWay": "",
                    "realRefundAmt": 100.00,
                    "receivableRegId": 1,
                    "receivableRegNo": "123456",
                    "recvAccountName": "长帆开票测试",
                    "recvAccountNo": "123456",
                    "recvAcountId": 0,
                    "recvBankAccountId": 0,
                    "recvBankBranch": "",
                    "recvBankCode": "",
                    "recvBankName": "",
                    "refundCurrency": "CNY",
                    "refundType": "overpayment",
                    "refuseReason": "",
                    "remark": "退款说明",
                    "settleCompCode": "cus000001",
                    "settleCompName": "长帆开票测试",
                    "state": "valid",
                    "transferChargeType": "customer",
                    "transferCharger": "1",
                    "transferFeeAmt": 100.00,
                    "transferFeeCurrency": "CNY",
                    "trustFileId": 1,
                    "updatedBy": 0,
                    "updatedName": "刘昌杰",
                    "updatedTime": "2020-12-30 15:40:06"
                },
                {
                    "applyNo": "2020102000000003",
                    "confirmBy": 0,
                    "confirmName": "",
                    "confirmStatus": "",
                    "confirmTime": null,
                    "createdBy": 13,
                    "createdName": "许坤才",
                    "createdTime": "2020-10-20 02:40:06",
                    "delayInvoice": "no",
                    "emplAbatementId": 0,
                    "hasInvoice": "",
                    "payApplyReceiveRefundId": 1,
                    "payInfoId": 24,
                    "payOrderId": 0,
                    "payOrderNo": "",
                    "payWay": "",
                    "realRefundAmt": 100.00,
                    "receivableRegId": 1,
                    "receivableRegNo": "123456",
                    "recvAccountName": "长帆开票测试",
                    "recvAccountNo": "123456",
                    "recvAcountId": 0,
                    "recvBankAccountId": 0,
                    "recvBankBranch": "",
                    "recvBankCode": "",
                    "recvBankName": "",
                    "refundCurrency": "CNY",
                    "refundType": "overpayment",
                    "refuseReason": "",
                    "remark": "退款说明",
                    "settleCompCode": "cus000001",
                    "settleCompName": "长帆开票测试",
                    "state": "valid",
                    "transferChargeType": "customer",
                    "transferCharger": "1",
                    "transferFeeAmt": 100.00,
                    "transferFeeCurrency": "CNY",
                    "trustFileId": 1,
                    "updatedBy": 0,
                    "updatedName": "刘昌杰",
                    "updatedTime": "2020-12-30 12:40:06"
                },
            ],
            "pageSize": 5,
            "totalCount": 1,
            "totalPage": 1
        },
        "msg": "success"
    }
}