module.exports = (prams) => {
    return {
        "code": 0,
        "data": [
            {
                "boxNo": 1,
                "cargoId": 1,
                "cn": "22222",
                "cname": "餐盘",
                "containerId": 309,
                "itemId": 13,
                "mark": "唛头",
                "packageType": "袋",
                "quantity": 2,
                "volume": 2,
                "weight": 2,
                "lastQuantity": 111,
                "lastWeight": 111,
                "lastVolume": 111,
                "whName": '财务室',
                "whid": 1,
                "batchNo": 111,
            },
            {
                "boxNo": 3,
                "cargoId": 3,
                "cn": "222223",
                "cname": "餐盘3",
                "containerId": 339,
                "itemId": 133,
                "mark": "唛头3",
                "packageType": "袋",
                "quantity": 3,
                "volume": 3,
                "weight": 3,
                "lastQuantity": 113,
                "lastWeight": 113,
                "lastVolume": 113,
                "whName": '财务室3',
                "whid": 3,
                "batchNo": 113,
            },
            {
                "boxNo": 2,
                "cargoId": 1,
                "cn": "22222",
                "cname": "餐盘",
                "containerId": 309,
                "itemId": 144,
                "mark": "唛头",
                "packageType": "袋",
                "quantity": 23,
                "volume": 2,
                "weight": 2,
                "lastQuantity": 22,
                "lastWeight": 22,
                "lastVolume": 23,
                "whName": '财务室22',
                "whid": 12,
                "batchNo": 111,
            }
        ],
        "msg": "success"
    }
}