module.exports = (params) => {
    return {
        "code": 0,
        "data": {
            "allColumns": [
                "bdEmployeeName",
                "orderNo",
                "auditEmployeeName",
                "bkgReqNo",
                "bkgEmployeeId",
                "bizDate",
                "auditEmployeeId",
                "podPortCode",
                "launchEmployeeName",
                "bkgStatus",
                "launchEmployeeId",
                "obdEmployeeName",
                "cargoSource",
                "carrierCode",
                "polPortCode",
                "bkgEmployeeName",
                "businessType",
                "porPortCode"
            ],
            "configColumns": ['bkgReqNo','orderNo', 'bkgStatus', 'shipCarrierCode',  'shipRefNo', 'cyCutOff'],
            "currPage": 1,
            "list": [
                {
                    "auditEmployeeId": 0,
                    "auditEmployeeName": "",
                    "bdEmployeeName": "张三",
                    "bizDate": "2020-08-10",
                    "bkgEmployeeId": 0,
                    "bkgEmployeeName": 0,
                    "bkgReqNo": "BKG2020081100020",
                    "bkgStatus": "",
                    "businessType": "BT01",
                    "cargoSource": "",
                    "carrierCode": "123123",
                    "launchEmployeeId": 0,
                    "launchEmployeeName": 0,
                    "obdEmployeeName": "",
                    "orderNo": "",
                    "podPortCode": "",
                    "polPortCode": "",
                    "porPortCode": ""
                },
                {
                    "auditEmployeeId": 0,
                    "auditEmployeeName": "",
                    "bdEmployeeName": "张三",
                    "bizDate": "2020-08-10",
                    "bkgEmployeeId": 0,
                    "bkgEmployeeName": 0,
                    "bkgReqNo": "BKG2020081100021",
                    "bkgStatus": "",
                    "businessType": "BT01",
                    "cargoSource": "",
                    "carrierCode": "123123",
                    "launchEmployeeId": 0,
                    "launchEmployeeName": 0,
                    "obdEmployeeName": "",
                    "orderNo": "S202008100000392",
                    "podPortCode": "",
                    "polPortCode": "",
                    "porPortCode": ""
                },
                {
                    "auditEmployeeId": 0,
                    "auditEmployeeName": "",
                    "bdEmployeeName": "张三",
                    "bizDate": "2020-08-10",
                    "bkgEmployeeId": 0,
                    "bkgEmployeeName": 0,
                    "bkgReqNo": "BKG2020081100022",
                    "bkgStatus": "",
                    "businessType": "BT01",
                    "cargoSource": "",
                    "carrierCode": "123123",
                    "launchEmployeeId": 0,
                    "launchEmployeeName": 0,
                    "obdEmployeeName": "",
                    "orderNo": "S202008100000393",
                    "podPortCode": "",
                    "polPortCode": "",
                    "porPortCode": ""
                }
            ],
            "pageSize": 10,
            "totalCount": 3,
            "totalPage": 1
        },
        "msg": "success"
    }
}