module.exports = (params) => {
    return {
        "code": 0,
        "data": {
            "allColumns": [
                "polEname",
                "endDate",
                "transitPort3Ename",
                "feederMatchMode",
                "publishDate",
                "allin",
                "sailingDate",
                "bkgAgent",
                "effectiveType",
                "transitPort2Ename",
                "freeTimeDesc",
                "shipCarrierCode",
                "priceGp20",
                "podCode",
                "state",
                "podCountryName",
                "externalDesc",
                "carrierService",
                "surchargeList",
                "blankSailing",
                "polCname",
                "recommendLevel",
                "voyage",
                "pricerName",
                "guidanceDesc",
                "feederRouteId",
                "sysLineCode",
                "weightDesc",
                "transitPort3Cname",
                "publisher",
                "transitPort1Ename",
                "shipTerms",
                "transitPort1Cname",
                "sameFlagCode",
                "feederPolCname",
                "podCityName",
                "priceGp40",
                "cargoLimited",
                "podEname",
                "routeId",
                "pricerDeptCode",
                "surchargeDesc",
                "internalDesc",
                "pricer",
                "transitVoyage",
                "polCityName",
                "feederPolEname",
                "feederPolCode",
                "priceHq40",
                "cutoffDate",
                "polCode",
                "blType",
                "beginDate",
                "schedule",
                "issueWay",
                "transitPort2Cname",
                "priceHq45",
                "podCname",
                "attention",
                "subRouteList",
                "carrierLineName"
            ],
            "configColumns": [
                "priceGp20",
                "priceGp40",
                "priceHq40",
                "priceHq45",
                "attention",
                "effectiveType",
                "schedule",
                "transitPortEname",
                "beginDate",
                "polCode",
                "polEname",
                "polCname",
                'podCode',
                'podEname',
                'podCname',
                'currency',
                'priceGp20',
                'currency',
                'priceGp40',
                'weightCurrency',
                'weightPriceGp40',
                'weightCurrency',
                'weightPriceGp20',
                "state",
                "externalDesc",
                "carrierService",
                "surchargeList",
                "shipCarrierCode",
                "issueWay"
            ],
            "currPage": 1,
            "list": [
                {
                    "billType": "operating_loss",
                    "createdBy": 22,
                    "createdName": "q",
                    "createdTime": "2020-10-10 17:16:51",
                    "departNo": "",
                    "employeeId": 0,
                    "employeeName": "",
                    "finBillId": 1,
                    "finBillNo": "123",
                    "ownerCompCode": "w",
                    "ownerCompName": "ewew",
                    "payMap": {
                        "USD": 2400,
                        "CNY": 6000
                    },
                    "receiveMap": {
                        "USD": 12400,
                        "CNY": 16000
                    },
                    "remark": "ewewe",
                    "revision": 0,
                    "settleOrderNo": "",
                    "state": "",
                    "updatedBy": 0,
                    "updatedName": "",
                    "updatedTime": null
                },
                {
                    "billType": "operating_loss",
                    "createdBy": 22,
                    "createdName": "q",
                    "createdTime": "2020-10-10 17:16:51",
                    "departNo": "",
                    "employeeId": 0,
                    "employeeName": "",
                    "finBillId": 1,
                    "finBillNo": "123",
                    "ownerCompCode": "w",
                    "ownerCompName": "ewew",
                    "payMap": {
                        "USD": 2400,
                        "CNY": 6000
                    },
                    "receiveMap": {
                        "USD": 12400,
                        "CNY": 16000
                    },
                    "remark": "ewewe",
                    "revision": 0,
                    "settleOrderNo": "",
                    "state": "",
                    "updatedBy": 0,
                    "updatedName": "",
                    "updatedTime": null
                }
            ],
            "pageSize": 10,
            "totalCount": 1,
            "totalPage": 1
        },
        "msg": "success"
    }
}