module.exports = (prams) => {
    return {
        "code": 0,
        "data": {
            "allColumns": [
                "polEname",
                "endDate",
                "transitPort3Ename",
                "feederMatchMode",
                "publishDate",
                "allin",
                "sailingDate",
                "bkgAgent",
                "effectiveType",
                "transitPort2Ename",
                "freeTimeDesc",
                "shipCarrierCode",
                "priceGp20",
                "podCode",
                "state",
                "podCountryName",
                "publishStatus",
                "externalDesc",
                "carrierService",
                "surchargeList",
                "blankSailing",
                "polCname",
                "recommendLevel",
                "voyage",
                "pricerName",
                "guidanceDesc",
                "feederRouteId",
                "sysLineCode",
                "weightDesc",
                "transitPort3Cname",
                "publisher",
                "transitPort1Ename",
                "shipTerms",
                "transitPort1Cname",
                "sameFlagCode",
                "feederPolCname",
                "podCityName",
                "priceGp40",
                "cargoLimited",
                "podEname",
                "routeId",
                "pricerDeptCode",
                "surchargeDesc",
                "internalDesc",
                "pricer",
                "transitVoyage",
                "polCityName",
                "feederPolEname",
                "feederPolCode",
                "priceHq40",
                "cutoffDate",
                "polCode",
                "blType",
                "beginDate",
                "schedule",
                "issueWay",
                "transitPort2Cname",
                "priceHq45",
                "podCname",
                "attention",
                "subRouteList",
                "carrierLineName"
            ],
            "configColumns": [],
            "currPage": 1,
            "list": [
                {
                    "allin": "allin",
                    "rowKey": "1232134",
                    "attention": "",
                    "beginDate": "2018-12-13",
                    "bkgAgent": "",
                    "blType": "",
                    "blankSailing": "",
                    "cargoLimited": "",
                    "carrierLineName": "",
                    "carrierService": "",
                    "cutoffDate": "",
                    "effectiveType": "cutoff_time",
                    "endDate": "2022-04-30",
                    "externalDesc": "",
                    "feederMatchMode": "none",
                    "feederPolCname": "",
                    "feederPolCode": "",
                    "feederPolEname": "",
                    "feederRouteId": 0,
                    "freeTimeDesc": "",
                    "guidanceDesc": "",
                    "internalDesc": "",
                    "issueWay": "",
                    "podCityName": "",
                    "podCname": "阿德雷德",
                    "podCode": "AUADE",
                    "podCountryName": "",
                    "podEname": "ADELAIDE",
                    "polCityName": "",
                    "polCname": "香港",
                    "polCode": "CNHKG",
                    "polEname": "HONG KONG",
                    "priceGp20": 340,
                    "priceGp40": 680,
                    "priceHq40": 680,
                    "priceHq45": 340,
                    "pricer": "",
                    "pricerDeptCode": "",
                    "pricerName": "",
                    "publishDate": "2020-08-03",
                    "publishStatus": "published",
                    "publisher": "张三",
                    "recommendLevel": "",
                    "routeId": 2,
                    "sailingDate": null,
                    "sameFlagCode": "CNHKGAUADEONEAXXUSD340.0000680.0000680.0000340.0000",
                    "schedule": "6/1",
                    "shipCarrierCode": "ONE",
                    "shipTerms": "CY/CY",
                    "state": "valid",
                    "subRouteList": [],
                    "surchargeDesc": "",
                    "surchargeList": [
                        {
                            "chargeCode": "DOC",
                            "chargeName": "文件费",
                            "chargeMode": "basePrice",
                            "chargeType": "起运港LOCAL",
                            "createdBy": 0,
                            "createdTime": null,
                            "currency": "USD",
                            "oid": 3,
                            "payMode": "预付",
                            "price": 52.3,
                            "priceGp20": '',
                            "priceGp40": '',
                            "priceHq40": '',
                            "priceHq45": '',
                            "rateUnit": "箱",
                            "state": "valid",
                            "templateId": 2,
                            "updatedBy": 0,
                            "updatedTime": null
                        },
                        {
                            "chargeCode": "SEAL",
                            "chargeName": "封条费",
                            "chargeMode": "basePrice",
                            "chargeType": "目的港LOCAL",
                            "createdBy": 0,
                            "createdTime": null,
                            "currency": "USD",
                            "oid": 3,
                            "payMode": "到付",
                            "price": 52.3,
                            "priceGp20": 45,
                            "priceGp40": 45,
                            "priceHq40": 45,
                            "priceHq45": 45,
                            "rateUnit": "箱型",
                            "state": "valid",
                            "templateId": 2,
                            "updatedBy": 0,
                            "updatedTime": null
                        },
                        {
                            "chargeCode": "GKABF",
                            "chargeName": "港口安保费",
                            "chargeMode": "basePrice",
                            "chargeType": "运费附加费",
                            "createdBy": 0,
                            "createdTime": null,
                            "currency": "ASP",
                            "oid": 4,
                            "payMode": "无限制",
                            "price": 521.3,
                            "priceGp20": 121.2,
                            "priceGp40": 43,
                            "priceHq40": 23,
                            "priceHq45": 43,
                            "rateUnit": "票",
                            "state": "valid",
                            "templateId": 2,
                            "updatedBy": 0,
                            "updatedTime": null
                        }
                    ],
                    "sysLineCode": "AXX",
                    "transitPort1Cname": "",
                    "transitPort1Ename": "",
                    "transitPort2Cname": "",
                    "transitPort2Ename": "",
                    "transitPort3Cname": "",
                    "transitPort3Ename": "",
                    "transitVoyage": 0,
                    "voyage": 0,
                    "weightDesc": ""
                },
                {
                    "allin": "allin",
                    "rowKey": "1233",
                    "attention": "",
                    "beginDate": "2018-12-13",
                    "bkgAgent": "",
                    "blType": "",
                    "blankSailing": "",
                    "cargoLimited": "",
                    "carrierLineName": "",
                    "carrierService": "",
                    "cutoffDate": "",
                    "effectiveType": "cutoff_time",
                    "endDate": "2022-04-30",
                    "externalDesc": "",
                    "feederMatchMode": "none",
                    "feederPolCname": "",
                    "feederPolCode": "",
                    "feederPolEname": "",
                    "feederRouteId": 0,
                    "freeTimeDesc": "",
                    "guidanceDesc": "",
                    "internalDesc": "",
                    "issueWay": "",
                    "podCityName": "",
                    "podCname": "阿德雷德",
                    "podCode": "AUADE",
                    "podCountryName": "",
                    "podEname": "ADELAIDE",
                    "polCityName": "",
                    "polCname": "香港",
                    "polCode": "CNHKG",
                    "polEname": "HONG KONG",
                    "priceGp20": 340,
                    "priceGp40": 680,
                    "priceHq40": 680,
                    "priceHq45": 340,
                    "pricer": "",
                    "pricerDeptCode": "",
                    "pricerName": "",
                    "publishDate": "2020-08-03",
                    "publishStatus": "published",
                    "publisher": "张三",
                    "recommendLevel": "",
                    "routeId": 6,
                    "sailingDate": null,
                    "sameFlagCode": "CNHKGAUADEONEAXXUSD340.0000680.0000680.0000340.0000",
                    "schedule": "6/1",
                    "shipCarrierCode": "ONE",
                    "shipTerms": "CY/CY",
                    "state": "valid",
                    "subRouteList": [
                        {
                            "allin": "allin",
                            "rowKey": "199",
                            "attention": "",
                            "beginDate": "2018-12-13",
                            "bkgAgent": "",
                            "blType": "",
                            "blankSailing": "",
                            "cargoLimited": "",
                            "carrierLineName": "",
                            "carrierService": "",
                            "cutoffDate": "",
                            "effectiveType": "cutoff_time",
                            "endDate": "2022-04-30",
                            "externalDesc": "",
                            "feederMatchMode": "none",
                            "feederPolCname": "",
                            "feederPolCode": "",
                            "feederPolEname": "",
                            "feederRouteId": 0,
                            "freeTimeDesc": "",
                            "guidanceDesc": "",
                            "internalDesc": "",
                            "issueWay": "",
                            "podCityName": "",
                            "podCname": "阿德雷德",
                            "podCode": "AUADE",
                            "podCountryName": "",
                            "podEname": "ADELAIDE",
                            "polCityName": "",
                            "polCname": "香港",
                            "polCode": "CNHKG",
                            "polEname": "HONG KONG",
                            "priceGp20": 340,
                            "priceGp40": 680,
                            "priceHq40": 680,
                            "priceHq45": 340,
                            "pricer": "",
                            "pricerDeptCode": "",
                            "pricerName": "",
                            "publishDate": "2020-08-03",
                            "publishStatus": "published",
                            "publisher": "张三",
                            "recommendLevel": "",
                            "routeId": 5,
                            "sailingDate": null,
                            "sameFlagCode": "CNHKGAUADEONEAXXUSD340.0000680.0000680.0000340.0000",
                            "schedule": "6/1",
                            "shipCarrierCode": "ONE",
                            "shipTerms": "CY/CY",
                            "state": "valid",
                            "subRouteList": [],
                            "surchargeDesc": "",
                            "surchargeList": [],
                            "sysLineCode": "AXX",
                            "transitPort1Cname": "",
                            "transitPort1Ename": "",
                            "transitPort2Cname": "",
                            "transitPort2Ename": "",
                            "transitPort3Cname": "",
                            "transitPort3Ename": "",
                            "transitVoyage": 0,
                            "voyage": 0,
                            "weightDesc": ""
                        }
                    ],
                    "surchargeDesc": "",
                    "surchargeList": [],
                    "sysLineCode": "AXX",
                    "transitPort1Cname": "",
                    "transitPort1Ename": "",
                    "transitPort2Cname": "",
                    "transitPort2Ename": "",
                    "transitPort3Cname": "",
                    "transitPort3Ename": "",
                    "transitVoyage": 0,
                    "voyage": 0,
                    "weightDesc": ""
                },
                {
                    "allin": "allin",
                    "rowKey": "12123433",
                    "attention": "",
                    "beginDate": "2018-12-13",
                    "bkgAgent": "",
                    "blType": "",
                    "blankSailing": "",
                    "cargoLimited": "",
                    "carrierLineName": "",
                    "carrierService": "",
                    "cutoffDate": "",
                    "effectiveType": "cutoff_time",
                    "endDate": "2022-04-30",
                    "externalDesc": "",
                    "feederMatchMode": "none",
                    "feederPolCname": "",
                    "feederPolCode": "",
                    "feederPolEname": "",
                    "feederRouteId": 0,
                    "freeTimeDesc": "",
                    "guidanceDesc": "",
                    "internalDesc": "",
                    "issueWay": "",
                    "podCityName": "",
                    "podCname": "阿德雷德",
                    "podCode": "AUADE",
                    "podCountryName": "",
                    "podEname": "ADELAIDE",
                    "polCityName": "",
                    "polCname": "香港",
                    "polCode": "CNHKG",
                    "polEname": "HONG KONG",
                    "priceGp20": 340,
                    "priceGp40": 680,
                    "priceHq40": 680,
                    "priceHq45": 340,
                    "pricer": "",
                    "pricerDeptCode": "",
                    "pricerName": "",
                    "publishDate": "2020-08-03",
                    "publishStatus": "published",
                    "publisher": "张三",
                    "recommendLevel": "",
                    "routeId": 6,
                    "sailingDate": null,
                    "sameFlagCode": "CNHKGAUADEONEAXXUSD340.0000680.0000680.0000340.0000",
                    "schedule": "6/1",
                    "shipCarrierCode": "ONE",
                    "shipTerms": "CY/CY",
                    "state": "valid",
                    "subRouteList": [
                    ],
                    "surchargeDesc": "",
                    "surchargeList": [],
                    "sysLineCode": "AXX",
                    "transitPort1Cname": "",
                    "transitPort1Ename": "",
                    "transitPort2Cname": "",
                    "transitPort2Ename": "",
                    "transitPort3Cname": "",
                    "transitPort3Ename": "",
                    "transitVoyage": 0,
                    "voyage": 0,
                    "weightDesc": ""
                },
                {
                    "allin": "allin",
                    "rowKey": "1212333",
                    "attention": "",
                    "beginDate": "2018-12-13",
                    "bkgAgent": "",
                    "blType": "",
                    "blankSailing": "",
                    "cargoLimited": "",
                    "carrierLineName": "",
                    "carrierService": "",
                    "cutoffDate": "",
                    "effectiveType": "cutoff_time",
                    "endDate": "2022-04-30",
                    "externalDesc": "",
                    "feederMatchMode": "none",
                    "feederPolCname": "",
                    "feederPolCode": "",
                    "feederPolEname": "",
                    "feederRouteId": 0,
                    "freeTimeDesc": "",
                    "guidanceDesc": "",
                    "internalDesc": "",
                    "issueWay": "",
                    "podCityName": "",
                    "podCname": "阿德雷德",
                    "podCode": "AUADE",
                    "podCountryName": "",
                    "podEname": "ADELAIDE",
                    "polCityName": "",
                    "polCname": "香港",
                    "polCode": "CNHKG",
                    "polEname": "HONG KONG",
                    "priceGp20": 340,
                    "priceGp40": 680,
                    "priceHq40": 680,
                    "priceHq45": 340,
                    "pricer": "",
                    "pricerDeptCode": "",
                    "pricerName": "",
                    "publishDate": "2020-08-03",
                    "publishStatus": "published",
                    "publisher": "张三",
                    "recommendLevel": "",
                    "routeId": 6,
                    "sailingDate": null,
                    "sameFlagCode": "CNHKGAUADEONEAXXUSD340.0000680.0000680.0000340.0000",
                    "schedule": "6/1",
                    "shipCarrierCode": "ONE",
                    "shipTerms": "CY/CY",
                    "state": "valid",
                    "subRouteList": [
                        {
                            "allin": "allin",
                            "rowKey": "192319",
                            "attention": "",
                            "beginDate": "2018-12-13",
                            "bkgAgent": "",
                            "blType": "",
                            "blankSailing": "",
                            "cargoLimited": "",
                            "carrierLineName": "",
                            "carrierService": "",
                            "cutoffDate": "",
                            "effectiveType": "cutoff_time",
                            "endDate": "2022-04-30",
                            "externalDesc": "",
                            "feederMatchMode": "none",
                            "feederPolCname": "",
                            "feederPolCode": "",
                            "feederPolEname": "",
                            "feederRouteId": 0,
                            "freeTimeDesc": "",
                            "guidanceDesc": "",
                            "internalDesc": "",
                            "issueWay": "",
                            "podCityName": "",
                            "podCname": "阿德雷德",
                            "podCode": "AUADE",
                            "podCountryName": "",
                            "podEname": "ADELAIDE",
                            "polCityName": "",
                            "polCname": "香港",
                            "polCode": "CNHKG",
                            "polEname": "HONG KONG",
                            "priceGp20": 340,
                            "priceGp40": 680,
                            "priceHq40": 680,
                            "priceHq45": 340,
                            "pricer": "",
                            "pricerDeptCode": "",
                            "pricerName": "",
                            "publishDate": "2020-08-03",
                            "publishStatus": "published",
                            "publisher": "张三",
                            "recommendLevel": "",
                            "routeId": 5,
                            "sailingDate": null,
                            "sameFlagCode": "CNHKGAUADEONEAXXUSD340.0000680.0000680.0000340.0000",
                            "schedule": "6/1",
                            "shipCarrierCode": "ONE",
                            "shipTerms": "CY/CY",
                            "state": "valid",
                            "subRouteList": [],
                            "surchargeDesc": "",
                            "surchargeList": [],
                            "sysLineCode": "AXX",
                            "transitPort1Cname": "",
                            "transitPort1Ename": "",
                            "transitPort2Cname": "",
                            "transitPort2Ename": "",
                            "transitPort3Cname": "",
                            "transitPort3Ename": "",
                            "transitVoyage": 0,
                            "voyage": 0,
                            "weightDesc": ""
                        }
                    ],
                    "surchargeDesc": "",
                    "surchargeList": [],
                    "sysLineCode": "AXX",
                    "transitPort1Cname": "",
                    "transitPort1Ename": "",
                    "transitPort2Cname": "",
                    "transitPort2Ename": "",
                    "transitPort3Cname": "",
                    "transitPort3Ename": "",
                    "transitVoyage": 0,
                    "voyage": 0,
                    "weightDesc": ""
                },
            ],
            "pageSize": 1,
            "totalCount": 7,
            "totalPage": 7
        },
        "msg": "success"
    }
};