module.exports = (prams) => {
    return {
        "code": 0,
        "data": {
            "allColumns": [],
            "configColumns": [],
            "currPage": 1,
            "list": [
                {
                    "cname": "",
                    "createdBy": 8,
                    "createdName": "",
                    "createdTime": "2020-08-26T15:40:35",
                    "deliveryContact": "俊妹妹",
                    "deliveryContactPhone": "13480691607",
                    "deliveryCustName": "科技公司1",
                    "deliveryCustid": 1,
                    "inRemark": "备注",
                    "oid": 1,
                    "planNo": "12347",
                    "positionNo": "134564568",
                    "planEnterTime": "2020-08-26",
                    "totalQuantity": 100,
                    "totalVolume": 100,
                    "totalWeight": 100,
                    "updatedBy": 0,
                    "updatedName": "",
                    "updatedTime": null,
                    "warehouseInplanItems": [{
                        "cargoId": 1,
                        "cargoVo": {
                            "cargoId": 1,
                            "cname": "小猫",
                            "ename": "cat",
                            "hscode": "16413245643165341",
                            "mark": "www",
                            "status": "1"
                        },
                        "createdBy": 0,
                        "createdName": "",
                        "createdTime": "2020-08-26T15:40:35",
                        "oid": 2,
                        "packageType": "bag",
                        "planNo": "12347",
                        "quantity": 100,
                        "updatedBy": 0,
                        "updatedName": "",
                        "updatedTime": null,
                        "lastQuantity": 120,
                        "lastVolume": 120,
                        "lastWeight": 120,
                        "volume": 100,
                        "weight": 100
                    },
                    {
                        "cargoId": 2,
                        "cargoVo": {
                            "cargoId": 2,
                            "cname": "小狗",
                            "ename": "cat",
                            "hscode": "16413245643165341",
                            "mark": "eee",
                            "status": "2"
                        },
                        "createdBy": 0,
                        "createdName": "",
                        "createdTime": "2020-08-26T15:40:35",
                        "oid": 3,
                        "packageType": "bag",
                        "planNo": "12347",
                        "quantity": 100,
                        "updatedBy": 0,
                        "updatedName": "",
                        "updatedTime": null,
                        "volume": 100,
                        "weight": 100
                    }],
                    "warehouseName": "测试必须的",
                    "status":"no", //字典：warehouse_inplan_status
                    "createdBy": 8,
                    "whId": 1
                },
                {
                    "cname": "",
                    "createdBy": 8,
                    "createdName": "",
                    "createdTime": "2020-08-26T15:40:35",
                    "deliveryContact": "俊妹妹",
                    "deliveryContactPhone": "13480691607",
                    "deliveryCustName": "科技公司1",
                    "deliveryCustid": 2,
                    "inRemark": "备注",
                    "oid": 2,
                    "planNo": "567890",
                    "positionNo": "134564568",
                    "planEnterTime": "2020-08-26",
                    "totalQuantity": 100,
                    "totalVolume": 100,
                    "totalWeight": 100,
                    "updatedBy": 0,
                    "updatedName": "",
                    "updatedTime": null,
                    "warehouseInplanItems": [{
                        "cargoId": 1,
                        "cargoVo": {
                            "cargoId": 1,
                            "cname": "小猫",
                            "ename": "cat",
                            "hscode": "16413245643165341",
                            "mark": "www",
                            "status": "1"
                        },
                        "createdBy": 0,
                        "createdName": "",
                        "createdTime": "2020-08-26T15:40:35",
                        "oid": 2,
                        "packageType": "bag",
                        "planNo": "12347",
                        "quantity": 100,
                        "updatedBy": 0,
                        "updatedName": "",
                        "updatedTime": null,
                        "lastQuantity": 120,
                        "lastVolume": 120,
                        "lastWeight": 120,
                        "volume": 100,
                        "weight": 100
                    },
                    {
                        "cargoId": 2,
                        "cargoVo": {
                            "cargoId": 2,
                            "cname": "小狗",
                            "ename": "cat",
                            "hscode": "16413245643165341",
                            "mark": "eee",
                            "status": "2"
                        },
                        "createdBy": 0,
                        "createdName": "",
                        "createdTime": "2020-08-26T15:40:35",
                        "oid": 3,
                        "packageType": "bag",
                        "planNo": "12347",
                        "quantity": 100,
                        "updatedBy": 0,
                        "updatedName": "",
                        "updatedTime": null,
                        "volume": 100,
                        "weight": 100
                    }],
                    "warehouseName": "测试必须的",
                    "status":"no", //字典：warehouse_inplan_status
                    "createdBy": 8,
                    "whId": 1
                }
            ],
            "pageSize": 10,
            "totalCount": 2,
            "totalPage": 1
        },
        "msg": "success"
    }
}