module.exports = (params) => {
  return {
    "code": 0,
    "data": {
        "allColumns": [
            "consignerName",
            "settleAmt",
            "dueDate",
            "feeId",
            "sourceBizNo",
            "bizAmt",
            "acctExRate",
            "feeAmtWithTax",
            "viewGroupType",
            "confirmStatus",
            "createdTime",
            "feeEnName",
            "rivalCode",
            "taxAmt",
            "gedgingWriteoffAmt",
            "ownerCompName",
            "unitPrice",
            "acctExRateId",
            "settleCorpCode",
            "settleCompName",
            "confirmBy",
            "invoiceReplenishAmt",
            "unitCount",
            "gedgingAmt",
            "confirmTime",
            "agencyNo",
            "feeAmt",
            "basicCurrency",
            "invoiceAmt",
            "taxRate",
            "sourceType",
            "precloseStatus",
            "transAcctVoucherNo",
            "isIssueInvoice",
            "settleLock",
            "feeCname",
            "closeStatus",
            "serviceCode",
            "settleStatus",
            "bizDate",
            "ownerCompCode",
            "settleCorpName",
            "remark",
            "isWithTax",
            "settleCloseTime",
            "finDate",
            "transAcctTime",
            "feeCode",
            "closeTime",
            "currency",
            "createdName",
            "invoiceApplyAmt",
            "basicMoneyAmt",
            "intraStatus",
            "gedgingStatus",
            "precloseTime",
            "feeUnit",
            "receipayType",
            "serviceName",
            "lockReason",
            "confirmName",
            "totalWriteoffAmt",
            "consignerCode",
            "settleCycle",
            "settleApplyAmt",
            "reviseStatus",
            "settleCompCode",
            "prepayType",
            "jointStatus"
        ],
        "configColumns": [],
        "currPage": 1,
        "list": [
            {
                "acctExRate": 6.7872,
                "closeStatus": "no",
                "closeTime": "",
                "confirmName": "",
                "confirmStatus": "no",
                "confirmTime": null,
                "consignerCode": "code111",
                "consignerName": "测试客户1",
                "createdName": "黄黄",
                "createdTime": "2020-09-22 16:32:20",
                "currency": "USD",
                "dueDate": null,
                "feeAmt": 10000,
                "feeCode": "truck001",
                "feeEnName": "truck001",
                "feeId": 13,
                "feeName": "拖车费",
                "feeUnit": "UNIT",
                "finDate": "2020-09-21 00:00:00",
                "finGroup": "",
                "gedgingApplyAmt": 0,
                "gedgingStatus": "no",
                "gedgingWriteoffAmt": 0,
                "intraStatus": "no",
                "invoiceAmt": 0,
                "invoiceApplyAmt": 0,
                "invoiceReplenishAmt": 0,
                "isIssueInvoice": "",
                "jointStatus": "no",
                "lockReason": "",
                "mergeFeeCode": "",
                "mergeFeeName": "",
                "orderFeeId": 0,
                "precloseStatus": "no",
                "precloseTime": "",
                "prepayType": "prepay",
                "priceWithTax": "",
                "profitType": "",
                "receipayType": "receive",
                "remark": "拖车费用备注说明",
                "reviseStatus": "no",
                "serviceCode": "truck",
                "serviceName": "",
                "settleAmt": 0,
                "settleApplyAmt": 0,
                "settleCloseTime": "",
                "settleCompCode": "000001",
                "settleCompName": "深圳分公司",
                "settleCorpCode": "code111",
                "settleCorpName": "测试客户1",
                "settleCycle": "ticket",
                "settleLock": "unlock",
                "settleStatus": "nofinish",
                "sourceBizNo": "",
                "sourceType": "order",
                "taxRate": 6,
                "totalWriteoffAmt": 0,
                "transAcctVoucherNo": "",
                "unitCount": 1,
                "unitPrice": 10000,
                "viewGroupType": "biz"
            }
        ],
        "pageSize": 10,
        "totalCount": 55,
        "totalPage": 6
    },
    "msg": "success"
  }
}