module.exports = (params) => {
  return {
    "code": 0,
    "data": {
      "allColumns": [
      ],
      "configColumns": [
      ],
      "list":[
        {
          "orderFeeId":1,
          "settleCompCode":"结算的分公司编码",
          "settleCompName":"结算的分公司名称",
          "consignerCode":"委托人编码",
          "consignerName":"委托人名称",
          "settleCorpCode":"结算单位编码",
          "settleCorpName":"结算单位名称",
          "settleCycle":"ticket",
          "serviceCode":"服务编码",
          "serviceName":"海运订舱",
          "feeCode":"seafee",
          "feeName":"海运费",
          "feeEnName":"seafee",
          "receipayType":"pay",
          "viewGroupType":"biz",
          "finGroup":"incomecost",
          "prepayType":"prepay",
          "feeAmt":100.00,
          "feeUnit":"bill",
          "unitPrice":100.00,
          "unitCount":1,
          "currency":"USD",
          "taxRate":6.00,
          "priceWithTax":"yes",
          "acctExRate":1,
          "settleLock":"no",
          "lockReason":"结算锁定",
          "settleApplyAmt":0.00,
          "settleAmt":0.00,
          "gedgingApplyAmt":0.00,
          "gedgingWriteoffAmt":0.00,
          "gedgingStatus":"no",
          "totalWriteoffAmt":0.00,
          "invoiceApplyAmt":0.00,
          "invoiceAmt":0.00,
          "invoiceReplenishAmt":0.00,
          "settleStatus":"no",
          "settleCloseTime":null,
          "intraStatus":"yes",
          "jointStatus":"yes",
          "remark":"备注",
          "finDate":"2020-09-20",
          "dueDate":"2020-10-20",
          "reviseStatus":"no",
          "precloseStatus":"no",
          "precloseTime":null,
          "closeStatus":"no",
          "closeTime":"",
          "confirmStatus":"yes",
          "confirmName":"某某某",
          "confirmTime":"2020-09-20",
          "transAcctVoucherNo":"12344",
          "createdName":"某某某",
          "createdTime":"2020-09-20",
          "profitType":"yes",
          "settleOrderNos": 's123456',
          "writeoffNos": 'w123456',
          "settleTimes": 'st123456'
        },
        {
          "orderFeeId":2,
          "settleCorpCode":"结算单位编码",
          "settleCorpName":"结算单位名称",
          "feeCode":"费用编码",
          "feeAmt":10000,
          "currency":"CNY",
          "remark":"备注说明",
          "receipayType":"receive",
          "serviceCode":"服务编码",
          "serviceName":"海运订舱",
          "settleOrderNos": 's123456',
          "writeoffNos": 'w123456',
          "settleTimes": 'st123456'
         }
      ]
    }
  }
}