module.exports = (prams) => {
    return {
        "code":0,
        "msg":"success",
        "data":[
            {
                "blNo": "bl_001",
                "createdBy": 0,
                "createdName": "",
                "createdTime": null,
                "docId": 1,
                "docName": "trade",
                "docNo": "doc123",
                "docType": "trade",
                "documentFiles": [
                    {
                        "createdBy": 0,
                        "createdName": "",
                        "createdTime": null,
                        "docId": 1,
                        "fileNo": "xxx",
                        "oid": 1,
                        "revision": 1,
                        "state": "valid",
                        "updatedBy": 0,
                        "updatedName": "",
                        "updatedTime": null,
                        "url": "暂时设置空"
                    }
                ],
                "documentStatus": {
                    "createdBy": 0,
                    "createdName": "",
                    "createdTime": null,
                    "docId": 1,
                    "oid": 1,
                    "postFinishTime": null,
                    "postStatus": "",
                    "retrieveFinishTime": "2020-09-12T16:04:33",
                    "retrieveStatus": "finish",
                    "revision": 1,
                    "state": "valid",
                    "updatedBy": 0,
                    "updatedName": "",
                    "updatedTime": null
                },
                "orderNo": "hello_003",
                "remark": "注意了哈",
                "revision": 1,
                "shDocumentData": null,
                "state": "valid",
                "updatedBy": 0,
                "updatedName": "",
                "updatedTime": null
            },
            {
                "blNo": "bl_002",
                "createdBy": 0,
                "createdName": "",
                "createdTime": null,
                "docId": 2,
                "docName": "certificate",
                "docNo": "doc1234",
                "docType": "certificate",
                "documentFiles": [
                    {
                        "createdBy": 0,
                        "createdName": "",
                        "createdTime": null,
                        "docId": 2,
                        "fileNo": "xxxxxxxxxxx",
                        "oid": 2,
                        "revision": 1,
                        "state": "valid",
                        "updatedBy": 0,
                        "updatedName": "",
                        "updatedTime": null,
                        "url": "yyyyyyyyyy"
                    }
                ],
                "documentStatus": {
                    "createdBy": 0,
                    "createdName": "",
                    "createdTime": null,
                    "docId": 2,
                    "oid": 2,
                    "postFinishTime": null,
                    "postStatus": "",
                    "retrieveFinishTime": "2020-09-12 19:24:07",
                    "retrieveStatus": "finish",
                    "revision": 1,
                    "state": "valid",
                    "updatedBy": 0,
                    "updatedName": "",
                    "updatedTime": null
                },
                "orderNo": "hello_004",
                "remark": "登记反馈",
                "revision": 1,
                "shDocumentData": null,
                "state": "valid",
                "updatedBy": 0,
                "updatedName": "",
                "updatedTime": null
            },
            {
                "blNo": "bl_003",
                "createdBy": 0,
                "createdName": "",
                "createdTime": null,
                "docId": 3,
                "docName": "guarantee",
                "docNo": "doc3",
                "docType": "guarantee",
                "documentFiles": [
                    {
                        "createdBy": 0,
                        "createdName": "",
                        "createdTime": null,
                        "docId": 3,
                        "fileNo": "333333333",
                        "oid": 3,
                        "revision": 1,
                        "state": "valid",
                        "updatedBy": 0,
                        "updatedName": "",
                        "updatedTime": null,
                        "url": "www."
                    }
                ],
                "documentStatus": {
                    "createdBy": 0,
                    "createdName": "",
                    "createdTime": null,
                    "docId": 2,
                    "oid": 2,
                    "postFinishTime": null,
                    "postStatus": "",
                    "retrieveFinishTime": "2020-09-09 22:24:07",
                    "retrieveStatus": "finish",
                    "revision": 1,
                    "state": "valid",
                    "updatedBy": 0,
                    "updatedName": "",
                    "updatedTime": null
                },
                "orderNo": "hello_005",
                "remark": "画江湖",
                "revision": 1,
                "shDocumentData": null,
                "state": "valid",
                "updatedBy": 0,
                "updatedName": "",
                "updatedTime": null
            },
            {
                "blNo": "bl_004",
                "createdBy": 0,
                "createdName": "",
                "createdTime": null,
                "docId": 4,
                "docName": "from",
                "docNo": "doc4",
                "docType": "from",
                "documentFiles": [
                    {
                        "createdBy": 0,
                        "createdName": "",
                        "createdTime": null,
                        "docId": 4,
                        "fileNo": "rftyy",
                        "oid": 4,
                        "revision": 1,
                        "state": "valid",
                        "updatedBy": 0,
                        "updatedName": "",
                        "updatedTime": null,
                        "url": "http://"
                    }
                ],
                "documentStatus": {
                    "createdBy": 0,
                    "createdName": "",
                    "createdTime": null,
                    "docId": 4,
                    "oid": 4,
                    "postFinishTime": null,
                    "postStatus": "",
                    "retrieveFinishTime": "2020-09-09 09:11:11",
                    "retrieveStatus": "finish",
                    "revision": 1,
                    "state": "valid",
                    "updatedBy": 0,
                    "updatedName": "",
                    "updatedTime": null
                },
                "orderNo": "hello_006",
                "remark": "逍遥游",
                "revision": 1,
                "shDocumentData": null,
                "state": "valid",
                "updatedBy": 0,
                "updatedName": "",
                "updatedTime": null
            }
        ]
    }
};
