module.exports = (params) => {
    return {
        "code":0,
        "data":{
            "allColumns":[
            ],
            "configColumns":[
            ],
            "currPage":1,
            "list":[
                {   
                    "writeoffReceipayId":"0000000001",
                    "acctVoucherNo":"LYDE9258201200",
                    "writeoffReceipayNo":"YO1252238552",
                    "settleCompName":"长帆物流",
                    "payOrderNo":"1233232658",
                    "orderType":"prepay_write_off",
                    "balanceAmtBf":23432,
                    "currency":"CNY",
                    "payApplyNo":"2342",
                    "writeoffName":"勿动",
                    "writeoffTime":"2020-10-25 15:20:30",
                    "recheckName":"邓云",
                    "recheckTime":"",
                    "invoiceNoAppend":"",
                    "writeoffReverse":{
                        "writeoffReverseNo":"1000001"
                    }
                },
                {   
                    "writeoffReceipayId":"0000000002",
                    "acctVoucherNo":"LYDE9258201201",
                    "writeoffReceipayNo":"YO1252238553",
                    "settleCompName":"深圳市订单网络科技公司",
                    "payOrderNo":"1233232659",
                    "orderType":"wrong_transfer_prepay",
                    "balanceAmtBf":23432,
                    "currency":"USD",
                    "payApplyNo":"2342",
                    "writeoffName":"勿动",
                    "writeoffTime":"2020-10-25 15:50:30",
                    "recheckName":"肖彩云",
                    "recheckTime":"",
                    "invoiceNoAppend":"",
                    "writeoffReverse":{
                        "writeoffReverseNo":"1000002"
                    }
                },
                {   
                    "writeoffReceipayId":"0000000003",
                    "acctVoucherNo":"LYDE9258201201",
                    "writeoffReceipayNo":"YO1252238553",
                    "settleCompName":"深圳市订单网络科技公司",
                    "payOrderNo":"1233232659",
                    "orderType":"prepay",
                    "balanceAmtBf":23432,
                    "currency":"USD",
                    "payApplyNo":"2342",
                    "writeoffName":"勿动",
                    "writeoffTime":"2020-10-25 15:50:30",
                    "recheckName":"邓云",
                    "recheckTime":"",
                    "invoiceNoAppend":"",
                    "writeoffReverse":{
                        "writeoffReverseNo":"1000003"
                    }
                },
                {   
                    "writeoffReceipayId":"0000000005",
                    "acctVoucherNo":"LYDE9258201201",
                    "writeoffReceipayNo":"YO1252238553",
                    "settleCompName":"深圳市订单网络科技公司",
                    "payOrderNo":"1233232659",
                    "orderType":"settle",
                    "balanceAmtBf":23432,
                    "currency":"USD",
                    "payApplyNo":"2342",
                    "writeoffName":"勿动",
                    "writeoffTime":"2020-10-25 15:50:30",
                    "recheckName":"肖小霞",
                    "recheckTime":"",
                    "invoiceNoAppend":"",
                    "writeoffReverse":{
                        "writeoffReverseNo":"1000004"
                    }
                },
                {   
                    "writeoffReceipayId":"0000000006",
                    "acctVoucherNo":"LYDE9258201201",
                    "writeoffReceipayNo":"YO1252238553",
                    "settleCompName":"深圳市订单网络科技公司",
                    "payOrderNo":"1233232659",
                    "orderType":"refund",
                    "balanceAmtBf":23432,
                    "currency":"USD",
                    "payApplyNo":"2342",
                    "writeoffName":"勿动",
                    "writeoffTime":"2020-10-25 15:50:30",
                    "recheckName":"肖彩云",
                    "recheckTime":"",
                    "invoiceNoAppend":"",
                    "writeoffReverse":{
                        "writeoffReverseNo":"1000005"
                    }
                },
            ],
            "pageSize":10,
            "totalCount":1,
            "totalPage":1
        },
        "msg":"success"
    }
}